// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Repository.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Repository.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Repository.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// A {0} entry cannot be a leaf.
    /// </summary>
    private static string Frame_EntryCannotLeaf => Get(nameof(Frame_EntryCannotLeaf));

    /// <summary>
    /// A {0} entry cannot be a leaf.
    /// </summary>
    internal static string FormatFrame_EntryCannotLeaf(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, Frame_EntryCannotLeaf, arg0);

    /// <summary>
    /// Unknown scan event {0}.
    /// </summary>
    private static string Frame_UnknownScanEvent => Get(nameof(Frame_UnknownScanEvent));

    /// <summary>
    /// Unknown scan event {0}.
    /// </summary>
    internal static string FormatFrame_UnknownScanEvent(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, Frame_UnknownScanEvent, arg0);

    /// <summary>
    /// The store refused snapshot object '{0}' with a failed precondition.
    /// </summary>
    private static string ManifestBuilder_StoreRefusedSnapshotObjectWith => Get(nameof(ManifestBuilder_StoreRefusedSnapshotObjectWith));

    /// <summary>
    /// The store refused snapshot object '{0}' with a failed precondition.
    /// </summary>
    internal static string FormatManifestBuilder_StoreRefusedSnapshotObjectWith(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ManifestBuilder_StoreRefusedSnapshotObjectWith, arg0);

    /// <summary>
    /// The store refused blob '{0}' with a failed precondition.
    /// </summary>
    private static string PreparedSegment_StoreRefusedBlobWithFailed => Get(nameof(PreparedSegment_StoreRefusedBlobWithFailed));

    /// <summary>
    /// The store refused blob '{0}' with a failed precondition.
    /// </summary>
    internal static string FormatPreparedSegment_StoreRefusedBlobWithFailed(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, PreparedSegment_StoreRefusedBlobWithFailed, arg0);

    /// <summary>
    /// The store already holds a different object under blob key '{0}': this writer's blob identifier has been used before, which means its sequence state has regressed (specification 05 §5.1, 08 §2). The publication is refused while the source data still exists.
    /// </summary>
    private static string BlobUpload_StoreHeldDifferentBytesUnder => Get(nameof(BlobUpload_StoreHeldDifferentBytesUnder));

    /// <summary>
    /// The store already holds a different object under blob key '{0}': this writer's blob identifier has been used before, which means its sequence state has regressed (specification 05 §5.1, 08 §2). The publication is refused while the source data still exists.
    /// </summary>
    internal static string FormatBlobUpload_StoreHeldDifferentBytesUnder(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobUpload_StoreHeldDifferentBytesUnder, arg0);

    /// <summary>
    /// The scan produced no root directory.
    /// </summary>
    internal static string PublicationOrchestrator_ScanProducedNoRootDirectory => Get(nameof(PublicationOrchestrator_ScanProducedNoRootDirectory));

    /// <summary>
    /// Blob class 0x{0:x4} is not defined (specification 05 §2).
    /// </summary>
    private static string RepositoryKeySet_BlobClassXNotDefined => Get(nameof(RepositoryKeySet_BlobClassXNotDefined));

    /// <summary>
    /// Blob class 0x{0:x4} is not defined (specification 05 §2).
    /// </summary>
    internal static string FormatRepositoryKeySet_BlobClassXNotDefined(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryKeySet_BlobClassXNotDefined, arg0);

    /// <summary>
    /// The descriptor does not verify — nothing is exported from an unverifiable repository.
    /// </summary>
    internal static string RepositoryLifecycle_DescriptorDoesNotVerify => Get(nameof(RepositoryLifecycle_DescriptorDoesNotVerify));

    /// <summary>
    /// The descriptor is present but /keys/ listed no key object — a lagging store listing; retry rather than treating this as damage (ADR-0022 §Decision 3).
    /// </summary>
    internal static string RepositoryLifecycle_DescriptorPresentButKeysListed => Get(nameof(RepositoryLifecycle_DescriptorPresentButKeysListed));

    /// <summary>
    /// The descriptor's digest does not verify — accidental corruption (specification 01 §3.1).
    /// </summary>
    internal static string RepositoryLifecycle_DescriptorSDigestDoesNot => Get(nameof(RepositoryLifecycle_DescriptorSDigestDoesNot));

    /// <summary>
    /// No repository descriptor exists at /repository-format.
    /// </summary>
    internal static string RepositoryLifecycle_NoRepositoryDescriptorExistsRepository => Get(nameof(RepositoryLifecycle_NoRepositoryDescriptorExistsRepository));

    /// <summary>
    /// No /repository-format object exists — this location does not hold a FallbackPlan repository (specification 01 §3).
    /// </summary>
    internal static string RepositoryLifecycle_NoRepositoryFormatObjectExists => Get(nameof(RepositoryLifecycle_NoRepositoryFormatObjectExists));

    /// <summary>
    /// The object at /repository-format is not a FallbackPlan repository descriptor (specification 01 §3.1).
    /// </summary>
    internal static string RepositoryLifecycle_ObjectRepositoryFormatNotFallbackPlan => Get(nameof(RepositoryLifecycle_ObjectRepositoryFormatNotFallbackPlan));

    /// <summary>
    /// The store refused '{0}' with {1} — an existing object at this key means the location already holds a repository (specification 01 §4).
    /// </summary>
    private static string RepositoryLifecycle_StoreRefusedWith => Get(nameof(RepositoryLifecycle_StoreRefusedWith));

    /// <summary>
    /// The store refused '{0}' with {1} — an existing object at this key means the location already holds a repository (specification 01 §4).
    /// </summary>
    internal static string FormatRepositoryLifecycle_StoreRefusedWith(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryLifecycle_StoreRefusedWith, arg0, arg1);

    /// <summary>
    /// Unrecognised descriptor parse outcome {0}.
    /// </summary>
    private static string RepositoryLifecycle_UnrecognisedDescriptorParseOutcome => Get(nameof(RepositoryLifecycle_UnrecognisedDescriptorParseOutcome));

    /// <summary>
    /// Unrecognised descriptor parse outcome {0}.
    /// </summary>
    internal static string FormatRepositoryLifecycle_UnrecognisedDescriptorParseOutcome(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryLifecycle_UnrecognisedDescriptorParseOutcome, arg0);

    /// <summary>
    /// A source key is exactly {0} bytes.
    /// </summary>
    private static string struct_SourceKeyExactlyBytes => Get(nameof(struct_SourceKeyExactlyBytes));

    /// <summary>
    /// A source key is exactly {0} bytes.
    /// </summary>
    internal static string Formatstruct_SourceKeyExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, struct_SourceKeyExactlyBytes, arg0);
}
