// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Repository.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Repository.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Repository.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// A {0} entry cannot be a leaf.
    /// </summary>
    private static string Frame_EntryCannotLeaf => Get(nameof(Frame_EntryCannotLeaf));

    /// <summary>
    /// A {0} entry cannot be a leaf.
    /// </summary>
    internal static string FormatFrame_EntryCannotLeaf(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, Frame_EntryCannotLeaf, arg0);

    /// <summary>
    /// Unknown scan event {0}.
    /// </summary>
    private static string Frame_UnknownScanEvent => Get(nameof(Frame_UnknownScanEvent));

    /// <summary>
    /// Unknown scan event {0}.
    /// </summary>
    internal static string FormatFrame_UnknownScanEvent(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, Frame_UnknownScanEvent, arg0);

    /// <summary>
    /// The store refused snapshot object '{0}' with a failed precondition.
    /// </summary>
    private static string ManifestBuilder_StoreRefusedSnapshotObjectWith => Get(nameof(ManifestBuilder_StoreRefusedSnapshotObjectWith));

    /// <summary>
    /// The store refused snapshot object '{0}' with a failed precondition.
    /// </summary>
    internal static string FormatManifestBuilder_StoreRefusedSnapshotObjectWith(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ManifestBuilder_StoreRefusedSnapshotObjectWith, arg0);

    /// <summary>
    /// The store refused blob '{0}' with a failed precondition.
    /// </summary>
    private static string PreparedSegment_StoreRefusedBlobWithFailed => Get(nameof(PreparedSegment_StoreRefusedBlobWithFailed));

    /// <summary>
    /// The store refused blob '{0}' with a failed precondition.
    /// </summary>
    internal static string FormatPreparedSegment_StoreRefusedBlobWithFailed(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, PreparedSegment_StoreRefusedBlobWithFailed, arg0);

    /// <summary>
    /// The store already holds a different object under blob key '{0}': this writer's blob identifier has been used before, which means its sequence state has regressed (specification 05 §5.1, 08 §2). The publication is refused while the source data still exists.
    /// </summary>
    private static string BlobUpload_StoreHeldDifferentBytesUnder => Get(nameof(BlobUpload_StoreHeldDifferentBytesUnder));

    /// <summary>
    /// The store already holds a different object under blob key '{0}': this writer's blob identifier has been used before, which means its sequence state has regressed (specification 05 §5.1, 08 §2). The publication is refused while the source data still exists.
    /// </summary>
    internal static string FormatBlobUpload_StoreHeldDifferentBytesUnder(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobUpload_StoreHeldDifferentBytesUnder, arg0);

    /// <summary>
    /// The scan produced no root directory.
    /// </summary>
    internal static string PublicationOrchestrator_ScanProducedNoRootDirectory => Get(nameof(PublicationOrchestrator_ScanProducedNoRootDirectory));

    /// <summary>
    /// Blob class 0x{0:x4} is not defined (specification 05 §2).
    /// </summary>
    private static string RepositoryKeySet_BlobClassXNotDefined => Get(nameof(RepositoryKeySet_BlobClassXNotDefined));

    /// <summary>
    /// Blob class 0x{0:x4} is not defined (specification 05 §2).
    /// </summary>
    internal static string FormatRepositoryKeySet_BlobClassXNotDefined(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryKeySet_BlobClassXNotDefined, arg0);

    /// <summary>
    /// The descriptor's digest does not verify — accidental corruption (specification 01 §3.1).
    /// </summary>
    internal static string RepositoryLifecycle_DescriptorSDigestDoesNot => Get(nameof(RepositoryLifecycle_DescriptorSDigestDoesNot));

    /// <summary>
    /// No /repository-format object exists — this location does not hold a FallbackPlan repository (specification 01 §3).
    /// </summary>
    internal static string RepositoryLifecycle_NoRepositoryFormatObjectExists => Get(nameof(RepositoryLifecycle_NoRepositoryFormatObjectExists));

    /// <summary>
    /// The object at /repository-format is not a FallbackPlan repository descriptor (specification 01 §3.1).
    /// </summary>
    internal static string RepositoryLifecycle_ObjectRepositoryFormatNotFallbackPlan => Get(nameof(RepositoryLifecycle_ObjectRepositoryFormatNotFallbackPlan));

    /// <summary>
    /// The store refused '{0}' with {1} — an existing object at this key means the location already holds a repository (specification 01 §4).
    /// </summary>
    private static string RepositoryLifecycle_StoreRefusedWith => Get(nameof(RepositoryLifecycle_StoreRefusedWith));

    /// <summary>
    /// The store refused '{0}' with {1} — an existing object at this key means the location already holds a repository (specification 01 §4).
    /// </summary>
    internal static string FormatRepositoryLifecycle_StoreRefusedWith(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryLifecycle_StoreRefusedWith, arg0, arg1);

    /// <summary>
    /// Unrecognised descriptor parse outcome {0}.
    /// </summary>
    private static string RepositoryLifecycle_UnrecognisedDescriptorParseOutcome => Get(nameof(RepositoryLifecycle_UnrecognisedDescriptorParseOutcome));

    /// <summary>
    /// Unrecognised descriptor parse outcome {0}.
    /// </summary>
    internal static string FormatRepositoryLifecycle_UnrecognisedDescriptorParseOutcome(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryLifecycle_UnrecognisedDescriptorParseOutcome, arg0);

    /// <summary>
    /// A source key is exactly {0} bytes.
    /// </summary>
    private static string struct_SourceKeyExactlyBytes => Get(nameof(struct_SourceKeyExactlyBytes));

    /// <summary>
    /// A source key is exactly {0} bytes.
    /// </summary>
    internal static string Formatstruct_SourceKeyExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, struct_SourceKeyExactlyBytes, arg0);

    /// <summary>
    /// The write credential does not belong to this repository: its sealing public key disagrees with the descriptor's (ADR-0042).
    /// </summary>
    internal static string RepositoryLifecycle_CredentialNotThisRepository => Get(nameof(RepositoryLifecycle_CredentialNotThisRepository));

    /// <summary>
    /// The passphrase does not reproduce this repository's keys (ADR-0042): the derived public key disagrees with the descriptor's.
    /// </summary>
    internal static string RepositoryLifecycle_PassphraseDoesNotReproduce => Get(nameof(RepositoryLifecycle_PassphraseDoesNotReproduce));

    /// <summary>
    /// A repository holds no data class key: content is sealed to the repository's public key and opened only under a read authority (specification 03 §9.2). Asking for one is a bug in the caller.
    /// </summary>
    internal static string RepositoryKeySet_NoDataClassKey => Get(nameof(RepositoryKeySet_NoDataClassKey));

    /// <summary>
    /// This repository already writes format version {0}; there is nothing to upgrade.
    /// </summary>
    private static string RepositoryLifecycle_AlreadyAtFormatVersion => Get(nameof(RepositoryLifecycle_AlreadyAtFormatVersion));

    /// <summary>
    /// This repository already writes format version {0}; there is nothing to upgrade.
    /// </summary>
    internal static string FormatRepositoryLifecycle_AlreadyAtFormatVersion(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryLifecycle_AlreadyAtFormatVersion, arg0);

    /// <summary>
    /// Format version {0} is not above this repository's effective version, {1}; an upgrade moves forward.
    /// </summary>
    private static string RepositoryLifecycle_UpgradeBelowEffectiveVersion => Get(nameof(RepositoryLifecycle_UpgradeBelowEffectiveVersion));

    /// <summary>
    /// Format version {0} is not above this repository's effective version, {1}; an upgrade moves forward.
    /// </summary>
    internal static string FormatRepositoryLifecycle_UpgradeBelowEffectiveVersion(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryLifecycle_UpgradeBelowEffectiveVersion, arg0, arg1);

    /// <summary>
    /// Compaction relocates sealed records, which only format 3 permits; at format 2 a record's key is its blob's and moving it means opening it, which a write-only service cannot do (ADR-0025, ADR-0052).
    /// </summary>
    internal static string BlobCompactor_CompactionNeedsFormatThree => Get(nameof(BlobCompactor_CompactionNeedsFormatThree));

    /// <summary>
    /// The compaction source '{0}' is not in the store it was planned from; nothing was relocated out of it.
    /// </summary>
    private static string BlobCompactor_SourceBlobMissing => Get(nameof(BlobCompactor_SourceBlobMissing));

    /// <summary>
    /// The compaction source '{0}' is not in the store it was planned from; nothing was relocated out of it.
    /// </summary>
    internal static string FormatBlobCompactor_SourceBlobMissing(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobCompactor_SourceBlobMissing, arg0);

    /// <summary>
    /// Record {1} of compaction source '{0}' was refused rather than relocated: {2}. A compactor that carried it anyway would launder damage into a blob nothing suspects.
    /// </summary>
    private static string BlobCompactor_SourceRecordRefused => Get(nameof(BlobCompactor_SourceRecordRefused));

    /// <summary>
    /// Record {1} of compaction source '{0}' was refused rather than relocated: {2}. A compactor that carried it anyway would launder damage into a blob nothing suspects.
    /// </summary>
    internal static string FormatBlobCompactor_SourceRecordRefused(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, BlobCompactor_SourceRecordRefused, arg0, arg1, arg2);

    /// <summary>
    /// Compacted blob {0} carries {1} record(s), whose index entries alone exceed one delta's budget of {2} bytes; a delta over the metadata-object bound is written without complaint and refused on read, so it is refused here instead.
    /// </summary>
    private static string CompactionPublication_BlobExceedsDeltaBudget => Get(nameof(CompactionPublication_BlobExceedsDeltaBudget));

    /// <summary>
    /// Compacted blob {0} carries {1} record(s), whose index entries alone exceed one delta's budget of {2} bytes; a delta over the metadata-object bound is written without complaint and refused on read, so it is refused here instead.
    /// </summary>
    internal static string FormatCompactionPublication_BlobExceedsDeltaBudget(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, CompactionPublication_BlobExceedsDeltaBudget, arg0, arg1, arg2);

    /// <summary>
    /// The store already held different bytes under '{0}'; a freshly allocated blob identifier collided, so the sequence state regressed and an index published over it would name a blob that cannot be read back.
    /// </summary>
    private static string CompactionPublication_StoreHeldDifferentBytes => Get(nameof(CompactionPublication_StoreHeldDifferentBytes));

    /// <summary>
    /// The store already held different bytes under '{0}'; a freshly allocated blob identifier collided, so the sequence state regressed and an index published over it would name a blob that cannot be read back.
    /// </summary>
    internal static string FormatCompactionPublication_StoreHeldDifferentBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CompactionPublication_StoreHeldDifferentBytes, arg0);

    /// <summary>
    /// The store refused the compacted blob '{0}' on its if-absent put; nothing was published for it.
    /// </summary>
    private static string CompactionPublication_StoreRefusedBlob => Get(nameof(CompactionPublication_StoreRefusedBlob));

    /// <summary>
    /// The store refused the compacted blob '{0}' on its if-absent put; nothing was published for it.
    /// </summary>
    internal static string FormatCompactionPublication_StoreRefusedBlob(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CompactionPublication_StoreRefusedBlob, arg0);

    /// <summary>
    /// This repository is at format {0}; compaction relocates sealed records and that is a format-3 property. Below it a rewrite means decrypt-and-reseal, which needs a content key this service does not hold — upgrade the set's format first.
    /// </summary>
    private static string CompactionPass_NeedsFormatThree => Get(nameof(CompactionPass_NeedsFormatThree));

    /// <summary>
    /// This repository is at format {0}; compaction relocates sealed records and that is a format-3 property. Below it a rewrite means decrypt-and-reseal, which needs a content key this service does not hold — upgrade the set's format first.
    /// </summary>
    internal static string FormatCompactionPass_NeedsFormatThree(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CompactionPass_NeedsFormatThree, arg0);

    /// <summary>
    /// This store declares no conditional create, and every durable step of a publication is an if-absent put — without it a write over a live key answers 'created', which is how a sealed blob would be silently replaced. Refused rather than guessed (ADR-0012).
    /// </summary>
    internal static string StoreAdmission_NoConditionalCreate => Get(nameof(StoreAdmission_NoConditionalCreate));

    /// <summary>
    /// This store declares no ranged reads, and opening a blob needs three of them before a single record is read. Refused rather than guessed (ADR-0012).
    /// </summary>
    internal static string StoreAdmission_NoRangedReads => Get(nameof(StoreAdmission_NoRangedReads));
}
