// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Keystore.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Keystore.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Keystore.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// '{0}' is readable beyond its owner ({1}). It is refused rather than used: the only thing protecting it is its permissions.
    /// </summary>
    private static string LinuxOwnerOnlyFileStore_ReadableBeyondOwnerRefusedRather => Get(nameof(LinuxOwnerOnlyFileStore_ReadableBeyondOwnerRefusedRather));

    /// <summary>
    /// '{0}' is readable beyond its owner ({1}). It is refused rather than used: the only thing protecting it is its permissions.
    /// </summary>
    internal static string FormatLinuxOwnerOnlyFileStore_ReadableBeyondOwnerRefusedRather(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, LinuxOwnerOnlyFileStore_ReadableBeyondOwnerRefusedRather, arg0, arg1);

    /// <summary>
    /// The macOS keychain refused a lookup for '{0}' (status {1}).
    /// </summary>
    private static string MacOsKeychainStore_MacOSKeychainRefusedLookupStatus => Get(nameof(MacOsKeychainStore_MacOSKeychainRefusedLookupStatus));

    /// <summary>
    /// The macOS keychain refused a lookup for '{0}' (status {1}).
    /// </summary>
    internal static string FormatMacOsKeychainStore_MacOSKeychainRefusedLookupStatus(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, MacOsKeychainStore_MacOSKeychainRefusedLookupStatus, arg0, arg1);

    /// <summary>
    /// The macOS keychain refused to store '{0}' (status {1}).
    /// </summary>
    private static string MacOsKeychainStore_MacOSKeychainRefusedStoreStatus => Get(nameof(MacOsKeychainStore_MacOSKeychainRefusedStoreStatus));

    /// <summary>
    /// The macOS keychain refused to store '{0}' (status {1}).
    /// </summary>
    internal static string FormatMacOsKeychainStore_MacOSKeychainRefusedStoreStatus(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, MacOsKeychainStore_MacOSKeychainRefusedStoreStatus, arg0, arg1);

    /// <summary>
    /// No keystore is implemented for {0}. Unattended unlock is unavailable on this platform; pass the passphrase by environment-variable name instead.
    /// </summary>
    private static string PlatformKeystore_NoKeystoreImplementedUnattendedUnlock => Get(nameof(PlatformKeystore_NoKeystoreImplementedUnattendedUnlock));

    /// <summary>
    /// No keystore is implemented for {0}. Unattended unlock is unavailable on this platform; pass the passphrase by environment-variable name instead.
    /// </summary>
    internal static string FormatPlatformKeystore_NoKeystoreImplementedUnattendedUnlock(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, PlatformKeystore_NoKeystoreImplementedUnattendedUnlock, arg0);
}
