using FallbackPlan.Domain.Identifiers;
using FallbackPlan.Repository.Crypto;
using FallbackPlan.TestSupport;

namespace FallbackPlan.Repository.Tests.Crypto;

/// <summary>
/// NFR-SEC-003's stated acceptance, written at last as the property it names:
/// "no <c>(key, nonce)</c> pair repeats across any generated sequence." The
/// record nonce is the ordinal, and the key is the per-blob derived key, so a
/// repeated pair is the AES-GCM catastrophe the whole construction exists to
/// prevent — two plaintexts under one keystream. The construction defends it
/// two ways at once, and the property holds them together: within a blob the
/// key is fixed and ordinals are dense and distinct; across blobs a fresh
/// random salt makes the derived key distinct even when writer and counter
/// repeat.
/// </summary>
[TestClass]
public sealed class NonceUniquenessTests
{
    [TestMethod]
    public void RecordKeystream_AcrossManyBlobsAndOrdinals_NoKeyNoncePairRepeats() =>
        PropertyCheck.Holds(this);

    public static bool RecordKeystream_AcrossManyBlobsAndOrdinals_NoKeyNoncePairRepeatsProperty(byte[]? saltEntropy, byte recordsPerBlob)
    {
        // A run's worth of blobs. Each draws its own salt from the generated
        // entropy; the writer and the class key are shared, and the counter is
        // reused deliberately — modelling the very collision (same writer, same
        // counter, a crash-restarted blob) that only the fresh salt separates.
        var classKey = new byte[32];
        var writer = WriterId.FromBytes(new byte[WriterId.Size]);
        var records = 1 + recordsPerBlob % 64;

        var salts = SaltsFrom(saltEntropy);
        var seen = new HashSet<string>();

        foreach (var salt in salts)
        {
            var key = new byte[BlobKeyDeriver.BlobKeyLength];
            BlobKeyDeriver.Derive(classKey, salt, writer, blobCounter: 7, key);
            var keyHex = Convert.ToHexStringLower(key);

            for (ushort ordinal = 0; ordinal < records; ordinal++)
            {
                if (!seen.Add($"{keyHex}:{ordinal}"))
                {
                    return false;
                }
            }
        }

        return true;
    }

    private static List<byte[]> SaltsFrom(byte[]? entropy)
    {
        // At least a few blobs, each with a distinct salt derived from the
        // generated bytes plus its index — distinct salts are the precondition
        // the format guarantees with a per-blob CSPRNG draw, and the property is
        // that distinct salts keep the keystreams disjoint.
        var count = 4 + (entropy?.Length ?? 0) % 8;
        var salts = new List<byte[]>(count);
        for (var index = 0; index < count; index++)
        {
            var salt = new byte[BlobKeyDeriver.BlobSaltLength];
            entropy?.AsSpan(0, Math.Min(entropy.Length, salt.Length)).CopyTo(salt);
            salt[0] ^= (byte)index;
            salt[1] ^= (byte)(index >> 8);
            salts.Add(salt);
        }

        return salts;
    }
}
