// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Domain.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Domain.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Domain.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// A blob identifier is exactly {0} bytes; got {1}.
    /// </summary>
    private static string BlobId_BlobIdentifierExactlyBytesGot => Get(nameof(BlobId_BlobIdentifierExactlyBytesGot));

    /// <summary>
    /// A blob identifier is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatBlobId_BlobIdentifierExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobId_BlobIdentifierExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// Destination must hold at least {0} bytes.
    /// </summary>
    private static string BlobId_DestinationMustHoldLeastBytes => Get(nameof(BlobId_DestinationMustHoldLeastBytes));

    /// <summary>
    /// Destination must hold at least {0} bytes.
    /// </summary>
    internal static string FormatBlobId_DestinationMustHoldLeastBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobId_DestinationMustHoldLeastBytes, arg0);

    /// <summary>
    /// A checkpoint identifier is exactly {0} bytes; got {1}.
    /// </summary>
    private static string CheckpointId_CheckpointIdentifierExactlyBytesGot => Get(nameof(CheckpointId_CheckpointIdentifierExactlyBytesGot));

    /// <summary>
    /// A checkpoint identifier is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatCheckpointId_CheckpointIdentifierExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, CheckpointId_CheckpointIdentifierExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// A content identifier is exactly {0} bytes; got {1}.
    /// </summary>
    private static string ContentId_ContentIdentifierExactlyBytesGot => Get(nameof(ContentId_ContentIdentifierExactlyBytesGot));

    /// <summary>
    /// A content identifier is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatContentId_ContentIdentifierExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ContentId_ContentIdentifierExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// A delta identifier is exactly {0} bytes; got {1}.
    /// </summary>
    private static string DeltaId_DeltaIdentifierExactlyBytesGot => Get(nameof(DeltaId_DeltaIdentifierExactlyBytesGot));

    /// <summary>
    /// A delta identifier is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatDeltaId_DeltaIdentifierExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, DeltaId_DeltaIdentifierExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// A key identifier is exactly {0} bytes; got {1}.
    /// </summary>
    private static string KeyId_KeyIdentifierExactlyBytesGot => Get(nameof(KeyId_KeyIdentifierExactlyBytesGot));

    /// <summary>
    /// A key identifier is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatKeyId_KeyIdentifierExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, KeyId_KeyIdentifierExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// An object identifier is exactly {0} bytes; got {1}.
    /// </summary>
    private static string ObjectId_ObjectIdentifierExactlyBytesGot => Get(nameof(ObjectId_ObjectIdentifierExactlyBytesGot));

    /// <summary>
    /// An object identifier is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatObjectId_ObjectIdentifierExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ObjectId_ObjectIdentifierExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// A repository identifier is exactly {0} bytes; got {1}.
    /// </summary>
    private static string RepositoryId_RepositoryIdentifierExactlyBytesGot => Get(nameof(RepositoryId_RepositoryIdentifierExactlyBytesGot));

    /// <summary>
    /// A repository identifier is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatRepositoryId_RepositoryIdentifierExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryId_RepositoryIdentifierExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// A store blob key is exactly {0} bytes; got {1}.
    /// </summary>
    private static string StoreBlobKey_StoreBlobKeyExactlyBytes => Get(nameof(StoreBlobKey_StoreBlobKeyExactlyBytes));

    /// <summary>
    /// A store blob key is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatStoreBlobKey_StoreBlobKeyExactlyBytes(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, StoreBlobKey_StoreBlobKeyExactlyBytes, arg0, arg1);

    /// <summary>
    /// A writer identifier is exactly {0} bytes; got {1}.
    /// </summary>
    private static string WriterId_WriterIdentifierExactlyBytesGot => Get(nameof(WriterId_WriterIdentifierExactlyBytesGot));

    /// <summary>
    /// A writer identifier is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatWriterId_WriterIdentifierExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, WriterId_WriterIdentifierExactlyBytesGot, arg0, arg1);
}
