// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Retention.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Retention.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Retention.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// The name a deletion is recorded under is at most {0} UTF-8 bytes; nothing was requested.
    /// </summary>
    private static string SnapshotDeletion_ActorTooLong => Get(nameof(SnapshotDeletion_ActorTooLong));

    /// <summary>
    /// The name a deletion is recorded under is at most {0} UTF-8 bytes; nothing was requested.
    /// </summary>
    internal static string FormatSnapshotDeletion_ActorTooLong(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, SnapshotDeletion_ActorTooLong, arg0);

    /// <summary>
    /// The store would not replace the tombstone already held for snapshot {0} ({1}), so its deletion was not requested.
    /// </summary>
    private static string SnapshotDeletion_TombstoneWouldNotBeReplaced => Get(nameof(SnapshotDeletion_TombstoneWouldNotBeReplaced));

    /// <summary>
    /// The store would not replace the tombstone already held for snapshot {0} ({1}), so its deletion was not requested.
    /// </summary>
    internal static string FormatSnapshotDeletion_TombstoneWouldNotBeReplaced(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, SnapshotDeletion_TombstoneWouldNotBeReplaced, arg0, arg1);

    /// <summary>
    /// The store did not keep the deletion request for snapshot {0}; nothing will delete it until the request is made again.
    /// </summary>
    private static string SnapshotDeletion_RequestNotHeld => Get(nameof(SnapshotDeletion_RequestNotHeld));

    /// <summary>
    /// The store did not keep the deletion request for snapshot {0}; nothing will delete it until the request is made again.
    /// </summary>
    internal static string FormatSnapshotDeletion_RequestNotHeld(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, SnapshotDeletion_RequestNotHeld, arg0);
}
