// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Cli.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Cli.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Cli.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// '{0}' does not exist.
    /// </summary>
    private static string CliApplication_DoesNotExist => Get(nameof(CliApplication_DoesNotExist));

    /// <summary>
    /// '{0}' does not exist.
    /// </summary>
    internal static string FormatCliApplication_DoesNotExist(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CliApplication_DoesNotExist, arg0);

    /// <summary>
    /// '{0}' does not exist in snapshot {1} — or the catalogue is stale; run `rebuild-index`.
    /// </summary>
    private static string CliApplication_DoesNotExistSnapshot => Get(nameof(CliApplication_DoesNotExistSnapshot));

    /// <summary>
    /// '{0}' does not exist in snapshot {1} — or the catalogue is stale; run `rebuild-index`.
    /// </summary>
    internal static string FormatCliApplication_DoesNotExistSnapshot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, CliApplication_DoesNotExistSnapshot, arg0, arg1);

    /// <summary>
    /// The manifest record failed to read: {0}.
    /// </summary>
    private static string CliApplication_ManifestRecordFailedRead => Get(nameof(CliApplication_ManifestRecordFailedRead));

    /// <summary>
    /// The manifest record failed to read: {0}.
    /// </summary>
    internal static string FormatCliApplication_ManifestRecordFailedRead(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CliApplication_ManifestRecordFailedRead, arg0);

    /// <summary>
    /// No object exists at '{0}'.
    /// </summary>
    private static string CliApplication_NoObjectExists => Get(nameof(CliApplication_NoObjectExists));

    /// <summary>
    /// No object exists at '{0}'.
    /// </summary>
    internal static string FormatCliApplication_NoObjectExists(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CliApplication_NoObjectExists, arg0);

    /// <summary>
    /// No record with that object identifier exists in any loaded blob.
    /// </summary>
    internal static string CliApplication_NoRecordWithObjectIdentifier => Get(nameof(CliApplication_NoRecordWithObjectIdentifier));

    /// <summary>
    /// No snapshot {0} exists in this repository.
    /// </summary>
    private static string CliApplication_NoSnapshotExistsRepository => Get(nameof(CliApplication_NoSnapshotExistsRepository));

    /// <summary>
    /// No snapshot {0} exists in this repository.
    /// </summary>
    internal static string FormatCliApplication_NoSnapshotExistsRepository(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CliApplication_NoSnapshotExistsRepository, arg0);

    /// <summary>
    /// '{0}' is not a 64-hex-digit object identifier.
    /// </summary>
    private static string CliApplication_NotHexDigitObjectIdentifier => Get(nameof(CliApplication_NotHexDigitObjectIdentifier));

    /// <summary>
    /// '{0}' is not a 64-hex-digit object identifier.
    /// </summary>
    internal static string FormatCliApplication_NotHexDigitObjectIdentifier(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CliApplication_NotHexDigitObjectIdentifier, arg0);

    /// <summary>
    /// Pass --manifest &lt;object-id&gt; or --snapshot &lt;snapshot-id&gt;.
    /// </summary>
    internal static string CliApplication_PassManifestObjectIdSnapshot => Get(nameof(CliApplication_PassManifestObjectIdSnapshot));

    /// <summary>
    /// The record failed to read: {0}.
    /// </summary>
    private static string CliApplication_RecordFailedRead => Get(nameof(CliApplication_RecordFailedRead));

    /// <summary>
    /// The record failed to read: {0}.
    /// </summary>
    internal static string FormatCliApplication_RecordFailedRead(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CliApplication_RecordFailedRead, arg0);

    /// <summary>
    /// Restore refused: {0}
    /// </summary>
    private static string CliApplication_RestoreRefused => Get(nameof(CliApplication_RestoreRefused));

    /// <summary>
    /// Restore refused: {0}
    /// </summary>
    internal static string FormatCliApplication_RestoreRefused(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CliApplication_RestoreRefused, arg0);

    /// <summary>
    /// snapshot {0} is not in the catalogue — check `snapshots`, or run `rebuild-index` if it is stale.
    /// </summary>
    private static string CliApplication_SnapshotNotCatalogue => Get(nameof(CliApplication_SnapshotNotCatalogue));

    /// <summary>
    /// snapshot {0} is not in the catalogue — check `snapshots`, or run `rebuild-index` if it is stale.
    /// </summary>
    internal static string FormatCliApplication_SnapshotNotCatalogue(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CliApplication_SnapshotNotCatalogue, arg0);

    /// <summary>
    /// The snapshot's root tree failed to read: {0}.
    /// </summary>
    private static string CliApplication_SnapshotSRootTreeFailed => Get(nameof(CliApplication_SnapshotSRootTreeFailed));

    /// <summary>
    /// The snapshot's root tree failed to read: {0}.
    /// </summary>
    internal static string FormatCliApplication_SnapshotSRootTreeFailed(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CliApplication_SnapshotSRootTreeFailed, arg0);

    /// <summary>
    /// The snapshot's tree holds no file entry.
    /// </summary>
    internal static string CliApplication_SnapshotSTreeHoldsNo => Get(nameof(CliApplication_SnapshotSTreeHoldsNo));

    /// <summary>
    /// --target-snapshot requires --forensic; the checkpoint-plus-delta rebuild is already bounded.
    /// </summary>
    internal static string CliApplication_TargetSnapshotRequiresForensicCheckpoint => Get(nameof(CliApplication_TargetSnapshotRequiresForensicCheckpoint));

    /// <summary>
    /// Environment variable '{0}' is unset or empty — the passphrase is passed by name, never on the command line.
    /// </summary>
    private static string CliSession_EnvironmentVariableUnsetEmpty => Get(nameof(CliSession_EnvironmentVariableUnsetEmpty));

    /// <summary>
    /// Environment variable '{0}' is unset or empty — the passphrase is passed by name, never on the command line.
    /// </summary>
    internal static string FormatCliSession_EnvironmentVariableUnsetEmpty(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CliSession_EnvironmentVariableUnsetEmpty, arg0);

    /// <summary>
    /// The catalogue knows nothing under snapshot {0} — run `rebuild-index` first.
    /// </summary>
    private static string DirectGateway_CatalogueKnowsNothingUnderSnapshot => Get(nameof(DirectGateway_CatalogueKnowsNothingUnderSnapshot));

    /// <summary>
    /// The catalogue knows nothing under snapshot {0} — run `rebuild-index` first.
    /// </summary>
    internal static string FormatDirectGateway_CatalogueKnowsNothingUnderSnapshot(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, DirectGateway_CatalogueKnowsNothingUnderSnapshot, arg0);

    /// <summary>
    /// No backup set named '{0}' exists in {1}.
    /// </summary>
    private static string DirectGateway_NoBackupSetNamedExists => Get(nameof(DirectGateway_NoBackupSetNamedExists));

    /// <summary>
    /// No backup set named '{0}' exists in {1}.
    /// </summary>
    internal static string FormatDirectGateway_NoBackupSetNamedExists(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, DirectGateway_NoBackupSetNamedExists, arg0, arg1);

    /// <summary>
    /// '{0}' is not a directory.
    /// </summary>
    private static string DirectGateway_NotDirectory => Get(nameof(DirectGateway_NotDirectory));

    /// <summary>
    /// '{0}' is not a directory.
    /// </summary>
    internal static string FormatDirectGateway_NotDirectory(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, DirectGateway_NotDirectory, arg0);

    /// <summary>
    /// '{0}' is not a verify level (locator | digest | records).
    /// </summary>
    private static string DirectGateway_NotVerifyLevelLocatorDigest => Get(nameof(DirectGateway_NotVerifyLevelLocatorDigest));

    /// <summary>
    /// '{0}' is not a verify level (locator | digest | records).
    /// </summary>
    internal static string FormatDirectGateway_NotVerifyLevelLocatorDigest(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, DirectGateway_NotVerifyLevelLocatorDigest, arg0);

    /// <summary>
    /// Pass a root directory or --set &lt;name&gt;.
    /// </summary>
    internal static string DirectGateway_PassRootDirectorySetName => Get(nameof(DirectGateway_PassRootDirectorySetName));

    /// <summary>
    /// Retention runs on the hub — the pass needs the service's configuration, sync ledger and writer role. Connect to it with --connect, or run `fallbackplan-agent retention [--apply]` there.
    /// </summary>
    internal static string DirectGateway_RetentionNeedsTheService => Get(nameof(DirectGateway_RetentionNeedsTheService));

    /// <summary>
    /// Verifying a destination runs on the hub — the sweep resumes from a cursor in the service's ledger, so a direct-mode pass would re-read the same objects forever and never record that it had. Connect to it with --connect, or run `fallbackplan-agent verify-destination` there.
    /// </summary>
    internal static string DirectGateway_VerifyDestinationNeedsTheService => Get(nameof(DirectGateway_VerifyDestinationNeedsTheService));

    /// <summary>
    /// Syncing destinations is the service's job — its scheduler, ledger and staging archives do the work. Connect to it with --connect, or run `fallbackplan-agent sync` on the hub when no service is running.
    /// </summary>
    internal static string DirectGateway_SyncNeedsTheService => Get(nameof(DirectGateway_SyncNeedsTheService));

    /// <summary>
    /// The service answered a backup with {0}.
    /// </summary>
    private static string ServiceGateway_ServiceAnsweredBackupWith => Get(nameof(ServiceGateway_ServiceAnsweredBackupWith));

    /// <summary>
    /// The service answered a backup with {0}.
    /// </summary>
    internal static string FormatServiceGateway_ServiceAnsweredBackupWith(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ServiceGateway_ServiceAnsweredBackupWith, arg0);

    /// <summary>
    /// The service answered a job list with {0}.
    /// </summary>
    private static string ServiceGateway_ServiceAnsweredJobListWith => Get(nameof(ServiceGateway_ServiceAnsweredJobListWith));

    /// <summary>
    /// The service answered a job list with {0}.
    /// </summary>
    internal static string FormatServiceGateway_ServiceAnsweredJobListWith(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ServiceGateway_ServiceAnsweredJobListWith, arg0);

    /// <summary>
    /// The service answered {0} with {1}.
    /// </summary>
    private static string ServiceGateway_ServiceAnsweredWith => Get(nameof(ServiceGateway_ServiceAnsweredWith));

    /// <summary>
    /// The service answered {0} with {1}.
    /// </summary>
    internal static string FormatServiceGateway_ServiceAnsweredWith(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ServiceGateway_ServiceAnsweredWith, arg0, arg1);

    /// <summary>
    /// The service forgot job '{0}' before it finished.
    /// </summary>
    private static string ServiceGateway_ServiceForgotJobBeforeFinished => Get(nameof(ServiceGateway_ServiceForgotJobBeforeFinished));

    /// <summary>
    /// The service forgot job '{0}' before it finished.
    /// </summary>
    internal static string FormatServiceGateway_ServiceForgotJobBeforeFinished(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ServiceGateway_ServiceForgotJobBeforeFinished, arg0);

    /// <summary>
    /// The service refused {0}: {1}
    /// </summary>
    private static string ServiceGateway_ServiceRefused => Get(nameof(ServiceGateway_ServiceRefused));

    /// <summary>
    /// The service refused {0}: {1}
    /// </summary>
    internal static string FormatServiceGateway_ServiceRefused(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ServiceGateway_ServiceRefused, arg0, arg1);

    /// <summary>
    /// The service refused the backup: {0}
    /// </summary>
    private static string ServiceGateway_ServiceRefusedBackup => Get(nameof(ServiceGateway_ServiceRefusedBackup));

    /// <summary>
    /// The service refused the backup: {0}
    /// </summary>
    internal static string FormatServiceGateway_ServiceRefusedBackup(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ServiceGateway_ServiceRefusedBackup, arg0);

    /// <summary>
    /// A service is running and holds the writer role, so this backup would be run by the service — but a service can only run a configured backup set, not an ad-hoc directory. Pass --set &lt;name&gt;, or stop the service and re-run with --direct.
    /// </summary>
    internal static string ServiceGateway_ServiceRunningHoldsWriterRole => Get(nameof(ServiceGateway_ServiceRunningHoldsWriterRole));

    /// <summary>
    /// The service stopped reporting the job: {0}
    /// </summary>
    private static string ServiceGateway_ServiceStoppedReportingJob => Get(nameof(ServiceGateway_ServiceStoppedReportingJob));

    /// <summary>
    /// The service stopped reporting the job: {0}
    /// </summary>
    internal static string FormatServiceGateway_ServiceStoppedReportingJob(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ServiceGateway_ServiceStoppedReportingJob, arg0);
}
