// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Storage.AzureBlob.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Storage.AzureBlob.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Storage.AzureBlob.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// An account key is the base64 text the storage account issued, with no spaces in it; what was given is not one.
    /// </summary>
    internal static string AzureBlobCredentials_AccountKeyMalformed => Get(nameof(AzureBlobCredentials_AccountKeyMalformed));

    /// <summary>
    /// A shared access signature is the query text the account issued, such as sv=…&amp;sp=…&amp;sig=…, at most {0} characters with no spaces and no address before it; what was given is not one.
    /// </summary>
    private static string AzureBlobCredentials_SignatureNotAToken => Get(nameof(AzureBlobCredentials_SignatureNotAToken));

    /// <summary>
    /// A shared access signature is the query text the account issued, such as sv=…&amp;sp=…&amp;sig=…, at most {0} characters with no spaces and no address before it; what was given is not one.
    /// </summary>
    internal static string FormatAzureBlobCredentials_SignatureNotAToken(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobCredentials_SignatureNotAToken, arg0);

    /// <summary>
    /// A shared access signature carries '{0}', and this one does not: give the whole token the account issued, from sv= to the end of sig=.
    /// </summary>
    private static string AzureBlobCredentials_SignatureLacksField => Get(nameof(AzureBlobCredentials_SignatureLacksField));

    /// <summary>
    /// A shared access signature carries '{0}', and this one does not: give the whole token the account issued, from sv= to the end of sig=.
    /// </summary>
    internal static string FormatAzureBlobCredentials_SignatureLacksField(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobCredentials_SignatureLacksField, arg0);

    /// <summary>
    /// The shared access signature's expiry '{0}' is not a time.
    /// </summary>
    private static string AzureBlobCredentials_SignatureExpiryUnreadable => Get(nameof(AzureBlobCredentials_SignatureExpiryUnreadable));

    /// <summary>
    /// The shared access signature's expiry '{0}' is not a time.
    /// </summary>
    internal static string FormatAzureBlobCredentials_SignatureExpiryUnreadable(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobCredentials_SignatureExpiryUnreadable, arg0);

    /// <summary>
    /// '{0}' is not a storage account name: 3 to 24 lowercase letters and digits.
    /// </summary>
    private static string AzureBlobLocation_AccountInvalid => Get(nameof(AzureBlobLocation_AccountInvalid));

    /// <summary>
    /// '{0}' is not a storage account name: 3 to 24 lowercase letters and digits.
    /// </summary>
    internal static string FormatAzureBlobLocation_AccountInvalid(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobLocation_AccountInvalid, arg0);

    /// <summary>
    /// '{0}' is not a container name: 3 to 63 lowercase letters, digits and hyphens, starting with a letter or a digit, with no two hyphens together and none at the end.
    /// </summary>
    private static string AzureBlobLocation_ContainerInvalid => Get(nameof(AzureBlobLocation_ContainerInvalid));

    /// <summary>
    /// '{0}' is not a container name: 3 to 63 lowercase letters, digits and hyphens, starting with a letter or a digit, with no two hyphens together and none at the end.
    /// </summary>
    internal static string FormatAzureBlobLocation_ContainerInvalid(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobLocation_ContainerInvalid, arg0);

    /// <summary>
    /// '{0}' is not a prefix: folders of lowercase letters, digits, dots, underscores and hyphens, separated by '/', none starting with a dot.
    /// </summary>
    private static string AzureBlobLocation_PrefixInvalid => Get(nameof(AzureBlobLocation_PrefixInvalid));

    /// <summary>
    /// '{0}' is not a prefix: folders of lowercase letters, digits, dots, underscores and hyphens, separated by '/', none starting with a dot.
    /// </summary>
    internal static string FormatAzureBlobLocation_PrefixInvalid(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobLocation_PrefixInvalid, arg0);

    /// <summary>
    /// The endpoint '{0}' is not the account's blob endpoint: give a scheme, a host and, where it is not the scheme's own, a port, and at most the account's name as its path — for example https://{1}.objects.example.net, or http://127.0.0.1:10000/{1} for a store on this machine.
    /// </summary>
    private static string AzureBlobLocation_EndpointNotTheAccounts => Get(nameof(AzureBlobLocation_EndpointNotTheAccounts));

    /// <summary>
    /// The endpoint '{0}' is not the account's blob endpoint: give a scheme, a host and, where it is not the scheme's own, a port, and at most the account's name as its path — for example https://{1}.objects.example.net, or http://127.0.0.1:10000/{1} for a store on this machine.
    /// </summary>
    internal static string FormatAzureBlobLocation_EndpointNotTheAccounts(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobLocation_EndpointNotTheAccounts, arg0, arg1);

    /// <summary>
    /// The endpoint '{0}' is not https. Only a store on this machine is spoken to in clear: anything further away is reached through whoever is in between.
    /// </summary>
    private static string AzureBlobLocation_EndpointInClear => Get(nameof(AzureBlobLocation_EndpointInClear));

    /// <summary>
    /// The endpoint '{0}' is not https. Only a store on this machine is spoken to in clear: anything further away is reached through whoever is in between.
    /// </summary>
    internal static string FormatAzureBlobLocation_EndpointInClear(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobLocation_EndpointInClear, arg0);

    /// <summary>
    /// '{0}' is {1} bytes; one request to an Azure Blob container carries at most {2}.
    /// </summary>
    private static string AzureBlobObjectStore_ObjectTooLarge => Get(nameof(AzureBlobObjectStore_ObjectTooLarge));

    /// <summary>
    /// '{0}' is {1} bytes; one request to an Azure Blob container carries at most {2}.
    /// </summary>
    internal static string FormatAzureBlobObjectStore_ObjectTooLarge(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobObjectStore_ObjectTooLarge, arg0, arg1, arg2);

    /// <summary>
    /// The Azure Blob store answered a listing that cannot be read ({0}).
    /// </summary>
    private static string AzureBlobObjectStore_ListingUnreadable => Get(nameof(AzureBlobObjectStore_ListingUnreadable));

    /// <summary>
    /// The Azure Blob store answered a listing that cannot be read ({0}).
    /// </summary>
    internal static string FormatAzureBlobObjectStore_ListingUnreadable(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobObjectStore_ListingUnreadable, arg0);

    /// <summary>
    /// The Azure Blob store could not be reached for a {0} after {1} attempt(s): {2}
    /// </summary>
    private static string AzureBlobObjectStore_Unreachable => Get(nameof(AzureBlobObjectStore_Unreachable));

    /// <summary>
    /// The Azure Blob store could not be reached for a {0} after {1} attempt(s): {2}
    /// </summary>
    internal static string FormatAzureBlobObjectStore_Unreachable(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobObjectStore_Unreachable, arg0, arg1, arg2);

    /// <summary>
    /// The Azure Blob store refused a {0} of '{1}': {2} {3}. {4}
    /// </summary>
    private static string AzureBlobObjectStore_Refused => Get(nameof(AzureBlobObjectStore_Refused));

    /// <summary>
    /// The Azure Blob store refused a {0} of '{1}': {2} {3}. {4}
    /// </summary>
    internal static string FormatAzureBlobObjectStore_Refused(object? arg0, object? arg1, object? arg2, object? arg3, object? arg4) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobObjectStore_Refused, arg0, arg1, arg2, arg3, arg4);

    /// <summary>
    /// The Azure Blob store's answer ended before the blob it was sending did.
    /// </summary>
    internal static string AzureBlobObjectStore_BodyEndedEarly => Get(nameof(AzureBlobObjectStore_BodyEndedEarly));

    /// <summary>
    /// The shared access signature for this container expired at {0} UTC, so nothing was asked of the store under it: store a new one.
    /// </summary>
    private static string AzureBlobObjectStore_SignatureExpired => Get(nameof(AzureBlobObjectStore_SignatureExpired));

    /// <summary>
    /// The shared access signature for this container expired at {0} UTC, so nothing was asked of the store under it: store a new one.
    /// </summary>
    internal static string FormatAzureBlobObjectStore_SignatureExpired(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, AzureBlobObjectStore_SignatureExpired, arg0);
}
