// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Web.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Web.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Web.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// The server started but reported no bound address.
    /// </summary>
    internal static string RunningConsole_NoBoundAddress => Get(nameof(RunningConsole_NoBoundAddress));

    /// <summary>
    /// The embedded asset '{0}' is missing from this build.
    /// </summary>
    private static string WebConsoleHost_EmbeddedAssetMissing => Get(nameof(WebConsoleHost_EmbeddedAssetMissing));

    /// <summary>
    /// The embedded asset '{0}' is missing from this build.
    /// </summary>
    internal static string FormatWebConsoleHost_EmbeddedAssetMissing(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, WebConsoleHost_EmbeddedAssetMissing, arg0);

    /// <summary>
    /// This console answers loopback requests only. The request named a different host, which is what a DNS-rebinding page does — it was refused.
    /// </summary>
    internal static string WebConsoleHost_HostNotLoopback => Get(nameof(WebConsoleHost_HostNotLoopback));

    /// <summary>
    /// The request body was not a command this contract knows: {0}
    /// </summary>
    private static string WebConsoleHost_MalformedCommand => Get(nameof(WebConsoleHost_MalformedCommand));

    /// <summary>
    /// The request body was not a command this contract knows: {0}
    /// </summary>
    internal static string FormatWebConsoleHost_MalformedCommand(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, WebConsoleHost_MalformedCommand, arg0);

    /// <summary>
    /// service none listening for '{0}' yet — the console keeps trying, and the page shows the service as unreachable until one answers
    /// </summary>
    private static string WebConsoleHost_NoServiceListening => Get(nameof(WebConsoleHost_NoServiceListening));

    /// <summary>
    /// service none listening for '{0}' yet — the console keeps trying, and the page shows the service as unreachable until one answers
    /// </summary>
    internal static string FormatWebConsoleHost_NoServiceListening(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, WebConsoleHost_NoServiceListening, arg0);

    /// <summary>
    /// service answered, but not with a service description — versions may be far apart
    /// </summary>
    internal static string WebConsoleHost_ServiceAnsweredUnexpectedly => Get(nameof(WebConsoleHost_ServiceAnsweredUnexpectedly));

    /// <summary>
    /// service reachable — {0}, contract {1}
    /// </summary>
    private static string WebConsoleHost_ServiceReachable => Get(nameof(WebConsoleHost_ServiceReachable));

    /// <summary>
    /// service reachable — {0}, contract {1}
    /// </summary>
    internal static string FormatWebConsoleHost_ServiceReachable(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, WebConsoleHost_ServiceReachable, arg0, arg1);

    /// <summary>
    /// The request did not present this run's access token. Open the console through the URL printed at start — the token in it is this run's key.
    /// </summary>
    internal static string WebConsoleHost_TokenMissingOrWrong => Get(nameof(WebConsoleHost_TokenMissingOrWrong));

    /// <summary>
    /// The flag '{0}' needs a value.
    /// </summary>
    private static string WebConsoleOptions_FlagNeedsValue => Get(nameof(WebConsoleOptions_FlagNeedsValue));

    /// <summary>
    /// The flag '{0}' needs a value.
    /// </summary>
    internal static string FormatWebConsoleOptions_FlagNeedsValue(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, WebConsoleOptions_FlagNeedsValue, arg0);

    /// <summary>
    /// The port '{0}' is not a number between 0 and 65535.
    /// </summary>
    private static string WebConsoleOptions_PortInvalid => Get(nameof(WebConsoleOptions_PortInvalid));

    /// <summary>
    /// The port '{0}' is not a number between 0 and 65535.
    /// </summary>
    internal static string FormatWebConsoleOptions_PortInvalid(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, WebConsoleOptions_PortInvalid, arg0);

    /// <summary>
    /// The state directory '{0}' does not exist. It is created by the service, not the console — start the service first, or check the path.
    /// </summary>
    private static string WebConsoleOptions_StateDirectoryMissing => Get(nameof(WebConsoleOptions_StateDirectoryMissing));

    /// <summary>
    /// The state directory '{0}' does not exist. It is created by the service, not the console — start the service first, or check the path.
    /// </summary>
    internal static string FormatWebConsoleOptions_StateDirectoryMissing(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, WebConsoleOptions_StateDirectoryMissing, arg0);

    /// <summary>
    /// Pass --state &lt;dir&gt; — the state directory whose service this console talks to.
    /// </summary>
    internal static string WebConsoleOptions_StateDirectoryRequired => Get(nameof(WebConsoleOptions_StateDirectoryRequired));

    /// <summary>
    /// Unknown argument '{0}'. Pass --help for usage.
    /// </summary>
    private static string WebConsoleOptions_UnknownArgument => Get(nameof(WebConsoleOptions_UnknownArgument));

    /// <summary>
    /// Unknown argument '{0}'. Pass --help for usage.
    /// </summary>
    internal static string FormatWebConsoleOptions_UnknownArgument(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, WebConsoleOptions_UnknownArgument, arg0);
}
