// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Repository.Packing.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Repository.Packing.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Repository.Packing.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// Blob class 0x{0:x4} is not defined (specification 05 §2).
    /// </summary>
    private static string BlobEnvelope_BlobClassXNotDefined => Get(nameof(BlobEnvelope_BlobClassXNotDefined));

    /// <summary>
    /// Blob class 0x{0:x4} is not defined (specification 05 §2).
    /// </summary>
    internal static string FormatBlobEnvelope_BlobClassXNotDefined(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobEnvelope_BlobClassXNotDefined, arg0);

    /// <summary>
    /// A blob envelope is {0} bytes; got {1}.
    /// </summary>
    private static string BlobEnvelope_BlobEnvelopeBytesGot => Get(nameof(BlobEnvelope_BlobEnvelopeBytesGot));

    /// <summary>
    /// A blob envelope is {0} bytes; got {1}.
    /// </summary>
    internal static string FormatBlobEnvelope_BlobEnvelopeBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobEnvelope_BlobEnvelopeBytesGot, arg0, arg1);

    /// <summary>
    /// A blob envelope is exactly {0} bytes; got {1}.
    /// </summary>
    private static string BlobEnvelope_BlobEnvelopeExactlyBytesGot => Get(nameof(BlobEnvelope_BlobEnvelopeExactlyBytesGot));

    /// <summary>
    /// A blob envelope is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatBlobEnvelope_BlobEnvelopeExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobEnvelope_BlobEnvelopeExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// The blob salt is exactly 32 bytes (specification 05 §2).
    /// </summary>
    internal static string BlobEnvelope_BlobSaltExactlyBytes => Get(nameof(BlobEnvelope_BlobSaltExactlyBytes));

    /// <summary>
    /// Not a FallbackPlan blob: the FBPKBLOB magic is absent.
    /// </summary>
    internal static string BlobEnvelope_NotFallbackPlanBlobFBPKBLOBMagic => Get(nameof(BlobEnvelope_NotFallbackPlanBlobFBPKBLOBMagic));

    /// <summary>
    /// The FBPKFOOT magic is absent — the locator points at something that is not a footer.
    /// </summary>
    internal static string BlobFooter_FBPKFOOTMagicAbsent => Get(nameof(BlobFooter_FBPKFOOTMagicAbsent));

    /// <summary>
    /// The footer declares a {0}-byte record table; the limit is {1} (specification 00 §8) — refused before allocation.
    /// </summary>
    private static string BlobFooter_FooterDeclaresByteRecordTable => Get(nameof(BlobFooter_FooterDeclaresByteRecordTable));

    /// <summary>
    /// The footer declares a {0}-byte record table; the limit is {1} (specification 00 §8) — refused before allocation.
    /// </summary>
    internal static string FormatBlobFooter_FooterDeclaresByteRecordTable(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobFooter_FooterDeclaresByteRecordTable, arg0, arg1);

    /// <summary>
    /// The footer declares {0} records; the limit is {1} (specification 00 §8).
    /// </summary>
    private static string BlobFooter_FooterDeclaresRecordsLimit => Get(nameof(BlobFooter_FooterDeclaresRecordsLimit));

    /// <summary>
    /// The footer declares {0} records; the limit is {1} (specification 00 §8).
    /// </summary>
    internal static string FormatBlobFooter_FooterDeclaresRecordsLimit(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobFooter_FooterDeclaresRecordsLimit, arg0, arg1);

    /// <summary>
    /// A footer header is {0} bytes; got {1}.
    /// </summary>
    private static string BlobFooter_FooterHeaderBytesGot => Get(nameof(BlobFooter_FooterHeaderBytesGot));

    /// <summary>
    /// A footer header is {0} bytes; got {1}.
    /// </summary>
    internal static string FormatBlobFooter_FooterHeaderBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobFooter_FooterHeaderBytesGot, arg0, arg1);

    /// <summary>
    /// The footer header is exactly {0} bytes.
    /// </summary>
    private static string BlobFooter_FooterHeaderExactlyBytes => Get(nameof(BlobFooter_FooterHeaderExactlyBytes));

    /// <summary>
    /// The footer header is exactly {0} bytes.
    /// </summary>
    internal static string FormatBlobFooter_FooterHeaderExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobFooter_FooterHeaderExactlyBytes, arg0);

    /// <summary>
    /// Record-table entry {0} carries an unassigned profile or object type; refused, not guessed (specification 00 §3).
    /// </summary>
    private static string BlobFooter_RecordTableEntryCarriesUnassigned => Get(nameof(BlobFooter_RecordTableEntryCarriesUnassigned));

    /// <summary>
    /// Record-table entry {0} carries an unassigned profile or object type; refused, not guessed (specification 00 §3).
    /// </summary>
    internal static string FormatBlobFooter_RecordTableEntryCarriesUnassigned(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobFooter_RecordTableEntryCarriesUnassigned, arg0);

    /// <summary>
    /// Record-table entry {0} extends to byte {1}, past the {2}-byte blob — a damage finding (specification 05 §3.1).
    /// </summary>
    private static string BlobFooter_RecordTableEntryExtendsByte => Get(nameof(BlobFooter_RecordTableEntryExtendsByte));

    /// <summary>
    /// Record-table entry {0} extends to byte {1}, past the {2}-byte blob — a damage finding (specification 05 §3.1).
    /// </summary>
    internal static string FormatBlobFooter_RecordTableEntryExtendsByte(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, BlobFooter_RecordTableEntryExtendsByte, arg0, arg1, arg2);

    /// <summary>
    /// A record-table entry has 8 fields; entry {0} has {1}.
    /// </summary>
    private static string BlobFooter_RecordTableEntryFieldsEntry => Get(nameof(BlobFooter_RecordTableEntryFieldsEntry));

    /// <summary>
    /// A record-table entry has 8 fields; entry {0} has {1}.
    /// </summary>
    internal static string FormatBlobFooter_RecordTableEntryFieldsEntry(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobFooter_RecordTableEntryFieldsEntry, arg0, arg1);

    /// <summary>
    /// Record-table entry {0} is missing a required field (specification 05 §3.1).
    /// </summary>
    private static string BlobFooter_RecordTableEntryMissingRequired => Get(nameof(BlobFooter_RecordTableEntryMissingRequired));

    /// <summary>
    /// Record-table entry {0} is missing a required field (specification 05 §3.1).
    /// </summary>
    internal static string FormatBlobFooter_RecordTableEntryMissingRequired(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobFooter_RecordTableEntryMissingRequired, arg0);

    /// <summary>
    /// The record table holds {0} entries; the footer declares {1} — a damage finding (specification 05 §3.1).
    /// </summary>
    private static string BlobFooter_RecordTableHoldsEntriesFooter => Get(nameof(BlobFooter_RecordTableHoldsEntriesFooter));

    /// <summary>
    /// The record table holds {0} entries; the footer declares {1} — a damage finding (specification 05 §3.1).
    /// </summary>
    internal static string FormatBlobFooter_RecordTableHoldsEntriesFooter(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobFooter_RecordTableHoldsEntriesFooter, arg0, arg1);

    /// <summary>
    /// Record-table offsets must strictly increase without overlap; entry {0} at {1} overlaps the previous record (specification 05 §3.1).
    /// </summary>
    private static string BlobFooter_RecordTableOffsetsMustStrictly => Get(nameof(BlobFooter_RecordTableOffsetsMustStrictly));

    /// <summary>
    /// Record-table offsets must strictly increase without overlap; entry {0} at {1} overlaps the previous record (specification 05 §3.1).
    /// </summary>
    internal static string FormatBlobFooter_RecordTableOffsetsMustStrictly(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobFooter_RecordTableOffsetsMustStrictly, arg0, arg1);

    /// <summary>
    /// Record-table ordinals must ascend from zero; entry {0} carries ordinal {1} (specification 05 §3.1).
    /// </summary>
    private static string BlobFooter_RecordTableOrdinalsMustAscend => Get(nameof(BlobFooter_RecordTableOrdinalsMustAscend));

    /// <summary>
    /// Record-table ordinals must ascend from zero; entry {0} carries ordinal {1} (specification 05 §3.1).
    /// </summary>
    internal static string FormatBlobFooter_RecordTableOrdinalsMustAscend(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobFooter_RecordTableOrdinalsMustAscend, arg0, arg1);

    /// <summary>
    /// A {0}-byte object is too short to be a sealed blob (specification 05 §1).
    /// </summary>
    private static string BlobReader_ByteObjectTooShortSealed => Get(nameof(BlobReader_ByteObjectTooShortSealed));

    /// <summary>
    /// A {0}-byte object is too short to be a sealed blob (specification 05 §1).
    /// </summary>
    internal static string FormatBlobReader_ByteObjectTooShortSealed(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobReader_ByteObjectTooShortSealed, arg0);

    /// <summary>
    /// The footer's declared table length does not reach the locator exactly — data beyond the sealed layout is a damage finding (specification 05 §5).
    /// </summary>
    internal static string BlobReader_FooterSDeclaredTableLength => Get(nameof(BlobReader_FooterSDeclaredTableLength));

    /// <summary>
    /// Range [{0}, {1}) of blob object '{2}' could not be read: {3}.
    /// </summary>
    private static string BlobReader_RangeBlobObjectCouldNot => Get(nameof(BlobReader_RangeBlobObjectCouldNot));

    /// <summary>
    /// Range [{0}, {1}) of blob object '{2}' could not be read: {3}.
    /// </summary>
    internal static string FormatBlobReader_RangeBlobObjectCouldNot(object? arg0, object? arg1, object? arg2, object? arg3) =>
        string.Format(CultureInfo.CurrentCulture, BlobReader_RangeBlobObjectCouldNot, arg0, arg1, arg2, arg3);

    /// <summary>
    /// Range read of '{0}' ended {1} bytes early.
    /// </summary>
    private static string BlobReader_RangeReadEndedBytesEarly => Get(nameof(BlobReader_RangeReadEndedBytesEarly));

    /// <summary>
    /// Range read of '{0}' ended {1} bytes early.
    /// </summary>
    internal static string FormatBlobReader_RangeReadEndedBytesEarly(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobReader_RangeReadEndedBytesEarly, arg0, arg1);

    /// <summary>
    /// The recovery footer failed authentication — the blob is damaged or does not belong to this repository (specification 05 §3).
    /// </summary>
    internal static string BlobReader_RecoveryFooterFailedAuthentication => Get(nameof(BlobReader_RecoveryFooterFailedAuthentication));

    /// <summary>
    /// A blob salt is exactly {0} bytes.
    /// </summary>
    private static string BlobWriter_BlobSaltExactlyBytes => Get(nameof(BlobWriter_BlobSaltExactlyBytes));

    /// <summary>
    /// A blob salt is exactly {0} bytes.
    /// </summary>
    internal static string FormatBlobWriter_BlobSaltExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobWriter_BlobSaltExactlyBytes, arg0);

    /// <summary>
    /// Format version 1 admits one record AEAD, aes-256-gcm-v1 (specification 03 §6); any other profile is refused, not guessed.
    /// </summary>
    internal static string BlobWriter_FormatVersionAdmitsOneRecord => Get(nameof(BlobWriter_FormatVersionAdmitsOneRecord));

    /// <summary>
    /// The record does not fit this blob; seal and start a new one — records are never split (specification 04 §8).
    /// </summary>
    internal static string BlobWriter_RecordDoesNotFitBlob => Get(nameof(BlobWriter_RecordDoesNotFitBlob));

    /// <summary>
    /// The identifier is exactly 16 bytes.
    /// </summary>
    internal static string MetadataStoreKeys_IdentifierExactlyBytes => Get(nameof(MetadataStoreKeys_IdentifierExactlyBytes));

    /// <summary>
    /// A standalone record's payload is never empty (specification 04 §2.1).
    /// </summary>
    internal static string StandaloneRecordCipher_StandaloneRecordSPayloadNever => Get(nameof(StandaloneRecordCipher_StandaloneRecordSPayloadNever));

    /// <summary>
    /// A footer locator is {0} bytes; got {1}.
    /// </summary>
    private static string struct_FooterLocatorBytesGot => Get(nameof(struct_FooterLocatorBytesGot));

    /// <summary>
    /// A footer locator is {0} bytes; got {1}.
    /// </summary>
    internal static string Formatstruct_FooterLocatorBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, struct_FooterLocatorBytesGot, arg0, arg1);

    /// <summary>
    /// A footer locator is exactly {0} bytes; got {1}.
    /// </summary>
    private static string struct_FooterLocatorExactlyBytesGot => Get(nameof(struct_FooterLocatorExactlyBytesGot));

    /// <summary>
    /// A footer locator is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string Formatstruct_FooterLocatorExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, struct_FooterLocatorExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// Footer offset {0} does not fall inside a {1}-byte blob — the locator is damaged (specification 05 §4).
    /// </summary>
    private static string struct_FooterOffsetDoesNotFall => Get(nameof(struct_FooterOffsetDoesNotFall));

    /// <summary>
    /// Footer offset {0} does not fall inside a {1}-byte blob — the locator is damaged (specification 05 §4).
    /// </summary>
    internal static string Formatstruct_FooterOffsetDoesNotFall(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, struct_FooterOffsetDoesNotFall, arg0, arg1);

    /// <summary>
    /// A v2 data blob's envelope carries exactly one 80-byte sealed content key; every other envelope carries none (ADR-0042).
    /// </summary>
    internal static string BlobEnvelope_SealedShareDisagrees => Get(nameof(BlobEnvelope_SealedShareDisagrees));

    /// <summary>
    /// This record's content key is sealed to the repository's public key — reading it requires a restore grant (ADR-0042).
    /// </summary>
    internal static string BlobReader_ContentKeySealed => Get(nameof(BlobReader_ContentKeySealed));

    /// <summary>
    /// A sealed data blob's envelope is at least {0} bytes; got {1}.
    /// </summary>
    private static string BlobEnvelope_SealedEnvelopeBytesGot => Get(nameof(BlobEnvelope_SealedEnvelopeBytesGot));

    /// <summary>
    /// A sealed data blob's envelope is at least {0} bytes; got {1}.
    /// </summary>
    internal static string FormatBlobEnvelope_SealedEnvelopeBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, BlobEnvelope_SealedEnvelopeBytesGot, arg0, arg1);

    /// <summary>
    /// The sealed-share associated data is exactly {0} bytes.
    /// </summary>
    private static string SealedContentKey_AadExactlyBytes => Get(nameof(SealedContentKey_AadExactlyBytes));

    /// <summary>
    /// The sealed-share associated data is exactly {0} bytes.
    /// </summary>
    internal static string FormatSealedContentKey_AadExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, SealedContentKey_AadExactlyBytes, arg0);
}
