// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Storage.Abstractions.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Storage.Abstractions.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Storage.Abstractions.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// '{0}' is not a valid object key.
    /// </summary>
    private static string ObjectKey_NotValidObjectKey => Get(nameof(ObjectKey_NotValidObjectKey));

    /// <summary>
    /// '{0}' is not a valid object key.
    /// </summary>
    internal static string FormatObjectKey_NotValidObjectKey(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ObjectKey_NotValidObjectKey, arg0);

    /// <summary>
    /// '{0}' cannot prefix any valid object key.
    /// </summary>
    private static string ObjectPrefix_CannotPrefixAnyValidObject => Get(nameof(ObjectPrefix_CannotPrefixAnyValidObject));

    /// <summary>
    /// '{0}' cannot prefix any valid object key.
    /// </summary>
    internal static string FormatObjectPrefix_CannotPrefixAnyValidObject(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ObjectPrefix_CannotPrefixAnyValidObject, arg0);
}
