using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Xunit;

namespace FallbackPlan.Repository.ConformanceTests;

/// <summary>
/// Verifies the committed conformance vectors against .NET's in-box cryptographic
/// primitives.
///
/// Two things this earns:
///
/// 1. It cross-validates the vectors. They were generated by a Python script using
///    only hashlib and hmac; these tests recompute them with an entirely separate
///    implementation. Agreement means the vectors describe the algorithms rather
///    than one library's quirks.
///
/// 2. It is the adoption gate for any candidate cryptography library. Specification
///    03 section 1 requires audited platform primitives and forbids writing our own.
///    A library proposed for the format-critical path must reproduce every value
///    below bit-for-bit; if it does not, it is not a drop-in and the answer is no.
///    That makes the decision testable rather than a matter of opinion.
///
/// See specifications/repository-format/conformance/README.md.
/// </summary>
public sealed class CryptographicPrimitiveTests
{
    private const int OrdinalSegment = 0x01;
    private const int OrdinalBlobKey = 0x07;

    private static readonly byte[] MasterKey = Enumerable.Range(0, 32).Select(i => (byte)i).ToArray();

    private static JsonDocument Load(string name) =>
        JsonDocument.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "vectors", name)));

    private static byte[] Hex(string value) => Convert.FromHexString(value);

    private static string Hex(byte[] value) => Convert.ToHexString(value).ToLowerInvariant();

    /// <summary>HKDF-Expand per RFC 5869 section 2.3, using the in-box implementation.</summary>
    private static byte[] Expand(byte[] prk, byte[] info, int length) =>
        HKDF.Expand(HashAlgorithmName.SHA256, prk, length, info);

    private static byte[] Info(string label, params byte[][] parts)
    {
        var buffer = new List<byte>(Encoding.ASCII.GetBytes(label));
        foreach (var part in parts)
        {
            buffer.AddRange(part);
        }

        return [.. buffer];
    }

    private static byte[] BigEndian(uint value) =>
        [(byte)(value >> 24), (byte)(value >> 16), (byte)(value >> 8), (byte)value];

    private static byte[] BigEndian(ulong value)
    {
        var bytes = BitConverter.GetBytes(value);
        if (BitConverter.IsLittleEndian)
        {
            Array.Reverse(bytes);
        }

        return bytes;
    }

    // ---------------------------------------------------------------------
    // Independent validation of the generator itself
    // ---------------------------------------------------------------------

    /// <summary>
    /// RFC 5869 test case 1. The vector generator runs this same check on every
    /// invocation; running it here too means a divergence between .NET's HKDF and
    /// the generator's would be caught rather than silently accepted.
    /// </summary>
    [Fact]
    public void Hkdf_expand_matches_rfc_5869_test_case_1()
    {
        var prk = Hex("077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5");
        var info = Hex("f0f1f2f3f4f5f6f7f8f9");

        Assert.Equal(
            "3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865",
            Hex(Expand(prk, info, 42)));
    }

    // ---------------------------------------------------------------------
    // Key derivation (specification 03)
    // ---------------------------------------------------------------------

    [Fact]
    public void Derived_keys_match_the_committed_vectors()
    {
        using var document = Load("keys.json");
        var derived = document.RootElement.GetProperty("derived");

        Assert.Equal(
            derived.GetProperty("content_id_key").GetString(),
            Hex(Expand(MasterKey, Encoding.ASCII.GetBytes("fbp/content-id/v1"), 32)));

        Assert.Equal(
            derived.GetProperty("key_id_key").GetString(),
            Hex(Expand(MasterKey, Encoding.ASCII.GetBytes("fbp/key-id/v1"), 32)));

        Assert.Equal(
            derived.GetProperty("data_key_generation_0").GetString(),
            Hex(Expand(MasterKey, Info("fbp/data/v1", BigEndian(0u)), 32)));

        Assert.Equal(
            derived.GetProperty("data_key_generation_1").GetString(),
            Hex(Expand(MasterKey, Info("fbp/data/v1", BigEndian(1u)), 32)));

        Assert.Equal(
            derived.GetProperty("metadata_key_generation_0").GetString(),
            Hex(Expand(MasterKey, Info("fbp/metadata/v1", BigEndian(0u)), 32)));

        Assert.Equal(
            derived.GetProperty("signing_key_generation_0").GetString(),
            Hex(Expand(MasterKey, Info("fbp/signing/v1", BigEndian(0u)), 32)));
    }

    /// <summary>
    /// The per-blob key derivation from specification 03 section 5 — the construction
    /// the format's confidentiality rests on.
    /// </summary>
    [Fact]
    public void Blob_key_derivation_matches_the_committed_vector()
    {
        using var document = Load("keys.json");
        var inputs = document.RootElement.GetProperty("inputs");

        var salt = Hex(inputs.GetProperty("blob_salt").GetString()!);
        var writerId = Hex(inputs.GetProperty("writer_id").GetString()!);
        var counter = inputs.GetProperty("blob_counter").GetUInt64();

        var dataKey = Expand(MasterKey, Info("fbp/data/v1", BigEndian(0u)), 32);
        var blobKey = Expand(dataKey, Info("fbp/blob/v1", salt, writerId, BigEndian(counter)), 32);

        Assert.Equal(
            document.RootElement.GetProperty("derived").GetProperty("blob_key").GetString(),
            Hex(blobKey));
    }

    /// <summary>
    /// Key separation must survive a cloned VM replaying CSPRNG state: the same
    /// blob_salt with a different writer or counter must yield a different key.
    /// This is the property PT-13 added, and it is worth testing rather than
    /// assuming, because it is invisible until it fails catastrophically.
    /// </summary>
    [Fact]
    public void Identical_salt_with_a_different_writer_or_counter_yields_a_different_key()
    {
        using var document = Load("keys.json");
        var inputs = document.RootElement.GetProperty("inputs");
        var checks = document.RootElement.GetProperty("separation_checks");

        var salt = Hex(inputs.GetProperty("blob_salt").GetString()!);
        var writerId = Hex(inputs.GetProperty("writer_id").GetString()!);
        var counter = inputs.GetProperty("blob_counter").GetUInt64();
        var dataKey = Expand(MasterKey, Info("fbp/data/v1", BigEndian(0u)), 32);

        var baseline = Expand(dataKey, Info("fbp/blob/v1", salt, writerId, BigEndian(counter)), 32);
        var otherWriter = Expand(dataKey, Info("fbp/blob/v1", salt, Enumerable.Repeat((byte)0xB0, 16).ToArray(), BigEndian(counter)), 32);
        var otherCounter = Expand(dataKey, Info("fbp/blob/v1", salt, writerId, BigEndian(counter + 1)), 32);

        Assert.Equal(checks.GetProperty("blob_key_other_writer").GetString(), Hex(otherWriter));
        Assert.Equal(checks.GetProperty("blob_key_other_counter").GetString(), Hex(otherCounter));

        Assert.NotEqual(Hex(baseline), Hex(otherWriter));
        Assert.NotEqual(Hex(baseline), Hex(otherCounter));
    }

    // ---------------------------------------------------------------------
    // Identifiers (specification 02)
    // ---------------------------------------------------------------------

    [Fact]
    public void Content_identifiers_match_the_committed_vectors()
    {
        using var document = Load("identifiers.json");

        foreach (var testCase in document.RootElement.GetProperty("cases").EnumerateArray())
        {
            var name = testCase.GetProperty("name").GetString();
            var plaintext = PlaintextFor(name!, testCase.GetProperty("plaintext_length").GetInt32());

            Assert.Equal(
                testCase.GetProperty("content_id").GetString(),
                Hex(SHA256.HashData(plaintext)));
        }
    }

    [Fact]
    public void Object_identifiers_match_the_committed_vectors()
    {
        using var document = Load("identifiers.json");
        var contentIdKey = Expand(MasterKey, Encoding.ASCII.GetBytes("fbp/content-id/v1"), 32);

        foreach (var testCase in document.RootElement.GetProperty("cases").EnumerateArray())
        {
            var name = testCase.GetProperty("name").GetString();
            var plaintext = PlaintextFor(name!, testCase.GetProperty("plaintext_length").GetInt32());
            var contentId = SHA256.HashData(plaintext);

            var message = new byte[1 + contentId.Length];
            message[0] = OrdinalSegment;
            contentId.CopyTo(message, 1);

            Assert.Equal(
                testCase.GetProperty("object_id_segment").GetString(),
                Hex(HMACSHA256.HashData(contentIdKey, message)));
        }
    }

    [Fact]
    public void Store_blob_key_derivation_matches_the_committed_vector()
    {
        using var document = Load("identifiers.json");
        var blob = document.RootElement.GetProperty("blob_identifier");
        var keyIdKey = Expand(MasterKey, Encoding.ASCII.GetBytes("fbp/key-id/v1"), 32);

        var blobId = Hex(blob.GetProperty("blob_id").GetString()!);
        var message = new byte[1 + blobId.Length];
        message[0] = OrdinalBlobKey;
        blobId.CopyTo(message, 1);

        Assert.Equal(
            blob.GetProperty("store_blob_key").GetString(),
            Hex(HMACSHA256.HashData(keyIdKey, message)[..16]));
    }

    // ---------------------------------------------------------------------
    // Associated data (specification 04 section 4)
    // ---------------------------------------------------------------------

    [Fact]
    public void Associated_data_matches_the_committed_vectors()
    {
        using var document = Load("records.json");
        var inputs = document.RootElement.GetProperty("inputs");

        var repositoryId = Hex(inputs.GetProperty("repository_id").GetString()!);
        var formatVersion = (ushort)inputs.GetProperty("format_version").GetInt32();
        var objectType = (byte)inputs.GetProperty("object_type").GetInt32();
        var objectId = Hex(inputs.GetProperty("object_id").GetString()!);

        foreach (var testCase in document.RootElement.GetProperty("cases").EnumerateArray())
        {
            var ordinal = testCase.GetProperty("ordinal").GetUInt32();

            var aad = new List<byte>(55);
            aad.AddRange(repositoryId);
            aad.AddRange([(byte)(formatVersion >> 8), (byte)formatVersion]);
            aad.Add(objectType);
            aad.AddRange(objectId);
            aad.AddRange(BigEndian(ordinal));

            Assert.Equal(55, aad.Count);
            Assert.Equal(testCase.GetProperty("aad").GetString(), Hex([.. aad]));
        }
    }

    // ---------------------------------------------------------------------
    // NIST known-answer tests — independent of both our implementations
    // ---------------------------------------------------------------------

    /// <summary>
    /// NIST CAVP AES-256-GCM vectors. These are the only AEAD vectors in the suite
    /// derived independently of anything we wrote, and they establish that the
    /// primitive is used correctly — nonce and tag handling included.
    /// </summary>
    [Fact]
    public void Aes_gcm_matches_known_answer_tests()
    {
        using var document = Load("aes-gcm.json");

        foreach (var testCase in document.RootElement.GetProperty("cases").EnumerateArray())
        {
            var key = Hex(testCase.GetProperty("key").GetString()!);
            var iv = Hex(testCase.GetProperty("iv").GetString()!);
            var plaintext = Hex(testCase.GetProperty("plaintext").GetString()!);
            var aad = Hex(testCase.GetProperty("aad").GetString()!);
            var expectedCipher = testCase.GetProperty("ciphertext").GetString();
            var expectedTag = testCase.GetProperty("tag").GetString();

            var ciphertext = new byte[plaintext.Length];
            var tag = new byte[16];

            using var aes = new AesGcm(key, tag.Length);
            aes.Encrypt(iv, plaintext, ciphertext, tag, aad);

            Assert.Equal(expectedCipher, Hex(ciphertext));
            Assert.Equal(expectedTag, Hex(tag));

            // And round-trips, which the vector file does not assert on its own.
            var recovered = new byte[plaintext.Length];
            aes.Decrypt(iv, ciphertext, tag, recovered, aad);
            Assert.Equal(Hex(plaintext), Hex(recovered));
        }
    }

    /// <summary>
    /// The AAD is authenticated, so altering it must cause decryption to fail.
    /// This is what makes relocating a record between ordinals, object types or
    /// repositories detectable (specification 04 section 4, threat T-3).
    /// </summary>
    [Fact]
    public void Altering_associated_data_causes_authentication_to_fail()
    {
        var key = RandomNumberGenerator.GetBytes(32);
        var nonce = new byte[12];
        var plaintext = Encoding.ASCII.GetBytes("segment payload");
        var aad = Encoding.ASCII.GetBytes("repository-a|ordinal-47");
        var tampered = Encoding.ASCII.GetBytes("repository-a|ordinal-48");

        var ciphertext = new byte[plaintext.Length];
        var tag = new byte[16];

        using var aes = new AesGcm(key, tag.Length);
        aes.Encrypt(nonce, plaintext, ciphertext, tag, aad);

        Assert.Throws<AuthenticationTagMismatchException>(() =>
            aes.Decrypt(nonce, ciphertext, tag, new byte[plaintext.Length], tampered));
    }

    // ---------------------------------------------------------------------

    /// <summary>Reproduces the generator's fixed plaintexts from the case name.</summary>
    private static byte[] PlaintextFor(string name, int expectedLength)
    {
        byte[] plaintext = name switch
        {
            "empty" => [],
            "single_byte" => [0x00],
            "ascii" => Encoding.ASCII.GetBytes("hello world"),
            "one_mib_cycle" => Enumerable.Range(0, 4096)
                .SelectMany(_ => Enumerable.Range(0, 256).Select(b => (byte)b))
                .ToArray(),
            "one_mib_zeros" => new byte[1024 * 1024],
            _ => throw new InvalidOperationException(
                string.Create(CultureInfo.InvariantCulture, $"Unknown vector case '{name}'.")),
        };

        Assert.Equal(expectedLength, plaintext.Length);
        return plaintext;
    }
}
