// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Recovery.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Recovery.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Recovery.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// Environment variable '{0}' is unset — the passphrase is passed by name, never on the command line.
    /// </summary>
    private static string RecoveryHost_EnvironmentVariableUnset => Get(nameof(RecoveryHost_EnvironmentVariableUnset));

    /// <summary>
    /// Environment variable '{0}' is unset — the passphrase is passed by name, never on the command line.
    /// </summary>
    internal static string FormatRecoveryHost_EnvironmentVariableUnset(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryHost_EnvironmentVariableUnset, arg0);

    /// <summary>
    /// Missing required option {0}.
    /// </summary>
    private static string RecoveryHost_MissingRequiredOption => Get(nameof(RecoveryHost_MissingRequiredOption));

    /// <summary>
    /// Missing required option {0}.
    /// </summary>
    internal static string FormatRecoveryHost_MissingRequiredOption(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryHost_MissingRequiredOption, arg0);

    /// <summary>
    /// No snapshot {0} is discoverable in this store.
    /// </summary>
    private static string RecoveryHost_NoSnapshotDiscoverableStore => Get(nameof(RecoveryHost_NoSnapshotDiscoverableStore));

    /// <summary>
    /// No snapshot {0} is discoverable in this store.
    /// </summary>
    internal static string FormatRecoveryHost_NoSnapshotDiscoverableStore(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryHost_NoSnapshotDiscoverableStore, arg0);

    /// <summary>
    /// Unknown command '{0}'. Run with --help.
    /// </summary>
    private static string RecoveryHost_UnknownCommandRunWithHelp => Get(nameof(RecoveryHost_UnknownCommandRunWithHelp));

    /// <summary>
    /// Unknown command '{0}'. Run with --help.
    /// </summary>
    internal static string FormatRecoveryHost_UnknownCommandRunWithHelp(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryHost_UnknownCommandRunWithHelp, arg0);

    /// <summary>
    /// The passphrase does not reproduce this repository's keys (ADR-0042): the derived public key disagrees with the kit's.
    /// </summary>
    internal static string RecoverySession_PassphraseDoesNotReproduce => Get(nameof(RecoverySession_PassphraseDoesNotReproduce));
}
