// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Application.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Application.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Application.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// Backup set '{0}': {1}
    /// </summary>
    private static string ClientConfiguration_BackupSet => Get(nameof(ClientConfiguration_BackupSet));

    /// <summary>
    /// Backup set '{0}': {1}
    /// </summary>
    internal static string FormatClientConfiguration_BackupSet(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSet, arg0, arg1);

    /// <summary>
    /// Backup set '{0}': id must be 32 hex digits.
    /// </summary>
    private static string ClientConfiguration_BackupSetIdMustHex => Get(nameof(ClientConfiguration_BackupSetIdMustHex));

    /// <summary>
    /// Backup set '{0}': id must be 32 hex digits.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetIdMustHex(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetIdMustHex, arg0);

    /// <summary>
    /// Backup set names must be non-empty and unique; '{0}' is not.
    /// </summary>
    private static string ClientConfiguration_BackupSetNamesMustNon => Get(nameof(ClientConfiguration_BackupSetNamesMustNon));

    /// <summary>
    /// Backup set names must be non-empty and unique; '{0}' is not.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetNamesMustNon(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetNamesMustNon, arg0);

    /// <summary>
    /// Backup set '{0}': root must not be empty.
    /// </summary>
    private static string ClientConfiguration_BackupSetRootMustNot => Get(nameof(ClientConfiguration_BackupSetRootMustNot));

    /// <summary>
    /// Backup set '{0}': root must not be empty.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetRootMustNot(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetRootMustNot, arg0);

    /// <summary>
    /// '{0}' declares schema_version {1}; this build reads version {2} only.
    /// </summary>
    private static string ClientConfiguration_DeclaresSchemaVersionBuildReads => Get(nameof(ClientConfiguration_DeclaresSchemaVersionBuildReads));

    /// <summary>
    /// '{0}' declares schema_version {1}; this build reads version {2} only.
    /// </summary>
    internal static string FormatClientConfiguration_DeclaresSchemaVersionBuildReads(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_DeclaresSchemaVersionBuildReads, arg0, arg1, arg2);

    /// <summary>
    /// '{0}' holds no configuration object.
    /// </summary>
    private static string ClientConfiguration_HoldsNoConfigurationObject => Get(nameof(ClientConfiguration_HoldsNoConfigurationObject));

    /// <summary>
    /// '{0}' holds no configuration object.
    /// </summary>
    internal static string FormatClientConfiguration_HoldsNoConfigurationObject(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_HoldsNoConfigurationObject, arg0);

    /// <summary>
    /// '{0}' is not a valid configuration file: {1}
    /// </summary>
    private static string ClientConfiguration_NotValidConfigurationFile => Get(nameof(ClientConfiguration_NotValidConfigurationFile));

    /// <summary>
    /// '{0}' is not a valid configuration file: {1}
    /// </summary>
    internal static string FormatClientConfiguration_NotValidConfigurationFile(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_NotValidConfigurationFile, arg0, arg1);

    /// <summary>
    /// No job '{0}' exists in the journal.
    /// </summary>
    private static string JobStateStore_NoJobExistsJournal => Get(nameof(JobStateStore_NoJobExistsJournal));

    /// <summary>
    /// No job '{0}' exists in the journal.
    /// </summary>
    internal static string FormatJobStateStore_NoJobExistsJournal(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, JobStateStore_NoJobExistsJournal, arg0);

    /// <summary>
    /// '{0}' holds no state object.
    /// </summary>
    private static string Model_HoldsNoStateObject => Get(nameof(Model_HoldsNoStateObject));

    /// <summary>
    /// '{0}' holds no state object.
    /// </summary>
    internal static string FormatModel_HoldsNoStateObject(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, Model_HoldsNoStateObject, arg0);

    /// <summary>
    /// Legacy identity file '{0}' is not 16 bytes of hex.
    /// </summary>
    private static string Model_LegacyIdentityFileNotBytes => Get(nameof(Model_LegacyIdentityFileNotBytes));

    /// <summary>
    /// Legacy identity file '{0}' is not 16 bytes of hex.
    /// </summary>
    internal static string FormatModel_LegacyIdentityFileNotBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, Model_LegacyIdentityFileNotBytes, arg0);

    /// <summary>
    /// '{0}' is not a valid state file: {1} — durable local state is never guessed.
    /// </summary>
    private static string Model_NotValidStateFile => Get(nameof(Model_NotValidStateFile));

    /// <summary>
    /// '{0}' is not a valid state file: {1} — durable local state is never guessed.
    /// </summary>
    internal static string FormatModel_NotValidStateFile(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, Model_NotValidStateFile, arg0, arg1);
}
