// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Application.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Application.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Application.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// Backup set '{0}': {1}
    /// </summary>
    private static string ClientConfiguration_BackupSet => Get(nameof(ClientConfiguration_BackupSet));

    /// <summary>
    /// Backup set '{0}': {1}
    /// </summary>
    internal static string FormatClientConfiguration_BackupSet(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSet, arg0, arg1);

    /// <summary>
    /// Backup set '{0}': id must be 32 hex digits.
    /// </summary>
    private static string ClientConfiguration_BackupSetIdMustHex => Get(nameof(ClientConfiguration_BackupSetIdMustHex));

    /// <summary>
    /// Backup set '{0}': id must be 32 hex digits.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetIdMustHex(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetIdMustHex, arg0);

    /// <summary>
    /// Backup set '{0}' references destination '{1}' more than once.
    /// </summary>
    private static string ClientConfiguration_BackupSetDuplicateDestination => Get(nameof(ClientConfiguration_BackupSetDuplicateDestination));

    /// <summary>
    /// Backup set '{0}' references destination '{1}' more than once.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetDuplicateDestination(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetDuplicateDestination, arg0, arg1);

    /// <summary>
    /// Backup set names must be non-empty and unique; '{0}' is not.
    /// </summary>
    private static string ClientConfiguration_BackupSetNamesMustNon => Get(nameof(ClientConfiguration_BackupSetNamesMustNon));

    /// <summary>
    /// Backup set names must be non-empty and unique; '{0}' is not.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetNamesMustNon(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetNamesMustNon, arg0);

    /// <summary>
    /// Backup set '{0}' declares no destinations; declare at least one — a local directory is the 'local-path' kind (FR-DEST-001).
    /// </summary>
    private static string ClientConfiguration_BackupSetNeedsDestination => Get(nameof(ClientConfiguration_BackupSetNeedsDestination));

    /// <summary>
    /// Backup set '{0}' declares no destinations; declare at least one — a local directory is the 'local-path' kind (FR-DEST-001).
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetNeedsDestination(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetNeedsDestination, arg0);

    /// <summary>
    /// Backup set '{0}': root must not be empty.
    /// </summary>
    private static string ClientConfiguration_BackupSetRootMustNot => Get(nameof(ClientConfiguration_BackupSetRootMustNot));

    /// <summary>
    /// Backup set '{0}': root must not be empty.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetRootMustNot(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetRootMustNot, arg0);

    /// <summary>
    /// Backup set '{0}' speaks both 'root' and 'roots'; a set carries exactly one of the two forms.
    /// </summary>
    private static string ClientConfiguration_BackupSetRootAndRoots => Get(nameof(ClientConfiguration_BackupSetRootAndRoots));

    /// <summary>
    /// Backup set '{0}' speaks both 'root' and 'roots'; a set carries exactly one of the two forms.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetRootAndRoots(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetRootAndRoots, arg0);

    /// <summary>
    /// Backup set '{0}' names the root '{1}' more than once.
    /// </summary>
    private static string ClientConfiguration_BackupSetRootPathsMustUnique => Get(nameof(ClientConfiguration_BackupSetRootPathsMustUnique));

    /// <summary>
    /// Backup set '{0}' names the root '{1}' more than once.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetRootPathsMustUnique(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetRootPathsMustUnique, arg0, arg1);

    /// <summary>
    /// Backup set '{0}': root label '{1}' is invalid — {2}.
    /// </summary>
    private static string ClientConfiguration_BackupSetLabelInvalid => Get(nameof(ClientConfiguration_BackupSetLabelInvalid));

    /// <summary>
    /// Backup set '{0}': root label '{1}' is invalid — {2}.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetLabelInvalid(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetLabelInvalid, arg0, arg1, arg2);

    /// <summary>
    /// Backup set '{0}': root label '{1}' is used more than once — labels name folders inside the snapshot, so they must stay distinct even case-insensitively.
    /// </summary>
    private static string ClientConfiguration_BackupSetLabelsMustUnique => Get(nameof(ClientConfiguration_BackupSetLabelsMustUnique));

    /// <summary>
    /// Backup set '{0}': root label '{1}' is used more than once — labels name folders inside the snapshot, so they must stay distinct even case-insensitively.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetLabelsMustUnique(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetLabelsMustUnique, arg0, arg1);

    /// <summary>
    /// Backup set '{0}' references destination '{1}', which is not declared.
    /// </summary>
    private static string ClientConfiguration_BackupSetUnknownDestination => Get(nameof(ClientConfiguration_BackupSetUnknownDestination));

    /// <summary>
    /// Backup set '{0}' references destination '{1}', which is not declared.
    /// </summary>
    internal static string FormatClientConfiguration_BackupSetUnknownDestination(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_BackupSetUnknownDestination, arg0, arg1);

    /// <summary>
    /// Logging: '{0}' is not a log level — the levels are {1}.
    /// </summary>
    private static string ClientConfiguration_LoggingLevelUnknown => Get(nameof(ClientConfiguration_LoggingLevelUnknown));

    /// <summary>
    /// Logging: '{0}' is not a log level — the levels are {1}.
    /// </summary>
    internal static string FormatClientConfiguration_LoggingLevelUnknown(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_LoggingLevelUnknown, arg0, arg1);

    /// <summary>
    /// Logging: category '{0}' asks for level '{1}', which is not a log level — the levels are {2}.
    /// </summary>
    private static string ClientConfiguration_LoggingCategoryLevelUnknown => Get(nameof(ClientConfiguration_LoggingCategoryLevelUnknown));

    /// <summary>
    /// Logging: category '{0}' asks for level '{1}', which is not a log level — the levels are {2}.
    /// </summary>
    internal static string FormatClientConfiguration_LoggingCategoryLevelUnknown(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_LoggingCategoryLevelUnknown, arg0, arg1, arg2);

    /// <summary>
    /// Logging: a category override must name a category; one of them is empty.
    /// </summary>
    internal static string ClientConfiguration_LoggingCategoryMustNotBeEmpty => Get(nameof(ClientConfiguration_LoggingCategoryMustNotBeEmpty));

    /// <summary>
    /// Logging: retain_files is {0}; it must be at least 1, or the log rolls into nothing.
    /// </summary>
    private static string ClientConfiguration_LoggingRetainFilesOutOfRange => Get(nameof(ClientConfiguration_LoggingRetainFilesOutOfRange));

    /// <summary>
    /// Logging: retain_files is {0}; it must be at least 1, or the log rolls into nothing.
    /// </summary>
    internal static string FormatClientConfiguration_LoggingRetainFilesOutOfRange(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_LoggingRetainFilesOutOfRange, arg0);

    /// <summary>
    /// Logging: max_file_bytes is {0}; it must be at least {1}, or a file rolls before it holds one useful session.
    /// </summary>
    private static string ClientConfiguration_LoggingMaxFileBytesOutOfRange => Get(nameof(ClientConfiguration_LoggingMaxFileBytesOutOfRange));

    /// <summary>
    /// Logging: max_file_bytes is {0}; it must be at least {1}, or a file rolls before it holds one useful session.
    /// </summary>
    internal static string FormatClientConfiguration_LoggingMaxFileBytesOutOfRange(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_LoggingMaxFileBytesOutOfRange, arg0, arg1);

    /// <summary>
    /// Logging: ring_capacity is {0}; it must be at least {1}, or a client reading the log misses records between two reads.
    /// </summary>
    private static string ClientConfiguration_LoggingRingCapacityOutOfRange => Get(nameof(ClientConfiguration_LoggingRingCapacityOutOfRange));

    /// <summary>
    /// Logging: ring_capacity is {0}; it must be at least {1}, or a client reading the log misses records between two reads.
    /// </summary>
    internal static string FormatClientConfiguration_LoggingRingCapacityOutOfRange(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_LoggingRingCapacityOutOfRange, arg0, arg1);

    /// <summary>
    /// '{0}' declares schema_version {1}; this build reads version {2} only.
    /// </summary>
    private static string ClientConfiguration_DeclaresSchemaVersionBuildReads => Get(nameof(ClientConfiguration_DeclaresSchemaVersionBuildReads));

    /// <summary>
    /// '{0}' declares schema_version {1}; this build reads version {2} only.
    /// </summary>
    internal static string FormatClientConfiguration_DeclaresSchemaVersionBuildReads(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_DeclaresSchemaVersionBuildReads, arg0, arg1, arg2);

    /// <summary>
    /// Destination '{0}': '{1}' does not apply to its kind.
    /// </summary>
    private static string ClientConfiguration_DestinationFieldNotForKind => Get(nameof(ClientConfiguration_DestinationFieldNotForKind));

    /// <summary>
    /// Destination '{0}': '{1}' does not apply to its kind.
    /// </summary>
    internal static string FormatClientConfiguration_DestinationFieldNotForKind(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_DestinationFieldNotForKind, arg0, arg1);

    /// <summary>
    /// Destination '{0}' is 'local-path' and cannot declare verification 'acknowledged-none': the hub can always read a directory it owns, and excusing the check costs the staging trim its licence to reclaim space.
    /// </summary>
    private static string ClientConfiguration_DestinationCannotDeclineVerification => Get(nameof(ClientConfiguration_DestinationCannotDeclineVerification));

    /// <summary>
    /// Destination '{0}' is 'local-path' and cannot declare verification 'acknowledged-none': the hub can always read a directory it owns, and excusing the check costs the staging trim its licence to reclaim space.
    /// </summary>
    internal static string FormatClientConfiguration_DestinationCannotDeclineVerification(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_DestinationCannotDeclineVerification, arg0);

    /// <summary>
    /// Destination '{0}': 'deep_verify_interval_days' must be a positive number of days; omit it to take the default.
    /// </summary>
    private static string ClientConfiguration_DestinationIntervalMustBePositive => Get(nameof(ClientConfiguration_DestinationIntervalMustBePositive));

    /// <summary>
    /// Destination '{0}': 'deep_verify_interval_days' must be a positive number of days; omit it to take the default.
    /// </summary>
    internal static string FormatClientConfiguration_DestinationIntervalMustBePositive(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_DestinationIntervalMustBePositive, arg0);

    /// <summary>
    /// Destination '{0}': id must be 32 hex digits.
    /// </summary>
    private static string ClientConfiguration_DestinationIdMustHex => Get(nameof(ClientConfiguration_DestinationIdMustHex));

    /// <summary>
    /// Destination '{0}': id must be 32 hex digits.
    /// </summary>
    internal static string FormatClientConfiguration_DestinationIdMustHex(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_DestinationIdMustHex, arg0);

    /// <summary>
    /// Destination names must be non-empty and unique; '{0}' is not.
    /// </summary>
    private static string ClientConfiguration_DestinationNamesMustNon => Get(nameof(ClientConfiguration_DestinationNamesMustNon));

    /// <summary>
    /// Destination names must be non-empty and unique; '{0}' is not.
    /// </summary>
    internal static string FormatClientConfiguration_DestinationNamesMustNon(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_DestinationNamesMustNon, arg0);

    /// <summary>
    /// Destination '{0}' is 'local-path' and must name a path.
    /// </summary>
    private static string ClientConfiguration_DestinationNeedsPath => Get(nameof(ClientConfiguration_DestinationNeedsPath));

    /// <summary>
    /// Destination '{0}' is 'local-path' and must name a path.
    /// </summary>
    internal static string FormatClientConfiguration_DestinationNeedsPath(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_DestinationNeedsPath, arg0);

    /// <summary>
    /// Destination '{0}' is 'peer' and must name a fingerprint and an endpoint.
    /// </summary>
    private static string ClientConfiguration_DestinationNeedsPeerIdentity => Get(nameof(ClientConfiguration_DestinationNeedsPeerIdentity));

    /// <summary>
    /// Destination '{0}' is 'peer' and must name a fingerprint and an endpoint.
    /// </summary>
    internal static string FormatClientConfiguration_DestinationNeedsPeerIdentity(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_DestinationNeedsPeerIdentity, arg0);

    /// <summary>
    /// '{0}' holds no configuration object.
    /// </summary>
    private static string ClientConfiguration_HoldsNoConfigurationObject => Get(nameof(ClientConfiguration_HoldsNoConfigurationObject));

    /// <summary>
    /// '{0}' holds no configuration object.
    /// </summary>
    internal static string FormatClientConfiguration_HoldsNoConfigurationObject(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_HoldsNoConfigurationObject, arg0);

    /// <summary>
    /// '{0}' is not a valid configuration file: {1}
    /// </summary>
    private static string ClientConfiguration_NotValidConfigurationFile => Get(nameof(ClientConfiguration_NotValidConfigurationFile));

    /// <summary>
    /// '{0}' is not a valid configuration file: {1}
    /// </summary>
    internal static string FormatClientConfiguration_NotValidConfigurationFile(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_NotValidConfigurationFile, arg0, arg1);

    /// <summary>
    /// Backup set '{0}': retention values for '{1}' must be positive.
    /// </summary>
    private static string ClientConfiguration_RetentionMustBePositive => Get(nameof(ClientConfiguration_RetentionMustBePositive));

    /// <summary>
    /// Backup set '{0}': retention values for '{1}' must be positive.
    /// </summary>
    internal static string FormatClientConfiguration_RetentionMustBePositive(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_RetentionMustBePositive, arg0, arg1);

    /// <summary>
    /// '{0}' declares max_concurrent_backups {1}; the backup pool takes 1 to 5 (ADR-0047).
    /// </summary>
    private static string ClientConfiguration_ConcurrencyOutOfRange => Get(nameof(ClientConfiguration_ConcurrencyOutOfRange));

    /// <summary>
    /// '{0}' declares max_concurrent_backups {1}; the backup pool takes 1 to 5 (ADR-0047).
    /// </summary>
    internal static string FormatClientConfiguration_ConcurrencyOutOfRange(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_ConcurrencyOutOfRange, arg0, arg1);

    /// <summary>
    /// '{0}' declares schema_version 1; this build reads version {1} (ADR-0034). Migrate: declare a top-level "destinations" table, give each backup set a "destinations" list naming at least one entry, and set schema_version to 2 — every version after that migrates itself on load.
    /// </summary>
    private static string ClientConfiguration_SchemaVersion1NeedsDestinations => Get(nameof(ClientConfiguration_SchemaVersion1NeedsDestinations));

    /// <summary>
    /// '{0}' declares schema_version 1; this build reads version {1} (ADR-0034). Migrate: declare a top-level "destinations" table, give each backup set a "destinations" list naming at least one entry, and set schema_version to 2 — every version after that migrates itself on load.
    /// </summary>
    internal static string FormatClientConfiguration_SchemaVersion1NeedsDestinations(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ClientConfiguration_SchemaVersion1NeedsDestinations, arg0, arg1);

    /// <summary>
    /// No job '{0}' exists in the journal.
    /// </summary>
    private static string JobStateStore_NoJobExistsJournal => Get(nameof(JobStateStore_NoJobExistsJournal));

    /// <summary>
    /// No job '{0}' exists in the journal.
    /// </summary>
    internal static string FormatJobStateStore_NoJobExistsJournal(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, JobStateStore_NoJobExistsJournal, arg0);

    /// <summary>
    /// '{0}' holds no state object.
    /// </summary>
    private static string Model_HoldsNoStateObject => Get(nameof(Model_HoldsNoStateObject));

    /// <summary>
    /// '{0}' holds no state object.
    /// </summary>
    internal static string FormatModel_HoldsNoStateObject(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, Model_HoldsNoStateObject, arg0);

    /// <summary>
    /// Legacy identity file '{0}' is not 16 bytes of hex.
    /// </summary>
    private static string Model_LegacyIdentityFileNotBytes => Get(nameof(Model_LegacyIdentityFileNotBytes));

    /// <summary>
    /// Legacy identity file '{0}' is not 16 bytes of hex.
    /// </summary>
    internal static string FormatModel_LegacyIdentityFileNotBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, Model_LegacyIdentityFileNotBytes, arg0);

    /// <summary>
    /// '{0}' is not a valid state file: {1} — durable local state is never guessed.
    /// </summary>
    private static string Model_NotValidStateFile => Get(nameof(Model_NotValidStateFile));

    /// <summary>
    /// '{0}' is not a valid state file: {1} — durable local state is never guessed.
    /// </summary>
    internal static string FormatModel_NotValidStateFile(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, Model_NotValidStateFile, arg0, arg1);
}
