#!/usr/bin/env python3
"""Generate the strongly-typed accessor for each assembly's Strings.resx.

Every user-facing exception message in FallbackPlan lives in a resx so it can
be translated (NFR-USE-004). Reaching one through `ResourceManager.GetString`
by name would put the key in a string literal, which is the same problem one
layer down: a typo compiles and fails at throw time, in front of the user,
in the situation the message exists to explain. So each resx gets a generated
accessor and the code names the message as a member.

The accessor is committed rather than produced by a design-time tool. This
repository has no Visual Studio in its build, and the SDK's own resx source
generation is not a public feature — the alternative was a source-generator
package in sixteen projects, which is a dependency where a fifty-line script
does. `--check` fails when a committed accessor no longer matches its resx,
which is what keeps "generated" from meaning "stale".

    eng/generate-resources.py            rewrite every Strings.g.cs
    eng/generate-resources.py --check    fail if any is out of date
"""
import pathlib
import re
import sys
import xml.etree.ElementTree as ElementTree

ROOT = pathlib.Path(__file__).resolve().parent.parent
HOLE = re.compile(r"\{(\d+)(?::[^}]*)?\}")


def read_resx(path):
    """The resx's data entries, in document order."""
    tree = ElementTree.parse(path)
    entries = []
    for data in tree.getroot().findall("data"):
        name = data.get("name")
        value = data.find("value")
        comment = data.find("comment")
        entries.append((name, value.text if value is not None else "",
                        comment.text if comment is not None else None))
    return entries


def placeholder_count(value):
    """How many distinct positional holes the message uses."""
    indexes = {int(m.group(1)) for m in HOLE.finditer(value)}
    return max(indexes) + 1 if indexes else 0


def xml_doc(value):
    """The message as an XML doc summary, escaped and collapsed to one line."""
    text = " ".join(value.split())
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def generate(project, resx):
    namespace = f"{project}.Resources"
    entries = read_resx(resx)

    lines = [
        "// <auto-generated>",
        "//     Generated by eng/generate-resources.py from Strings.resx.",
        "//     Edit the resx, then re-run the generator; edits here are overwritten.",
        "// </auto-generated>",
        "",
        "#nullable enable",
        "",
        "using System.Globalization;",
        "using System.Resources;",
        "",
        f"namespace {namespace};",
        "",
        "/// <summary>",
        f"/// The translated messages for {project}.",
        "/// </summary>",
        "internal static class Strings",
        "{",
        "    private static readonly ResourceManager Manager =",
        f'        new("{namespace}.Strings", typeof(Strings).Assembly);',
        "",
        "    /// <summary>The message for <paramref name=\"name\"/> in the caller's UI culture.</summary>",
        "    private static string Get(string name) =>",
        "        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;",
    ]

    for name, value, comment in entries:
        count = placeholder_count(value)
        lines.append("")
        lines.append("    /// <summary>")
        lines.append(f"    /// {xml_doc(value)}")
        lines.append("    /// </summary>")
        if comment:
            lines.append(f"    /// <remarks>{xml_doc(comment)}</remarks>")

        if count == 0:
            lines.append(f"    internal static string {name} => Get(nameof({name}));")
            continue

        # A message with holes is exposed only as a Format method. The raw
        # composite string stays private: handing it out invites a caller to
        # format it with the wrong argument count, which throws while building
        # the message for another failure. It is still a member rather than a
        # string literal in the lookup, so the resource name is checked by the
        # compiler and not merely by this script.
        parameters = ", ".join(f"object? arg{i}" for i in range(count))
        arguments = ", ".join(f"arg{i}" for i in range(count))
        lines.append(f"    private static string {name} => Get(nameof({name}));")
        lines.append("")
        lines.append("    /// <summary>")
        lines.append(f"    /// {xml_doc(value)}")
        lines.append("    /// </summary>")
        lines.append(f"    internal static string Format{name}({parameters}) =>")
        lines.append(f"        string.Format(CultureInfo.CurrentCulture, {name}, {arguments});")

    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    check = "--check" in sys.argv
    stale = []
    generated = 0

    for resx in sorted(ROOT.glob("src/*/Resources/Strings.resx")):
        project = resx.parent.parent.name
        target = resx.parent / "Strings.g.cs"
        content = generate(project, resx)

        if check:
            if not target.exists() or target.read_text() != content:
                stale.append(target.relative_to(ROOT))
        else:
            target.write_text(content)
        generated += 1

    if check and stale:
        print("FAIL generated resource accessors are out of date:")
        for path in stale:
            print(f"       {path}")
        print("       run eng/generate-resources.py")
        return 1

    print(f"resource accessors : {generated}")
    print("all checks passed" if check else "generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
