<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FallbackPlan.Domain\FallbackPlan.Domain.csproj" />
    <ProjectReference Include="..\FallbackPlan.Repository.Format\FallbackPlan.Repository.Format.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
