<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FallbackPlan.Application\FallbackPlan.Application.csproj" />
    <ProjectReference Include="..\FallbackPlan.Domain\FallbackPlan.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bodu.Security.Cryptography" />
    <PackageReference Include="System.Formats.Cbor" />
  </ItemGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
