// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Repository.Format.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Repository.Format.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Repository.Format.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// Array declares {0} items; the limit here is {1}.
    /// </summary>
    private static string CanonicalCborReader_ArrayDeclaresItemsLimitHere => Get(nameof(CanonicalCborReader_ArrayDeclaresItemsLimitHere));

    /// <summary>
    /// Array declares {0} items; the limit here is {1}.
    /// </summary>
    internal static string FormatCanonicalCborReader_ArrayDeclaresItemsLimitHere(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, CanonicalCborReader_ArrayDeclaresItemsLimitHere, arg0, arg1);

    /// <summary>
    /// Byte string is {0} bytes; exactly {1} required.
    /// </summary>
    private static string CanonicalCborReader_ByteStringBytesExactlyRequired => Get(nameof(CanonicalCborReader_ByteStringBytesExactlyRequired));

    /// <summary>
    /// Byte string is {0} bytes; exactly {1} required.
    /// </summary>
    internal static string FormatCanonicalCborReader_ByteStringBytesExactlyRequired(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, CanonicalCborReader_ByteStringBytesExactlyRequired, arg0, arg1);

    /// <summary>
    /// Byte string declares {0} bytes; the limit here is {1}.
    /// </summary>
    private static string CanonicalCborReader_ByteStringDeclaresBytesLimit => Get(nameof(CanonicalCborReader_ByteStringDeclaresBytesLimit));

    /// <summary>
    /// Byte string declares {0} bytes; the limit here is {1}.
    /// </summary>
    internal static string FormatCanonicalCborReader_ByteStringDeclaresBytesLimit(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, CanonicalCborReader_ByteStringDeclaresBytesLimit, arg0, arg1);

    /// <summary>
    /// CBOR input violates the deterministic encoding profile.
    /// </summary>
    internal static string CanonicalCborReader_CBORInputViolatesDeterministicEncoding => Get(nameof(CanonicalCborReader_CBORInputViolatesDeterministicEncoding));

    /// <summary>
    /// CBOR integer is out of range for the required width.
    /// </summary>
    internal static string CanonicalCborReader_CBORIntegerOutRangeRequired => Get(nameof(CanonicalCborReader_CBORIntegerOutRangeRequired));

    /// <summary>
    /// CBOR item is not of the required type.
    /// </summary>
    internal static string CanonicalCborReader_CBORItemNotRequiredType => Get(nameof(CanonicalCborReader_CBORItemNotRequiredType));

    /// <summary>
    /// CBOR tags are forbidden; format v1 defines none (specification 00 §4.1 rule 6).
    /// </summary>
    internal static string CanonicalCborReader_CBORTagsForbiddenFormatV => Get(nameof(CanonicalCborReader_CBORTagsForbiddenFormatV));

    /// <summary>
    /// Floating-point values are forbidden (specification 00 §4.1 rule 5).
    /// </summary>
    internal static string CanonicalCborReader_FloatingPointValuesForbidden => Get(nameof(CanonicalCborReader_FloatingPointValuesForbidden));

    /// <summary>
    /// Indefinite-length array.
    /// </summary>
    internal static string CanonicalCborReader_IndefiniteLengthArray => Get(nameof(CanonicalCborReader_IndefiniteLengthArray));

    /// <summary>
    /// Indefinite-length map.
    /// </summary>
    internal static string CanonicalCborReader_IndefiniteLengthMap => Get(nameof(CanonicalCborReader_IndefiniteLengthMap));

    /// <summary>
    /// Map keys must be unsigned integers (specification 00 §4.2).
    /// </summary>
    internal static string CanonicalCborReader_MapKeysMustUnsignedIntegers => Get(nameof(CanonicalCborReader_MapKeysMustUnsignedIntegers));

    /// <summary>
    /// Text string declares {0} UTF-8 bytes; the limit here is {1}.
    /// </summary>
    private static string CanonicalCborReader_TextStringDeclaresUTFBytes => Get(nameof(CanonicalCborReader_TextStringDeclaresUTFBytes));

    /// <summary>
    /// Text string declares {0} UTF-8 bytes; the limit here is {1}.
    /// </summary>
    internal static string FormatCanonicalCborReader_TextStringDeclaresUTFBytes(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, CanonicalCborReader_TextStringDeclaresUTFBytes, arg0, arg1);

    /// <summary>
    /// Trailing bytes after the root CBOR value.
    /// </summary>
    internal static string CanonicalCborReader_TrailingBytesAfterRootCBOR => Get(nameof(CanonicalCborReader_TrailingBytesAfterRootCBOR));

    /// <summary>
    /// Unsupported CBOR item '{0}' in a format object.
    /// </summary>
    private static string CanonicalCborReader_UnsupportedCBORItemFormatObject => Get(nameof(CanonicalCborReader_UnsupportedCBORItemFormatObject));

    /// <summary>
    /// Unsupported CBOR item '{0}' in a format object.
    /// </summary>
    internal static string FormatCanonicalCborReader_UnsupportedCBORItemFormatObject(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CanonicalCborReader_UnsupportedCBORItemFormatObject, arg0);

    /// <summary>
    /// Value {0} does not fit a u16.
    /// </summary>
    private static string CanonicalCborReader_ValueDoesNotFitU => Get(nameof(CanonicalCborReader_ValueDoesNotFitU));

    /// <summary>
    /// Value {0} does not fit a u16.
    /// </summary>
    internal static string FormatCanonicalCborReader_ValueDoesNotFitU(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CanonicalCborReader_ValueDoesNotFitU, arg0);

    /// <summary>
    /// Value {0} does not fit a u8.
    /// </summary>
    private static string CanonicalCborReader_ValueDoesNotFitU2 => Get(nameof(CanonicalCborReader_ValueDoesNotFitU2));

    /// <summary>
    /// Value {0} does not fit a u8.
    /// </summary>
    internal static string FormatCanonicalCborReader_ValueDoesNotFitU2(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CanonicalCborReader_ValueDoesNotFitU2, arg0);

    /// <summary>
    /// The error manifest carries exactly key 1 (specification 06 §8).
    /// </summary>
    internal static string ErrorManifestCodec_ErrorManifestCarriesExactlyKey => Get(nameof(ErrorManifestCodec_ErrorManifestCarriesExactlyKey));

    /// <summary>
    /// The error manifest is not canonical CBOR: {0}
    /// </summary>
    private static string ErrorManifestCodec_ErrorManifestNotCanonicalCBOR => Get(nameof(ErrorManifestCodec_ErrorManifestNotCanonicalCBOR));

    /// <summary>
    /// The error manifest is not canonical CBOR: {0}
    /// </summary>
    internal static string FormatErrorManifestCodec_ErrorManifestNotCanonicalCBOR(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ErrorManifestCodec_ErrorManifestNotCanonicalCBOR, arg0);

    /// <summary>
    /// A failure entry carries an unknown key; specification 06 §8.1 assigns keys 1-3 only.
    /// </summary>
    internal static string ErrorManifestCodec_FailureEntryCarriesUnknownKey => Get(nameof(ErrorManifestCodec_FailureEntryCarriesUnknownKey));

    /// <summary>
    /// A failure entry omits a mandatory key (specification 06 §8.1).
    /// </summary>
    internal static string ErrorManifestCodec_FailureEntryOmitsMandatoryKey => Get(nameof(ErrorManifestCodec_FailureEntryOmitsMandatoryKey));

    /// <summary>
    /// Failure reason {0} is unassigned (specification 06 §8.1).
    /// </summary>
    private static string ErrorManifestCodec_FailureReasonUnassigned => Get(nameof(ErrorManifestCodec_FailureReasonUnassigned));

    /// <summary>
    /// Failure reason {0} is unassigned (specification 06 §8.1).
    /// </summary>
    internal static string FormatErrorManifestCodec_FailureReasonUnassigned(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ErrorManifestCodec_FailureReasonUnassigned, arg0);

    /// <summary>
    /// An alternate stream is exactly three elements (specification 06 §4.1).
    /// </summary>
    internal static string FileVersionManifestCodec_AlternateStreamExactlyThreeElements => Get(nameof(FileVersionManifestCodec_AlternateStreamExactlyThreeElements));

    /// <summary>
    /// capture_diagnostics is present only when non-empty (specification 06 §4).
    /// </summary>
    internal static string FileVersionManifestCodec_CaptureDiagnosticsPresentOnlyWhen => Get(nameof(FileVersionManifestCodec_CaptureDiagnosticsPresentOnlyWhen));

    /// <summary>
    /// Coverage breaks at offset {0}: the next piece starts at {1}. References and sparse extents MUST cover [0, logical_length) exactly, without gaps or overlap (specification 06 §3.2).
    /// </summary>
    private static string FileVersionManifestCodec_CoverageBreaksOffsetNextPiece => Get(nameof(FileVersionManifestCodec_CoverageBreaksOffsetNextPiece));

    /// <summary>
    /// Coverage breaks at offset {0}: the next piece starts at {1}. References and sparse extents MUST cover [0, logical_length) exactly, without gaps or overlap (specification 06 §3.2).
    /// </summary>
    internal static string FormatFileVersionManifestCodec_CoverageBreaksOffsetNextPiece(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, FileVersionManifestCodec_CoverageBreaksOffsetNextPiece, arg0, arg1);

    /// <summary>
    /// The encoded manifest is {0} bytes; the metadata limit is 16 MiB (specification 00 §8).
    /// </summary>
    private static string FileVersionManifestCodec_EncodedManifestBytesMetadataLimit => Get(nameof(FileVersionManifestCodec_EncodedManifestBytesMetadataLimit));

    /// <summary>
    /// The encoded manifest is {0} bytes; the metadata limit is 16 MiB (specification 00 §8).
    /// </summary>
    internal static string FormatFileVersionManifestCodec_EncodedManifestBytesMetadataLimit(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, FileVersionManifestCodec_EncodedManifestBytesMetadataLimit, arg0);

    /// <summary>
    /// entry_kind {0} is unassigned (specification 06 §4).
    /// </summary>
    private static string FileVersionManifestCodec_EntryKindUnassigned => Get(nameof(FileVersionManifestCodec_EntryKindUnassigned));

    /// <summary>
    /// entry_kind {0} is unassigned (specification 06 §4).
    /// </summary>
    internal static string FormatFileVersionManifestCodec_EntryKindUnassigned(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, FileVersionManifestCodec_EntryKindUnassigned, arg0);

    /// <summary>
    /// An extended attribute is exactly two byte strings (specification 06 §4.1).
    /// </summary>
    internal static string FileVersionManifestCodec_ExtendedAttributeExactlyTwoByte => Get(nameof(FileVersionManifestCodec_ExtendedAttributeExactlyTwoByte));

    /// <summary>
    /// The manifest carries an unknown key; specification 06 §4 assigns keys 1-13 only, and a reader MUST reject rather than skip (06 §3.1).
    /// </summary>
    internal static string FileVersionManifestCodec_ManifestCarriesUnknownKeySpecification => Get(nameof(FileVersionManifestCodec_ManifestCarriesUnknownKeySpecification));

    /// <summary>
    /// The manifest is not canonical CBOR: {0}
    /// </summary>
    private static string FileVersionManifestCodec_ManifestNotCanonicalCBOR => Get(nameof(FileVersionManifestCodec_ManifestNotCanonicalCBOR));

    /// <summary>
    /// The manifest is not canonical CBOR: {0}
    /// </summary>
    internal static string FormatFileVersionManifestCodec_ManifestNotCanonicalCBOR(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, FileVersionManifestCodec_ManifestNotCanonicalCBOR, arg0);

    /// <summary>
    /// The manifest omits a mandatory key (specification 06 §4).
    /// </summary>
    internal static string FileVersionManifestCodec_ManifestOmitsMandatoryKey => Get(nameof(FileVersionManifestCodec_ManifestOmitsMandatoryKey));

    /// <summary>
    /// The metadata map carries an unknown key; specification 06 §4.1 assigns keys 1-10 only.
    /// </summary>
    internal static string FileVersionManifestCodec_MetadataMapCarriesUnknownKey => Get(nameof(FileVersionManifestCodec_MetadataMapCarriesUnknownKey));

    /// <summary>
    /// name_normalisation {0} is unassigned (specification 06 §4).
    /// </summary>
    private static string FileVersionManifestCodec_NameNormalisationUnassigned => Get(nameof(FileVersionManifestCodec_NameNormalisationUnassigned));

    /// <summary>
    /// name_normalisation {0} is unassigned (specification 06 §4).
    /// </summary>
    internal static string FormatFileVersionManifestCodec_NameNormalisationUnassigned(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, FileVersionManifestCodec_NameNormalisationUnassigned, arg0);

    /// <summary>
    /// References and sparse extents cover {0} bytes; logical_length declares {1} (specification 06 §3.2).
    /// </summary>
    private static string FileVersionManifestCodec_ReferencesSparseExtentsCoverBytes => Get(nameof(FileVersionManifestCodec_ReferencesSparseExtentsCoverBytes));

    /// <summary>
    /// References and sparse extents cover {0} bytes; logical_length declares {1} (specification 06 §3.2).
    /// </summary>
    internal static string FormatFileVersionManifestCodec_ReferencesSparseExtentsCoverBytes(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, FileVersionManifestCodec_ReferencesSparseExtentsCoverBytes, arg0, arg1);

    /// <summary>
    /// A segment reference is exactly three elements; got {0} — a fourth element is where physical location would smuggle in (specification 06 §3, §3.1).
    /// </summary>
    private static string FileVersionManifestCodec_SegmentReferenceExactlyThreeElements => Get(nameof(FileVersionManifestCodec_SegmentReferenceExactlyThreeElements));

    /// <summary>
    /// A segment reference is exactly three elements; got {0} — a fourth element is where physical location would smuggle in (specification 06 §3, §3.1).
    /// </summary>
    internal static string FormatFileVersionManifestCodec_SegmentReferenceExactlyThreeElements(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, FileVersionManifestCodec_SegmentReferenceExactlyThreeElements, arg0);

    /// <summary>
    /// A segment reference's offset must be non-negative and its length positive (specification 06 §3).
    /// </summary>
    internal static string FileVersionManifestCodec_SegmentReferenceSOffsetMust => Get(nameof(FileVersionManifestCodec_SegmentReferenceSOffsetMust));

    /// <summary>
    /// {0} segment references exceed the 1 048 576 maximum — a file this large requires a larger segment size (specification 06 §3.2).
    /// </summary>
    private static string FileVersionManifestCodec_SegmentReferencesExceedMaximum => Get(nameof(FileVersionManifestCodec_SegmentReferencesExceedMaximum));

    /// <summary>
    /// {0} segment references exceed the 1 048 576 maximum — a file this large requires a larger segment size (specification 06 §3.2).
    /// </summary>
    internal static string FormatFileVersionManifestCodec_SegmentReferencesExceedMaximum(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, FileVersionManifestCodec_SegmentReferencesExceedMaximum, arg0);

    /// <summary>
    /// Segment references MUST be ordered by ascending logical_offset (specification 06 §3.2).
    /// </summary>
    internal static string FileVersionManifestCodec_SegmentReferencesMUSTOrderedAscending => Get(nameof(FileVersionManifestCodec_SegmentReferencesMUSTOrderedAscending));

    /// <summary>
    /// A sparse extent is exactly two elements; got {0} (specification 06 §4).
    /// </summary>
    private static string FileVersionManifestCodec_SparseExtentExactlyTwoElements => Get(nameof(FileVersionManifestCodec_SparseExtentExactlyTwoElements));

    /// <summary>
    /// A sparse extent is exactly two elements; got {0} (specification 06 §4).
    /// </summary>
    internal static string FormatFileVersionManifestCodec_SparseExtentExactlyTwoElements(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, FileVersionManifestCodec_SparseExtentExactlyTwoElements, arg0);

    /// <summary>
    /// A sparse extent's length must be positive (specification 06 §4).
    /// </summary>
    internal static string FileVersionManifestCodec_SparseExtentSLengthMust => Get(nameof(FileVersionManifestCodec_SparseExtentSLengthMust));

    /// <summary>
    /// whole_file_hash is exactly 32 bytes (specification 06 §4).
    /// </summary>
    internal static string FileVersionManifestCodec_WholeFileHashExactlyBytes => Get(nameof(FileVersionManifestCodec_WholeFileHashExactlyBytes));

    /// <summary>
    /// The footer AAD is exactly {0} bytes; got {1}.
    /// </summary>
    private static string FooterAad_FooterAADExactlyBytesGot => Get(nameof(FooterAad_FooterAADExactlyBytesGot));

    /// <summary>
    /// The footer AAD is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatFooterAad_FooterAADExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, FooterAad_FooterAADExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// Key bundle is {0} bytes; the limit is {1} (specification 00 §8).
    /// </summary>
    private static string KeyBundleCodec_KeyBundleBytesLimit => Get(nameof(KeyBundleCodec_KeyBundleBytesLimit));

    /// <summary>
    /// Key bundle is {0} bytes; the limit is {1} (specification 00 §8).
    /// </summary>
    internal static string FormatKeyBundleCodec_KeyBundleBytesLimit(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, KeyBundleCodec_KeyBundleBytesLimit, arg0, arg1);

    /// <summary>
    /// Key bundle is missing a required field (specification 03 §3.1).
    /// </summary>
    internal static string KeyBundleCodec_KeyBundleMissingRequiredField => Get(nameof(KeyBundleCodec_KeyBundleMissingRequiredField));

    /// <summary>
    /// The master key is exactly 32 bytes (specification 03 §3.1).
    /// </summary>
    internal static string KeyBundle_MasterKeyExactlyBytes => Get(nameof(KeyBundle_MasterKeyExactlyBytes));

    /// <summary>
    /// Key object is {0} bytes; the declared bundle length implies exactly {1}.
    /// </summary>
    private static string KeyObjectFraming_KeyObjectBytesDeclaredBundle => Get(nameof(KeyObjectFraming_KeyObjectBytesDeclaredBundle));

    /// <summary>
    /// Key object is {0} bytes; the declared bundle length implies exactly {1}.
    /// </summary>
    internal static string FormatKeyObjectFraming_KeyObjectBytesDeclaredBundle(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, KeyObjectFraming_KeyObjectBytesDeclaredBundle, arg0, arg1);

    /// <summary>
    /// Key object is {0} bytes; the framing alone requires {1}.
    /// </summary>
    private static string KeyObjectFraming_KeyObjectBytesFramingAlone => Get(nameof(KeyObjectFraming_KeyObjectBytesFramingAlone));

    /// <summary>
    /// Key object is {0} bytes; the framing alone requires {1}.
    /// </summary>
    internal static string FormatKeyObjectFraming_KeyObjectBytesFramingAlone(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, KeyObjectFraming_KeyObjectBytesFramingAlone, arg0, arg1);

    /// <summary>
    /// Not a key object: the FBPKKEYS magic is absent.
    /// </summary>
    internal static string KeyObjectFraming_NotKeyObjectFBPKKEYSMagic => Get(nameof(KeyObjectFraming_NotKeyObjectFBPKKEYSMagic));

    /// <summary>
    /// The wrap nonce is exactly {0} bytes.
    /// </summary>
    private static string KeyObjectFraming_WrapNonceExactlyBytes => Get(nameof(KeyObjectFraming_WrapNonceExactlyBytes));

    /// <summary>
    /// The wrap nonce is exactly {0} bytes.
    /// </summary>
    internal static string FormatKeyObjectFraming_WrapNonceExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, KeyObjectFraming_WrapNonceExactlyBytes, arg0);

    /// <summary>
    /// Wrap profile 0x{0:x4} is not permitted: format v1 requires aes-256-gcm-v1 (0x0001) (specification 03 §3).
    /// </summary>
    private static string KeyObjectFraming_WrapProfileXNotPermitted => Get(nameof(KeyObjectFraming_WrapProfileXNotPermitted));

    /// <summary>
    /// Wrap profile 0x{0:x4} is not permitted: format v1 requires aes-256-gcm-v1 (0x0001) (specification 03 §3).
    /// </summary>
    internal static string FormatKeyObjectFraming_WrapProfileXNotPermitted(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, KeyObjectFraming_WrapProfileXNotPermitted, arg0);

    /// <summary>
    /// The wrap tag is exactly {0} bytes.
    /// </summary>
    private static string KeyObjectFraming_WrapTagExactlyBytes => Get(nameof(KeyObjectFraming_WrapTagExactlyBytes));

    /// <summary>
    /// The wrap tag is exactly {0} bytes.
    /// </summary>
    internal static string FormatKeyObjectFraming_WrapTagExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, KeyObjectFraming_WrapTagExactlyBytes, arg0);

    /// <summary>
    /// The wrapped bundle is {0} bytes; the limit is {1} (specification 00 §8).
    /// </summary>
    private static string KeyObjectFraming_WrappedBundleBytesLimit => Get(nameof(KeyObjectFraming_WrappedBundleBytesLimit));

    /// <summary>
    /// The wrapped bundle is {0} bytes; the limit is {1} (specification 00 §8).
    /// </summary>
    internal static string FormatKeyObjectFraming_WrappedBundleBytesLimit(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, KeyObjectFraming_WrappedBundleBytesLimit, arg0, arg1);

    /// <summary>
    /// Wrapped bundle declares {0} bytes; the limit is {1} (specification 00 §8).
    /// </summary>
    private static string KeyObjectFraming_WrappedBundleDeclaresBytesLimit => Get(nameof(KeyObjectFraming_WrappedBundleDeclaresBytesLimit));

    /// <summary>
    /// Wrapped bundle declares {0} bytes; the limit is {1} (specification 00 §8).
    /// </summary>
    internal static string FormatKeyObjectFraming_WrappedBundleDeclaresBytesLimit(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, KeyObjectFraming_WrappedBundleDeclaresBytesLimit, arg0, arg1);

    /// <summary>
    /// blob_write_profile carries an unknown key (ADR-0022 §Decision 6).
    /// </summary>
    internal static string PolicyManifestCodec_BlobWriteProfileCarriesUnknown => Get(nameof(PolicyManifestCodec_BlobWriteProfileCarriesUnknown));

    /// <summary>
    /// The policy manifest carries an unknown key; specification 06 §7 assigns keys 1-9 only.
    /// </summary>
    internal static string PolicyManifestCodec_PolicyManifestCarriesUnknownKey => Get(nameof(PolicyManifestCodec_PolicyManifestCarriesUnknownKey));

    /// <summary>
    /// The policy manifest is not canonical CBOR: {0}
    /// </summary>
    private static string PolicyManifestCodec_PolicyManifestNotCanonicalCBOR => Get(nameof(PolicyManifestCodec_PolicyManifestNotCanonicalCBOR));

    /// <summary>
    /// The policy manifest is not canonical CBOR: {0}
    /// </summary>
    internal static string FormatPolicyManifestCodec_PolicyManifestNotCanonicalCBOR(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, PolicyManifestCodec_PolicyManifestNotCanonicalCBOR, arg0);

    /// <summary>
    /// The policy manifest omits a mandatory key (specification 06 §7).
    /// </summary>
    internal static string PolicyManifestCodec_PolicyManifestOmitsMandatoryKey => Get(nameof(PolicyManifestCodec_PolicyManifestOmitsMandatoryKey));

    /// <summary>
    /// segmentation_parameters carries an unknown key (ADR-0022 §Decision 6).
    /// </summary>
    internal static string PolicyManifestCodec_SegmentationParametersCarriesUnknownKey => Get(nameof(PolicyManifestCodec_SegmentationParametersCarriesUnknownKey));

    /// <summary>
    /// The record AAD is exactly {0} bytes; got {1}.
    /// </summary>
    private static string RecordAad_RecordAADExactlyBytesGot => Get(nameof(RecordAad_RecordAADExactlyBytesGot));

    /// <summary>
    /// The record AAD is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatRecordAad_RecordAADExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RecordAad_RecordAADExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// Compression profile 0x{0:x4} is unknown; refused, not guessed (specification 00 §3).
    /// </summary>
    private static string RecordHeader_CompressionProfileXUnknownRefused => Get(nameof(RecordHeader_CompressionProfileXUnknownRefused));

    /// <summary>
    /// Compression profile 0x{0:x4} is unknown; refused, not guessed (specification 00 §3).
    /// </summary>
    internal static string FormatRecordHeader_CompressionProfileXUnknownRefused(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecordHeader_CompressionProfileXUnknownRefused, arg0);

    /// <summary>
    /// Encryption profile 0x{0:x4} is unknown; refused, not guessed (specification 00 §3).
    /// </summary>
    private static string RecordHeader_EncryptionProfileXUnknownRefused => Get(nameof(RecordHeader_EncryptionProfileXUnknownRefused));

    /// <summary>
    /// Encryption profile 0x{0:x4} is unknown; refused, not guessed (specification 00 §3).
    /// </summary>
    internal static string FormatRecordHeader_EncryptionProfileXUnknownRefused(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecordHeader_EncryptionProfileXUnknownRefused, arg0);

    /// <summary>
    /// logical_length is zero — a damage finding: zero-length files produce no records (specification 04 §2.1).
    /// </summary>
    internal static string RecordHeader_LogicalLengthZero => Get(nameof(RecordHeader_LogicalLengthZero));

    /// <summary>
    /// Not an assigned object type (specification 02 §3.1).
    /// </summary>
    internal static string RecordHeader_NotAssignedObjectType => Get(nameof(RecordHeader_NotAssignedObjectType));

    /// <summary>
    /// Object type 0x{0:x2} is not assigned — including the reserved 0x07 (specification 02 §3.1).
    /// </summary>
    private static string RecordHeader_ObjectTypeXNotAssigned => Get(nameof(RecordHeader_ObjectTypeXNotAssigned));

    /// <summary>
    /// Object type 0x{0:x2} is not assigned — including the reserved 0x07 (specification 02 §3.1).
    /// </summary>
    internal static string FormatRecordHeader_ObjectTypeXNotAssigned(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecordHeader_ObjectTypeXNotAssigned, arg0);

    /// <summary>
    /// Ordinal {0} exceeds {1} (specification 04 §2.1).
    /// </summary>
    private static string RecordHeader_OrdinalExceeds => Get(nameof(RecordHeader_OrdinalExceeds));

    /// <summary>
    /// Ordinal {0} exceeds {1} (specification 04 §2.1).
    /// </summary>
    internal static string FormatRecordHeader_OrdinalExceeds(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RecordHeader_OrdinalExceeds, arg0, arg1);

    /// <summary>
    /// A record header is {0} bytes; got {1}.
    /// </summary>
    private static string RecordHeader_RecordHeaderBytesGot => Get(nameof(RecordHeader_RecordHeaderBytesGot));

    /// <summary>
    /// A record header is {0} bytes; got {1}.
    /// </summary>
    internal static string FormatRecordHeader_RecordHeaderBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RecordHeader_RecordHeaderBytesGot, arg0, arg1);

    /// <summary>
    /// A record header is exactly {0} bytes; got {1}.
    /// </summary>
    private static string RecordHeader_RecordHeaderExactlyBytesGot => Get(nameof(RecordHeader_RecordHeaderExactlyBytesGot));

    /// <summary>
    /// A record header is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatRecordHeader_RecordHeaderExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RecordHeader_RecordHeaderExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// The record marker 0x52 is absent (specification 04 §2.1).
    /// </summary>
    internal static string RecordHeader_RecordMarkerXAbsent => Get(nameof(RecordHeader_RecordMarkerXAbsent));

    /// <summary>
    /// stored_length {0} exceeds the 64 MiB record limit (specification 00 §8) — refused before allocation.
    /// </summary>
    private static string RecordHeader_StoredLengthExceedsMiBRecord => Get(nameof(RecordHeader_StoredLengthExceedsMiBRecord));

    /// <summary>
    /// stored_length {0} exceeds the 64 MiB record limit (specification 00 §8) — refused before allocation.
    /// </summary>
    internal static string FormatRecordHeader_StoredLengthExceedsMiBRecord(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecordHeader_StoredLengthExceedsMiBRecord, arg0);

    /// <summary>
    /// With compression profile none, stored_length equals logical_length (specification 04 §2.1).
    /// </summary>
    internal static string RecordHeader_WithCompressionProfileNoneStored => Get(nameof(RecordHeader_WithCompressionProfileNoneStored));

    /// <summary>
    /// With compression profile none, stored_length must equal logical_length (specification 04 §2.1).
    /// </summary>
    internal static string RecordHeader_WithCompressionProfileNoneStored2 => Get(nameof(RecordHeader_WithCompressionProfileNoneStored2));

    /// <summary>
    /// The footer nonce is {0} bytes; got {1}.
    /// </summary>
    private static string RecordNonce_FooterNonceBytesGot => Get(nameof(RecordNonce_FooterNonceBytesGot));

    /// <summary>
    /// The footer nonce is {0} bytes; got {1}.
    /// </summary>
    internal static string FormatRecordNonce_FooterNonceBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RecordNonce_FooterNonceBytesGot, arg0, arg1);

    /// <summary>
    /// A record nonce is {0} or {1} bytes; got {2}.
    /// </summary>
    private static string RecordNonce_RecordNonceBytesGot => Get(nameof(RecordNonce_RecordNonceBytesGot));

    /// <summary>
    /// A record nonce is {0} or {1} bytes; got {2}.
    /// </summary>
    internal static string FormatRecordNonce_RecordNonceBytesGot(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, RecordNonce_RecordNonceBytesGot, arg0, arg1, arg2);

    /// <summary>
    /// A destination carries exactly 4 keys (specifications/recovery-kit §2).
    /// </summary>
    internal static string RecoveryKitCodec_DestinationCarriesExactlyKeys => Get(nameof(RecoveryKitCodec_DestinationCarriesExactlyKeys));

    /// <summary>
    /// A destination carries an unknown key (specifications/recovery-kit §2).
    /// </summary>
    internal static string RecoveryKitCodec_DestinationCarriesUnknownKey => Get(nameof(RecoveryKitCodec_DestinationCarriesUnknownKey));

    /// <summary>
    /// The framed version ({0}) and body key 1 ({1}) disagree.
    /// </summary>
    private static string RecoveryKitCodec_FramedVersionBodyKeyDisagree => Get(nameof(RecoveryKitCodec_FramedVersionBodyKeyDisagree));

    /// <summary>
    /// The framed version ({0}) and body key 1 ({1}) disagree.
    /// </summary>
    internal static string FormatRecoveryKitCodec_FramedVersionBodyKeyDisagree(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryKitCodec_FramedVersionBodyKeyDisagree, arg0, arg1);

    /// <summary>
    /// kdf_parameters carries exactly 4 keys (specifications/recovery-kit §2).
    /// </summary>
    internal static string RecoveryKitCodec_KdfParametersCarriesExactlyKeys => Get(nameof(RecoveryKitCodec_KdfParametersCarriesExactlyKeys));

    /// <summary>
    /// kdf_parameters carries an unknown key (specifications/recovery-kit §2).
    /// </summary>
    internal static string RecoveryKitCodec_KdfParametersCarriesUnknownKey => Get(nameof(RecoveryKitCodec_KdfParametersCarriesUnknownKey));

    /// <summary>
    /// kdf salt and issuing device id are 16 bytes each (specifications/recovery-kit §2).
    /// </summary>
    internal static string RecoveryKitCodec_KdfSaltIssuingDeviceId => Get(nameof(RecoveryKitCodec_KdfSaltIssuingDeviceId));

    /// <summary>
    /// Key 5 must be a verbatim FBPKKEYS key object (specifications/recovery-kit §2).
    /// </summary>
    internal static string RecoveryKitCodec_KeyMustVerbatimFBPKKEYSKey => Get(nameof(RecoveryKitCodec_KeyMustVerbatimFBPKKEYSKey));

    /// <summary>
    /// The kit body carries an unknown key; a v1 kit assigns keys 1-10 only (specifications/recovery-kit §2).
    /// </summary>
    internal static string RecoveryKitCodec_KitBodyCarriesUnknownKey => Get(nameof(RecoveryKitCodec_KitBodyCarriesUnknownKey));

    /// <summary>
    /// The kit body omits a mandatory key (specifications/recovery-kit §2).
    /// </summary>
    internal static string RecoveryKitCodec_KitBodyOmitsMandatoryKey => Get(nameof(RecoveryKitCodec_KitBodyOmitsMandatoryKey));

    /// <summary>
    /// The kit is {0} bytes; the framing declares {1}.
    /// </summary>
    private static string RecoveryKitCodec_KitBytesFramingDeclares => Get(nameof(RecoveryKitCodec_KitBytesFramingDeclares));

    /// <summary>
    /// The kit is {0} bytes; the framing declares {1}.
    /// </summary>
    internal static string FormatRecoveryKitCodec_KitBytesFramingDeclares(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryKitCodec_KitBytesFramingDeclares, arg0, arg1);

    /// <summary>
    /// The kit checksum does not verify — transcription or storage damage (specifications/recovery-kit §3).
    /// </summary>
    internal static string RecoveryKitCodec_KitChecksumDoesNotVerify => Get(nameof(RecoveryKitCodec_KitChecksumDoesNotVerify));

    /// <summary>
    /// The kit declares a {0}-byte body; the bound is {1} (specifications/recovery-kit §3).
    /// </summary>
    private static string RecoveryKitCodec_KitDeclaresByteBodyBound => Get(nameof(RecoveryKitCodec_KitDeclaresByteBodyBound));

    /// <summary>
    /// The kit declares a {0}-byte body; the bound is {1} (specifications/recovery-kit §3).
    /// </summary>
    internal static string FormatRecoveryKitCodec_KitDeclaresByteBodyBound(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryKitCodec_KitDeclaresByteBodyBound, arg0, arg1);

    /// <summary>
    /// Kit format version {0} is not supported by this implementation (v1 only).
    /// </summary>
    private static string RecoveryKitCodec_KitFormatVersionNotSupported => Get(nameof(RecoveryKitCodec_KitFormatVersionNotSupported));

    /// <summary>
    /// Kit format version {0} is not supported by this implementation (v1 only).
    /// </summary>
    internal static string FormatRecoveryKitCodec_KitFormatVersionNotSupported(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryKitCodec_KitFormatVersionNotSupported, arg0);

    /// <summary>
    /// A kit is at least {0} bytes; got {1}.
    /// </summary>
    private static string RecoveryKitCodec_KitLeastBytesGot => Get(nameof(RecoveryKitCodec_KitLeastBytesGot));

    /// <summary>
    /// A kit is at least {0} bytes; got {1}.
    /// </summary>
    internal static string FormatRecoveryKitCodec_KitLeastBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryKitCodec_KitLeastBytesGot, arg0, arg1);

    /// <summary>
    /// Not a FallbackPlan recovery kit: the FBPKRKIT magic is absent.
    /// </summary>
    internal static string RecoveryKitCodec_NotFallbackPlanRecoveryKitFBPKRKIT => Get(nameof(RecoveryKitCodec_NotFallbackPlanRecoveryKitFBPKRKIT));

    /// <summary>
    /// repository_id, kdf salt, and issuing device id are 16 bytes each.
    /// </summary>
    internal static string RecoveryKitCodec_RepositoryIdKdfSaltIssuing => Get(nameof(RecoveryKitCodec_RepositoryIdKdfSaltIssuing));

    /// <summary>
    /// A v1 kit body carries exactly 10 keys; got {0} (specifications/recovery-kit §2).
    /// </summary>
    private static string RecoveryKitCodec_VKitBodyCarriesExactly => Get(nameof(RecoveryKitCodec_VKitBodyCarriesExactly));

    /// <summary>
    /// A v1 kit body carries exactly 10 keys; got {0} (specifications/recovery-kit §2).
    /// </summary>
    internal static string FormatRecoveryKitCodec_VKitBodyCarriesExactly(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryKitCodec_VKitBodyCarriesExactly, arg0);

    /// <summary>
    /// Line {0}: the line check does not verify — a transcription error on this line (specifications/recovery-kit §4).
    /// </summary>
    private static string RecoveryKitText_LineLineCheckDoesNot => Get(nameof(RecoveryKitText_LineLineCheckDoesNot));

    /// <summary>
    /// Line {0}: the line check does not verify — a transcription error on this line (specifications/recovery-kit §4).
    /// </summary>
    internal static string FormatRecoveryKitText_LineLineCheckDoesNot(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryKitText_LineLineCheckDoesNot, arg0);

    /// <summary>
    /// Line {0}: too short to carry payload and check.
    /// </summary>
    private static string RecoveryKitText_LineTooShortCarryPayload => Get(nameof(RecoveryKitText_LineTooShortCarryPayload));

    /// <summary>
    /// Line {0}: too short to carry payload and check.
    /// </summary>
    internal static string FormatRecoveryKitText_LineTooShortCarryPayload(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RecoveryKitText_LineTooShortCarryPayload, arg0);

    /// <summary>
    /// No payload lines found — not a recovery-kit text form.
    /// </summary>
    internal static string RecoveryKitText_NoPayloadLinesFound => Get(nameof(RecoveryKitText_NoPayloadLinesFound));

    /// <summary>
    /// The payload does not decode as base32 (specifications/recovery-kit §4).
    /// </summary>
    internal static string RecoveryKitText_PayloadDoesNotDecodeAs => Get(nameof(RecoveryKitText_PayloadDoesNotDecodeAs));

    /// <summary>
    /// The descriptor body is {0} bytes; the limit is {1} (specification 01 §3.1).
    /// </summary>
    private static string RepositoryDescriptorCodec_DescriptorBodyBytesLimit => Get(nameof(RepositoryDescriptorCodec_DescriptorBodyBytesLimit));

    /// <summary>
    /// The descriptor body is {0} bytes; the limit is {1} (specification 01 §3.1).
    /// </summary>
    internal static string FormatRepositoryDescriptorCodec_DescriptorBodyBytesLimit(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryDescriptorCodec_DescriptorBodyBytesLimit, arg0, arg1);

    /// <summary>
    /// The KDF salt is exactly 16 bytes (specification 01 §3.3).
    /// </summary>
    internal static string RepositoryDescriptorCodec_KDFSaltExactlyBytes => Get(nameof(RepositoryDescriptorCodec_KDFSaltExactlyBytes));

    /// <summary>
    /// kdf_parameters carries {0} keys; specification 01 §3.3 defines exactly 5.
    /// </summary>
    private static string RepositoryDescriptorCodec_KdfParametersCarriesKeysSpecification => Get(nameof(RepositoryDescriptorCodec_KdfParametersCarriesKeysSpecification));

    /// <summary>
    /// kdf_parameters carries {0} keys; specification 01 §3.3 defines exactly 5.
    /// </summary>
    internal static string FormatRepositoryDescriptorCodec_KdfParametersCarriesKeysSpecification(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryDescriptorCodec_KdfParametersCarriesKeysSpecification, arg0);

    /// <summary>
    /// kdf_parameters carries an unknown key (specification 01 §3.3).
    /// </summary>
    internal static string RepositoryDescriptorCodec_KdfParametersCarriesUnknownKey => Get(nameof(RepositoryDescriptorCodec_KdfParametersCarriesUnknownKey));

    /// <summary>
    /// kdf_parameters omits the salt (specification 01 §3.3).
    /// </summary>
    internal static string RepositoryDescriptorCodec_KdfParametersOmitsSalt => Get(nameof(RepositoryDescriptorCodec_KdfParametersOmitsSalt));

    /// <summary>
    /// kdf_profile 0x{0:x4} is not Argon2id (0x0001); refused, not guessed (specification 00 §3).
    /// </summary>
    private static string RepositoryDescriptorCodec_KdfProfileXNotArgon => Get(nameof(RepositoryDescriptorCodec_KdfProfileXNotArgon));

    /// <summary>
    /// kdf_profile 0x{0:x4} is not Argon2id (0x0001); refused, not guessed (specification 00 §3).
    /// </summary>
    internal static string FormatRepositoryDescriptorCodec_KdfProfileXNotArgon(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryDescriptorCodec_KdfProfileXNotArgon, arg0);

    /// <summary>
    /// capture_status {0} is unassigned (specification 06 §6).
    /// </summary>
    private static string SnapshotManifestCodec_CaptureStatusUnassigned => Get(nameof(SnapshotManifestCodec_CaptureStatusUnassigned));

    /// <summary>
    /// capture_status {0} is unassigned (specification 06 §6).
    /// </summary>
    internal static string FormatSnapshotManifestCodec_CaptureStatusUnassigned(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, SnapshotManifestCodec_CaptureStatusUnassigned, arg0);

    /// <summary>
    /// consistency_method {0} is unassigned (specification 06 §6).
    /// </summary>
    private static string SnapshotManifestCodec_ConsistencyMethodUnassigned => Get(nameof(SnapshotManifestCodec_ConsistencyMethodUnassigned));

    /// <summary>
    /// consistency_method {0} is unassigned (specification 06 §6).
    /// </summary>
    internal static string FormatSnapshotManifestCodec_ConsistencyMethodUnassigned(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, SnapshotManifestCodec_ConsistencyMethodUnassigned, arg0);

    /// <summary>
    /// snapshot_id, device_id, and backup_set_id are 16 bytes each (specification 06 §6).
    /// </summary>
    internal static string SnapshotManifestCodec_SnapshotIdDeviceIdBackup => Get(nameof(SnapshotManifestCodec_SnapshotIdDeviceIdBackup));

    /// <summary>
    /// The snapshot manifest carries an unknown key; specification 06 §6 assigns keys 1-17 only.
    /// </summary>
    internal static string SnapshotManifestCodec_SnapshotManifestCarriesUnknownKey => Get(nameof(SnapshotManifestCodec_SnapshotManifestCarriesUnknownKey));

    /// <summary>
    /// The snapshot manifest is not canonical CBOR: {0}
    /// </summary>
    private static string SnapshotManifestCodec_SnapshotManifestNotCanonicalCBOR => Get(nameof(SnapshotManifestCodec_SnapshotManifestNotCanonicalCBOR));

    /// <summary>
    /// The snapshot manifest is not canonical CBOR: {0}
    /// </summary>
    internal static string FormatSnapshotManifestCodec_SnapshotManifestNotCanonicalCBOR(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, SnapshotManifestCodec_SnapshotManifestNotCanonicalCBOR, arg0);

    /// <summary>
    /// The snapshot manifest omits a mandatory key (specification 06 §6).
    /// </summary>
    internal static string SnapshotManifestCodec_SnapshotManifestOmitsMandatoryKey => Get(nameof(SnapshotManifestCodec_SnapshotManifestOmitsMandatoryKey));

    /// <summary>
    /// A snapshot signature is exactly 64 bytes (specification 06 §6).
    /// </summary>
    internal static string SnapshotManifestCodec_SnapshotSignatureExactlyBytes => Get(nameof(SnapshotManifestCodec_SnapshotSignatureExactlyBytes));

    /// <summary>
    /// source_filesystem carries an unknown key (ADR-0022 §Decision 6; ADR-0026 §Decision 7).
    /// </summary>
    internal static string SnapshotManifestCodec_SourceFilesystemCarriesUnknownKey => Get(nameof(SnapshotManifestCodec_SourceFilesystemCarriesUnknownKey));

    /// <summary>
    /// source_filesystem omits a mandatory key (ADR-0022 §Decision 6).
    /// </summary>
    internal static string SnapshotManifestCodec_SourceFilesystemOmitsMandatoryKey => Get(nameof(SnapshotManifestCodec_SourceFilesystemOmitsMandatoryKey));

    /// <summary>
    /// A snapshot identifier is exactly 16 bytes.
    /// </summary>
    internal static string SourceIdentityHintCodec_SnapshotIdentifierExactlyBytes => Get(nameof(SourceIdentityHintCodec_SnapshotIdentifierExactlyBytes));

    /// <summary>
    /// A source-identity hint carries the capture time at key 5.
    /// </summary>
    internal static string SourceIdentityHintCodec_SourceIdentityHintCarriesCapture => Get(nameof(SourceIdentityHintCodec_SourceIdentityHintCarriesCapture));

    /// <summary>
    /// A source-identity hint carries exactly keys 1-5 (specification 06 §11).
    /// </summary>
    internal static string SourceIdentityHintCodec_SourceIdentityHintCarriesExactly => Get(nameof(SourceIdentityHintCodec_SourceIdentityHintCarriesExactly));

    /// <summary>
    /// A source-identity hint carries the object identifier at key 4.
    /// </summary>
    internal static string SourceIdentityHintCodec_SourceIdentityHintCarriesObject => Get(nameof(SourceIdentityHintCodec_SourceIdentityHintCarriesObject));

    /// <summary>
    /// A source-identity hint carries the snapshot identifier at key 3.
    /// </summary>
    internal static string SourceIdentityHintCodec_SourceIdentityHintCarriesSnapshot => Get(nameof(SourceIdentityHintCodec_SourceIdentityHintCarriesSnapshot));

    /// <summary>
    /// A source-identity hint carries the source key at key 2.
    /// </summary>
    internal static string SourceIdentityHintCodec_SourceIdentityHintCarriesSource => Get(nameof(SourceIdentityHintCodec_SourceIdentityHintCarriesSource));

    /// <summary>
    /// The source-identity hint is not canonical CBOR: {0}
    /// </summary>
    private static string SourceIdentityHintCodec_SourceIdentityHintNotCanonical => Get(nameof(SourceIdentityHintCodec_SourceIdentityHintNotCanonical));

    /// <summary>
    /// The source-identity hint is not canonical CBOR: {0}
    /// </summary>
    internal static string FormatSourceIdentityHintCodec_SourceIdentityHintNotCanonical(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, SourceIdentityHintCodec_SourceIdentityHintNotCanonical, arg0);

    /// <summary>
    /// A source-identity hint opens with key 1, the schema version.
    /// </summary>
    internal static string SourceIdentityHintCodec_SourceIdentityHintOpensWith => Get(nameof(SourceIdentityHintCodec_SourceIdentityHintOpensWith));

    /// <summary>
    /// Source-identity schema {0} is unknown; this reader implements {1}.
    /// </summary>
    private static string SourceIdentityHintCodec_SourceIdentitySchemaUnknownReader => Get(nameof(SourceIdentityHintCodec_SourceIdentitySchemaUnknownReader));

    /// <summary>
    /// Source-identity schema {0} is unknown; this reader implements {1}.
    /// </summary>
    internal static string FormatSourceIdentityHintCodec_SourceIdentitySchemaUnknownReader(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, SourceIdentityHintCodec_SourceIdentitySchemaUnknownReader, arg0, arg1);

    /// <summary>
    /// A source key is exactly {0} bytes.
    /// </summary>
    private static string SourceIdentityHintCodec_SourceKeyExactlyBytes => Get(nameof(SourceIdentityHintCodec_SourceKeyExactlyBytes));

    /// <summary>
    /// A source key is exactly {0} bytes.
    /// </summary>
    internal static string FormatSourceIdentityHintCodec_SourceKeyExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, SourceIdentityHintCodec_SourceKeyExactlyBytes, arg0);

    /// <summary>
    /// The blob salt is exactly {0} bytes.
    /// </summary>
    private static string StandaloneRecordFraming_BlobSaltExactlyBytes => Get(nameof(StandaloneRecordFraming_BlobSaltExactlyBytes));

    /// <summary>
    /// The blob salt is exactly {0} bytes.
    /// </summary>
    internal static string FormatStandaloneRecordFraming_BlobSaltExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, StandaloneRecordFraming_BlobSaltExactlyBytes, arg0);

    /// <summary>
    /// The destination must hold {0} bytes.
    /// </summary>
    private static string StandaloneRecordFraming_DestinationMustHoldBytes => Get(nameof(StandaloneRecordFraming_DestinationMustHoldBytes));

    /// <summary>
    /// The destination must hold {0} bytes.
    /// </summary>
    internal static string FormatStandaloneRecordFraming_DestinationMustHoldBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, StandaloneRecordFraming_DestinationMustHoldBytes, arg0);

    /// <summary>
    /// Not a FallbackPlan standalone metadata record — the FBPKSREC magic is absent.
    /// </summary>
    internal static string StandaloneRecordFraming_NotFallbackPlanStandaloneMetadataRecord => Get(nameof(StandaloneRecordFraming_NotFallbackPlanStandaloneMetadataRecord));

    /// <summary>
    /// The object is {0} bytes; the header declares {1} — data beyond the sealed layout is a damage finding.
    /// </summary>
    private static string StandaloneRecordFraming_ObjectBytesHeaderDeclares => Get(nameof(StandaloneRecordFraming_ObjectBytesHeaderDeclares));

    /// <summary>
    /// The object is {0} bytes; the header declares {1} — data beyond the sealed layout is a damage finding.
    /// </summary>
    internal static string FormatStandaloneRecordFraming_ObjectBytesHeaderDeclares(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, StandaloneRecordFraming_ObjectBytesHeaderDeclares, arg0, arg1);

    /// <summary>
    /// A standalone record is at least {0} bytes; got {1} (ADR-0022).
    /// </summary>
    private static string StandaloneRecordFraming_StandaloneRecordLeastBytesGot => Get(nameof(StandaloneRecordFraming_StandaloneRecordLeastBytesGot));

    /// <summary>
    /// A standalone record is at least {0} bytes; got {1} (ADR-0022).
    /// </summary>
    internal static string FormatStandaloneRecordFraming_StandaloneRecordLeastBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, StandaloneRecordFraming_StandaloneRecordLeastBytesGot, arg0, arg1);

    /// <summary>
    /// A standalone record's ordinal is exactly 0; got {0} (ADR-0022 §Decision 1).
    /// </summary>
    private static string StandaloneRecordFraming_StandaloneRecordSOrdinalExactly => Get(nameof(StandaloneRecordFraming_StandaloneRecordSOrdinalExactly));

    /// <summary>
    /// A standalone record's ordinal is exactly 0; got {0} (ADR-0022 §Decision 1).
    /// </summary>
    internal static string FormatStandaloneRecordFraming_StandaloneRecordSOrdinalExactly(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, StandaloneRecordFraming_StandaloneRecordSOrdinalExactly, arg0);

    /// <summary>
    /// stored_length {0} exceeds the 16 MiB metadata bound (specification 00 §8) — refused before allocation.
    /// </summary>
    private static string StandaloneRecordFraming_StoredLengthExceedsMiBMetadata => Get(nameof(StandaloneRecordFraming_StoredLengthExceedsMiBMetadata));

    /// <summary>
    /// stored_length {0} exceeds the 16 MiB metadata bound (specification 00 §8) — refused before allocation.
    /// </summary>
    internal static string FormatStandaloneRecordFraming_StoredLengthExceedsMiBMetadata(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, StandaloneRecordFraming_StoredLengthExceedsMiBMetadata, arg0);

    /// <summary>
    /// Continuations MUST NOT carry metadata, name, or name_normalisation (specification 06 §9).
    /// </summary>
    internal static string TreeChain_ContinuationsMUSTNOTCarryMetadata => Get(nameof(TreeChain_ContinuationsMUSTNOTCarryMetadata));

    /// <summary>
    /// Each manifest except the last carries continuation; the last omits it (specification 06 §9).
    /// </summary>
    internal static string TreeChain_EachManifestExceptLastCarries => Get(nameof(TreeChain_EachManifestExceptLastCarries));

    /// <summary>
    /// Every entry in a manifest MUST sort strictly after every entry in its predecessor (specification 06 §9).
    /// </summary>
    internal static string TreeChain_EveryEntryManifestMUSTSort => Get(nameof(TreeChain_EveryEntryManifestMUSTSort));

    /// <summary>
    /// The first manifest of a chain carries name, name_normalisation, and metadata (specification 06 §9).
    /// </summary>
    internal static string TreeChain_FirstManifestChainCarriesName => Get(nameof(TreeChain_FirstManifestChainCarriesName));

    /// <summary>
    /// A tree chain has at least one manifest (specification 06 §9).
    /// </summary>
    internal static string TreeChain_TreeChainLeastOneManifest => Get(nameof(TreeChain_TreeChainLeastOneManifest));

    /// <summary>
    /// The encoded tree manifest is {0} bytes; a directory this large MUST shard (specification 06 §9).
    /// </summary>
    private static string TreeManifestCodec_EncodedTreeManifestBytesDirectory => Get(nameof(TreeManifestCodec_EncodedTreeManifestBytesDirectory));

    /// <summary>
    /// The encoded tree manifest is {0} bytes; a directory this large MUST shard (specification 06 §9).
    /// </summary>
    internal static string FormatTreeManifestCodec_EncodedTreeManifestBytesDirectory(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, TreeManifestCodec_EncodedTreeManifestBytesDirectory, arg0);

    /// <summary>
    /// metadata, name, and name_normalisation ride together on the first manifest of a chain and are absent from continuations (specification 06 §9).
    /// </summary>
    internal static string TreeManifestCodec_MetadataNameNameNormalisationRide => Get(nameof(TreeManifestCodec_MetadataNameNameNormalisationRide));

    /// <summary>
    /// Tree entries MUST be sorted by the raw bytes of name, ascending (specification 06 §5).
    /// </summary>
    internal static string TreeManifestCodec_TreeEntriesMUSTSortedRaw => Get(nameof(TreeManifestCodec_TreeEntriesMUSTSortedRaw));

    /// <summary>
    /// A tree entry is exactly three elements; got {0} (specification 06 §5).
    /// </summary>
    private static string TreeManifestCodec_TreeEntryExactlyThreeElements => Get(nameof(TreeManifestCodec_TreeEntryExactlyThreeElements));

    /// <summary>
    /// A tree entry is exactly three elements; got {0} (specification 06 §5).
    /// </summary>
    internal static string FormatTreeManifestCodec_TreeEntryExactlyThreeElements(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, TreeManifestCodec_TreeEntryExactlyThreeElements, arg0);

    /// <summary>
    /// A tree MUST NOT contain two entries with the same name bytes (specification 06 §5).
    /// </summary>
    internal static string TreeManifestCodec_TreeMUSTNOTContainTwo => Get(nameof(TreeManifestCodec_TreeMUSTNOTContainTwo));

    /// <summary>
    /// The tree manifest carries an unknown key; specification 06 §5 assigns keys 1-5 only.
    /// </summary>
    internal static string TreeManifestCodec_TreeManifestCarriesUnknownKey => Get(nameof(TreeManifestCodec_TreeManifestCarriesUnknownKey));

    /// <summary>
    /// The tree manifest is not canonical CBOR: {0}
    /// </summary>
    private static string TreeManifestCodec_TreeManifestNotCanonicalCBOR => Get(nameof(TreeManifestCodec_TreeManifestNotCanonicalCBOR));

    /// <summary>
    /// The tree manifest is not canonical CBOR: {0}
    /// </summary>
    internal static string FormatTreeManifestCodec_TreeManifestNotCanonicalCBOR(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, TreeManifestCodec_TreeManifestNotCanonicalCBOR, arg0);

    /// <summary>
    /// The tree manifest omits its entries (specification 06 §5).
    /// </summary>
    internal static string TreeManifestCodec_TreeManifestOmitsEntries => Get(nameof(TreeManifestCodec_TreeManifestOmitsEntries));

    /// <summary>
    /// The destination must hold at least the plaintext length — a stored-compressed frame is never larger.
    /// </summary>
    internal static string ZstdSegmentCodec_DestinationMustHoldLeastPlaintext => Get(nameof(ZstdSegmentCodec_DestinationMustHoldLeastPlaintext));

    /// <summary>
    /// The maximum segment size is unset.
    /// </summary>
    internal static string ZstdSegmentCodec_MaximumSegmentSizeUnset => Get(nameof(ZstdSegmentCodec_MaximumSegmentSizeUnset));

    /// <summary>
    /// The frame produced {0} bytes; the record's logical length is {1} (specification 10 §4.1).
    /// </summary>
    private static string ZstdSegmentDecompressor_FrameProducedBytesRecordS => Get(nameof(ZstdSegmentDecompressor_FrameProducedBytesRecordS));

    /// <summary>
    /// The frame produced {0} bytes; the record's logical length is {1} (specification 10 §4.1).
    /// </summary>
    internal static string FormatZstdSegmentDecompressor_FrameProducedBytesRecordS(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, ZstdSegmentDecompressor_FrameProducedBytesRecordS, arg0, arg1);

    /// <summary>
    /// Stored bytes are not one standard Zstandard frame producing exactly the record's logical length (specification 10 §4.1).
    /// </summary>
    internal static string ZstdSegmentDecompressor_StoredBytesNotOneStandard => Get(nameof(ZstdSegmentDecompressor_StoredBytesNotOneStandard));

    /// <summary>
    /// A tombstone signature is exactly 64 bytes.
    /// </summary>
    internal static string TombstoneCodec_SignatureExactlyBytes => Get(nameof(TombstoneCodec_SignatureExactlyBytes));

    /// <summary>
    /// A tombstone is not canonical CBOR: {0}
    /// </summary>
    private static string TombstoneCodec_NotCanonicalCbor => Get(nameof(TombstoneCodec_NotCanonicalCbor));

    /// <summary>
    /// A tombstone is not canonical CBOR: {0}
    /// </summary>
    internal static string FormatTombstoneCodec_NotCanonicalCbor(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, TombstoneCodec_NotCanonicalCbor, arg0);

    /// <summary>
    /// Tombstone schema version {0} is not supported; this build reads version 1.
    /// </summary>
    private static string TombstoneCodec_SchemaVersionUnsupported => Get(nameof(TombstoneCodec_SchemaVersionUnsupported));

    /// <summary>
    /// Tombstone schema version {0} is not supported; this build reads version 1.
    /// </summary>
    internal static string FormatTombstoneCodec_SchemaVersionUnsupported(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, TombstoneCodec_SchemaVersionUnsupported, arg0);

    /// <summary>
    /// A tombstone for object type {0} carries a {1}-byte identifier; {2} bytes are required (11 §3.1).
    /// </summary>
    private static string TombstoneCodec_ObjectIdWidthMismatch => Get(nameof(TombstoneCodec_ObjectIdWidthMismatch));

    /// <summary>
    /// A tombstone for object type {0} carries a {1}-byte identifier; {2} bytes are required (11 §3.1).
    /// </summary>
    internal static string FormatTombstoneCodec_ObjectIdWidthMismatch(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, TombstoneCodec_ObjectIdWidthMismatch, arg0, arg1, arg2);

    /// <summary>
    /// Tombstone reason {0} is not in the closed vocabulary (11 §3).
    /// </summary>
    private static string TombstoneCodec_ReasonOutsideVocabulary => Get(nameof(TombstoneCodec_ReasonOutsideVocabulary));

    /// <summary>
    /// Tombstone reason {0} is not in the closed vocabulary (11 §3).
    /// </summary>
    internal static string FormatTombstoneCodec_ReasonOutsideVocabulary(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, TombstoneCodec_ReasonOutsideVocabulary, arg0);

    /// <summary>
    /// A tombstone omits required key {0} (11 §3).
    /// </summary>
    private static string TombstoneCodec_RequiredKeyMissing => Get(nameof(TombstoneCodec_RequiredKeyMissing));

    /// <summary>
    /// A tombstone omits required key {0} (11 §3).
    /// </summary>
    internal static string FormatTombstoneCodec_RequiredKeyMissing(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, TombstoneCodec_RequiredKeyMissing, arg0);

    /// <summary>
    /// A write-only (format v2) kit carries the 32-byte sealing public key and no key object; every actual key re-derives from the passphrase (ADR-0042).
    /// </summary>
    internal static string RecoveryKitCodec_WriteOnlyKitShape => Get(nameof(RecoveryKitCodec_WriteOnlyKitShape));
}
