// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Filesystem.Local.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Filesystem.Local.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Filesystem.Local.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// Alternate data streams exist on Windows only.
    /// </summary>
    internal static string LocalFileSystemSource_AlternateDataStreamsExistWindows => Get(nameof(LocalFileSystemSource_AlternateDataStreamsExistWindows));

    /// <summary>
    /// '{0}' is not a scannable directory.
    /// </summary>
    private static string LocalFileSystemSource_NotScannableDirectory => Get(nameof(LocalFileSystemSource_NotScannableDirectory));

    /// <summary>
    /// '{0}' is not a scannable directory.
    /// </summary>
    internal static string FormatLocalFileSystemSource_NotScannableDirectory(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, LocalFileSystemSource_NotScannableDirectory, arg0);
}
