// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Repository.Index.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Repository.Index.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Repository.Index.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// The checkpoint carries an entry in shard {0} but does not enumerate it in shard_set (specification 07 §8).
    /// </summary>
    private static string CheckpointCodec_CheckpointCarriesEntryShardBut => Get(nameof(CheckpointCodec_CheckpointCarriesEntryShardBut));

    /// <summary>
    /// The checkpoint carries an entry in shard {0} but does not enumerate it in shard_set (specification 07 §8).
    /// </summary>
    internal static string FormatCheckpointCodec_CheckpointCarriesEntryShardBut(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CheckpointCodec_CheckpointCarriesEntryShardBut, arg0);

    /// <summary>
    /// The checkpoint carries an unknown key; specification 07 §5 assigns keys 1-9 only.
    /// </summary>
    internal static string CheckpointCodec_CheckpointCarriesUnknownKeySpecification => Get(nameof(CheckpointCodec_CheckpointCarriesUnknownKeySpecification));

    /// <summary>
    /// The checkpoint is not canonical CBOR: {0}
    /// </summary>
    private static string CheckpointCodec_CheckpointNotCanonicalCBOR => Get(nameof(CheckpointCodec_CheckpointNotCanonicalCBOR));

    /// <summary>
    /// The checkpoint is not canonical CBOR: {0}
    /// </summary>
    internal static string FormatCheckpointCodec_CheckpointNotCanonicalCBOR(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, CheckpointCodec_CheckpointNotCanonicalCBOR, arg0);

    /// <summary>
    /// The checkpoint omits a mandatory key (specification 07 §5).
    /// </summary>
    internal static string CheckpointCodec_CheckpointOmitsMandatoryKey => Get(nameof(CheckpointCodec_CheckpointOmitsMandatoryKey));

    /// <summary>
    /// A checkpoint signature is exactly 64 bytes (specification 07 §5).
    /// </summary>
    internal static string CheckpointCodec_CheckpointSignatureExactlyBytes => Get(nameof(CheckpointCodec_CheckpointSignatureExactlyBytes));

    /// <summary>
    /// shard_set and shard_hashes are positionally parallel and must agree in length (specification 07 §5).
    /// </summary>
    internal static string CheckpointCodec_ShardSetShardHashesPositionally => Get(nameof(CheckpointCodec_ShardSetShardHashesPositionally));

    /// <summary>
    /// A writer watermark is exactly [writer_id, highest_sequence] (specification 07 §5 key 3).
    /// </summary>
    internal static string CheckpointCodec_WriterWatermarkExactlyWriterId => Get(nameof(CheckpointCodec_WriterWatermarkExactlyWriterId));

    /// <summary>
    /// A covered blob digest is a 32-byte SHA-256 (specification 07 §2.2).
    /// </summary>
    internal static string IndexDeltaCodec_CoveredBlobDigestByteSHA => Get(nameof(IndexDeltaCodec_CoveredBlobDigestByteSHA));

    /// <summary>
    /// covered_blob_digests has {0} elements against {1} covered blobs; the arrays are parallel or absent (specification 07 §2.2).
    /// </summary>
    private static string IndexDeltaCodec_CoveredBlobDigestsElementsAgainst => Get(nameof(IndexDeltaCodec_CoveredBlobDigestsElementsAgainst));

    /// <summary>
    /// covered_blob_digests has {0} elements against {1} covered blobs; the arrays are parallel or absent (specification 07 §2.2).
    /// </summary>
    internal static string FormatIndexDeltaCodec_CoveredBlobDigestsElementsAgainst(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, IndexDeltaCodec_CoveredBlobDigestsElementsAgainst, arg0, arg1);

    /// <summary>
    /// The delta carries an unknown key; specification 07 §2 assigns keys 1-10 only.
    /// </summary>
    internal static string IndexDeltaCodec_DeltaCarriesUnknownKeySpecification => Get(nameof(IndexDeltaCodec_DeltaCarriesUnknownKeySpecification));

    /// <summary>
    /// The delta declares shard {0} but carries an entry in shard {1} (ADR-0022 §Decision 4).
    /// </summary>
    private static string IndexDeltaCodec_DeltaDeclaresShardButCarries => Get(nameof(IndexDeltaCodec_DeltaDeclaresShardButCarries));

    /// <summary>
    /// The delta declares shard {0} but carries an entry in shard {1} (ADR-0022 §Decision 4).
    /// </summary>
    internal static string FormatIndexDeltaCodec_DeltaDeclaresShardButCarries(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, IndexDeltaCodec_DeltaDeclaresShardButCarries, arg0, arg1);

    /// <summary>
    /// The delta is not canonical CBOR: {0}
    /// </summary>
    private static string IndexDeltaCodec_DeltaNotCanonicalCBOR => Get(nameof(IndexDeltaCodec_DeltaNotCanonicalCBOR));

    /// <summary>
    /// The delta is not canonical CBOR: {0}
    /// </summary>
    internal static string FormatIndexDeltaCodec_DeltaNotCanonicalCBOR(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, IndexDeltaCodec_DeltaNotCanonicalCBOR, arg0);

    /// <summary>
    /// The delta omits a mandatory key (specification 07 §2).
    /// </summary>
    internal static string IndexDeltaCodec_DeltaOmitsMandatoryKey => Get(nameof(IndexDeltaCodec_DeltaOmitsMandatoryKey));

    /// <summary>
    /// A delta signature is exactly 64 bytes (specification 07 §2).
    /// </summary>
    internal static string IndexDeltaCodec_DeltaSignatureExactlyBytes => Get(nameof(IndexDeltaCodec_DeltaSignatureExactlyBytes));

    /// <summary>
    /// entry_type {0} is unassigned (specification 07 §2.1).
    /// </summary>
    private static string IndexDeltaCodec_EntryTypeUnassigned => Get(nameof(IndexDeltaCodec_EntryTypeUnassigned));

    /// <summary>
    /// entry_type {0} is unassigned (specification 07 §2.1).
    /// </summary>
    internal static string FormatIndexDeltaCodec_EntryTypeUnassigned(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, IndexDeltaCodec_EntryTypeUnassigned, arg0);

    /// <summary>
    /// An index entry is exactly six elements; got {0} (specification 07 §2.1).
    /// </summary>
    private static string IndexDeltaCodec_IndexEntryExactlySixElements => Get(nameof(IndexDeltaCodec_IndexEntryExactlySixElements));

    /// <summary>
    /// An index entry is exactly six elements; got {0} (specification 07 §2.1).
    /// </summary>
    internal static string FormatIndexDeltaCodec_IndexEntryExactlySixElements(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, IndexDeltaCodec_IndexEntryExactlySixElements, arg0);

    /// <summary>
    /// A void delta is well-formed and signed with empty entries and empty covered_blob_ids (specification 07 §4).
    /// </summary>
    internal static string IndexDeltaCodec_VoidDeltaWellFormedSigned => Get(nameof(IndexDeltaCodec_VoidDeltaWellFormedSigned));

    /// <summary>
    /// is_void is present and true only for a void delta (specification 07 §2 key 8).
    /// </summary>
    internal static string IndexDeltaCodec_VoidPresentTrueOnlyVoid => Get(nameof(IndexDeltaCodec_VoidPresentTrueOnlyVoid));

    /// <summary>
    /// Generation {0} exceeds the key hierarchy's u32 generation space (specification 03 §4).
    /// </summary>
    private static string IndexPublisher_GenerationExceedsKeyHierarchyS => Get(nameof(IndexPublisher_GenerationExceedsKeyHierarchyS));

    /// <summary>
    /// Generation {0} exceeds the key hierarchy's u32 generation space (specification 03 §4).
    /// </summary>
    internal static string FormatIndexPublisher_GenerationExceedsKeyHierarchyS(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, IndexPublisher_GenerationExceedsKeyHierarchyS, arg0);

    /// <summary>
    /// The store refused index object '{0}' with a failed precondition.
    /// </summary>
    private static string IndexPublisher_StoreRefusedIndexObjectWith => Get(nameof(IndexPublisher_StoreRefusedIndexObjectWith));

    /// <summary>
    /// The store refused index object '{0}' with a failed precondition.
    /// </summary>
    internal static string FormatIndexPublisher_StoreRefusedIndexObjectWith(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, IndexPublisher_StoreRefusedIndexObjectWith, arg0);

    /// <summary>
    /// The store refused journal record {0} with a failed precondition.
    /// </summary>
    private static string JournalPublisher_StoreRefusedJournalRecordWith => Get(nameof(JournalPublisher_StoreRefusedJournalRecordWith));

    /// <summary>
    /// The store refused journal record {0} with a failed precondition.
    /// </summary>
    internal static string FormatJournalPublisher_StoreRefusedJournalRecordWith(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, JournalPublisher_StoreRefusedJournalRecordWith, arg0);

    /// <summary>
    /// The store already holds a different journal record at sequence {0}: this writer's sequence state has regressed (specification 08 §2). The publication is refused while the source data still exists.
    /// </summary>
    private static string JournalStore_StoreHeldDifferentRecordAtSequence => Get(nameof(JournalStore_StoreHeldDifferentRecordAtSequence));

    /// <summary>
    /// The store already holds a different journal record at sequence {0}: this writer's sequence state has regressed (specification 08 §2). The publication is refused while the source data still exists.
    /// </summary>
    internal static string FormatJournalStore_StoreHeldDifferentRecordAtSequence(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, JournalStore_StoreHeldDifferentRecordAtSequence, arg0);

    /// <summary>
    /// The audit payload carries an unknown key (specification 08 §6).
    /// </summary>
    internal static string JournalRecordCodec_AuditPayloadCarriesUnknownKey => Get(nameof(JournalRecordCodec_AuditPayloadCarriesUnknownKey));

    /// <summary>
    /// The audit payload is incomplete or carries an unassigned action (specification 08 §6; ADR-0022 §Decision 6).
    /// </summary>
    internal static string JournalRecordCodec_AuditPayloadIncompleteCarriesUnassigned => Get(nameof(JournalRecordCodec_AuditPayloadIncompleteCarriesUnassigned));

    /// <summary>
    /// backup_set_id is exactly 16 bytes (specification 08 §3).
    /// </summary>
    internal static string JournalRecordCodec_BackupSetIdExactlyBytes => Get(nameof(JournalRecordCodec_BackupSetIdExactlyBytes));

    /// <summary>
    /// The intent-extension payload carries an unknown key (specification 08 §4).
    /// </summary>
    internal static string JournalRecordCodec_IntentExtensionPayloadCarriesUnknown => Get(nameof(JournalRecordCodec_IntentExtensionPayloadCarriesUnknown));

    /// <summary>
    /// The intent-extension payload is incomplete (specification 08 §4).
    /// </summary>
    internal static string JournalRecordCodec_IntentExtensionPayloadIncomplete => Get(nameof(JournalRecordCodec_IntentExtensionPayloadIncomplete));

    /// <summary>
    /// The intent-retirement payload carries an unknown key (specification 08 §5).
    /// </summary>
    internal static string JournalRecordCodec_IntentRetirementPayloadCarriesUnknown => Get(nameof(JournalRecordCodec_IntentRetirementPayloadCarriesUnknown));

    /// <summary>
    /// The intent-retirement payload is incomplete or carries an unassigned outcome (specification 08 §5).
    /// </summary>
    internal static string JournalRecordCodec_IntentRetirementPayloadIncompleteCarries => Get(nameof(JournalRecordCodec_IntentRetirementPayloadIncompleteCarries));

    /// <summary>
    /// The journal record carries an unknown key; specification 08 §2 assigns keys 1-6 only.
    /// </summary>
    internal static string JournalRecordCodec_JournalRecordCarriesUnknownKey => Get(nameof(JournalRecordCodec_JournalRecordCarriesUnknownKey));

    /// <summary>
    /// The journal record is not canonical CBOR: {0}
    /// </summary>
    private static string JournalRecordCodec_JournalRecordNotCanonicalCBOR => Get(nameof(JournalRecordCodec_JournalRecordNotCanonicalCBOR));

    /// <summary>
    /// The journal record is not canonical CBOR: {0}
    /// </summary>
    internal static string FormatJournalRecordCodec_JournalRecordNotCanonicalCBOR(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, JournalRecordCodec_JournalRecordNotCanonicalCBOR, arg0);

    /// <summary>
    /// The journal record omits a mandatory key (specification 08 §2).
    /// </summary>
    internal static string JournalRecordCodec_JournalRecordOmitsMandatoryKey => Get(nameof(JournalRecordCodec_JournalRecordOmitsMandatoryKey));

    /// <summary>
    /// A journal signature is exactly 64 bytes (specification 08 §2).
    /// </summary>
    internal static string JournalRecordCodec_JournalSignatureExactlyBytes => Get(nameof(JournalRecordCodec_JournalSignatureExactlyBytes));

    /// <summary>
    /// The payload precedes record_kind — not canonical (00 §4.1).
    /// </summary>
    internal static string JournalRecordCodec_PayloadPrecedesRecordKind => Get(nameof(JournalRecordCodec_PayloadPrecedesRecordKind));

    /// <summary>
    /// record_kind {0} does not match its payload shape (specification 08 §2).
    /// </summary>
    private static string JournalRecordCodec_RecordKindDoesNotMatch => Get(nameof(JournalRecordCodec_RecordKindDoesNotMatch));

    /// <summary>
    /// record_kind {0} does not match its payload shape (specification 08 §2).
    /// </summary>
    internal static string FormatJournalRecordCodec_RecordKindDoesNotMatch(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, JournalRecordCodec_RecordKindDoesNotMatch, arg0);

    /// <summary>
    /// record_kind {0} is unassigned (specification 08 §2).
    /// </summary>
    private static string JournalRecordCodec_RecordKindUnassigned => Get(nameof(JournalRecordCodec_RecordKindUnassigned));

    /// <summary>
    /// record_kind {0} is unassigned (specification 08 §2).
    /// </summary>
    internal static string FormatJournalRecordCodec_RecordKindUnassigned(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, JournalRecordCodec_RecordKindUnassigned, arg0);

    /// <summary>
    /// Unknown journal payload shape.
    /// </summary>
    internal static string JournalRecordCodec_UnknownJournalPayloadShape => Get(nameof(JournalRecordCodec_UnknownJournalPayloadShape));

    /// <summary>
    /// Unknown record kind.
    /// </summary>
    internal static string JournalRecordCodec_UnknownRecordKind => Get(nameof(JournalRecordCodec_UnknownRecordKind));

    /// <summary>
    /// The write-intent payload carries an unknown key (specification 08 §3).
    /// </summary>
    internal static string JournalRecordCodec_WriteIntentPayloadCarriesUnknown => Get(nameof(JournalRecordCodec_WriteIntentPayloadCarriesUnknown));

    /// <summary>
    /// The write-intent payload is incomplete or carries an unassigned purpose (specification 08 §3).
    /// </summary>
    internal static string JournalRecordCodec_WriteIntentPayloadIncompleteCarries => Get(nameof(JournalRecordCodec_WriteIntentPayloadIncompleteCarries));
}
