// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Repository.Crypto.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Repository.Crypto.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Repository.Crypto.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// The blob salt is exactly {0} bytes.
    /// </summary>
    private static string BlobKeyDeriver_BlobSaltExactlyBytes => Get(nameof(BlobKeyDeriver_BlobSaltExactlyBytes));

    /// <summary>
    /// The blob salt is exactly {0} bytes.
    /// </summary>
    internal static string FormatBlobKeyDeriver_BlobSaltExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobKeyDeriver_BlobSaltExactlyBytes, arg0);

    /// <summary>
    /// The class key is exactly 32 bytes.
    /// </summary>
    internal static string BlobKeyDeriver_ClassKeyExactlyBytes => Get(nameof(BlobKeyDeriver_ClassKeyExactlyBytes));

    /// <summary>
    /// The destination is exactly {0} bytes.
    /// </summary>
    private static string BlobKeyDeriver_DestinationExactlyBytes => Get(nameof(BlobKeyDeriver_DestinationExactlyBytes));

    /// <summary>
    /// The destination is exactly {0} bytes.
    /// </summary>
    internal static string FormatBlobKeyDeriver_DestinationExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobKeyDeriver_DestinationExactlyBytes, arg0);

    /// <summary>
    /// The content-ID key is exactly 32 bytes.
    /// </summary>
    internal static string HardlinkGrouper_ContentIDKeyExactlyBytes => Get(nameof(HardlinkGrouper_ContentIDKeyExactlyBytes));

    /// <summary>
    /// The master key is exactly 32 bytes.
    /// </summary>
    internal static string RecoveryRecipient_MasterKeyExactlyBytes => Get(nameof(RecoveryRecipient_MasterKeyExactlyBytes));

    /// <summary>
    /// The KDF salt is exactly {0} bytes; got {1}.
    /// </summary>
    private static string KekDerivation_KDFSaltExactlyBytesGot => Get(nameof(KekDerivation_KDFSaltExactlyBytesGot));

    /// <summary>
    /// The KDF salt is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatKekDerivation_KDFSaltExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, KekDerivation_KDFSaltExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// The device identifier is exactly 16 bytes.
    /// </summary>
    internal static string KeyedFileIdentity_DeviceIdentifierExactlyBytes => Get(nameof(KeyedFileIdentity_DeviceIdentifierExactlyBytes));

    /// <summary>
    /// An empty password is refused. The primitive accepts one, so refusing is the engine's job (ADR-0045 §4).
    /// </summary>
    internal static string PasswordHash_EmptyPasswordRefused => Get(nameof(PasswordHash_EmptyPasswordRefused));

    /// <summary>
    /// An empty passphrase is refused at repository creation. The primitive accepts one, so refusing is the engine's job (specification 03 §2.1).
    /// </summary>
    internal static string Passphrase_EmptyPassphraseRefusedRepositoryCreation => Get(nameof(Passphrase_EmptyPassphraseRefusedRepositoryCreation));

    /// <summary>
    /// The key-ID key is exactly 32 bytes.
    /// </summary>
    internal static string StoreBlobKeyDeriver_KeyIDKeyExactlyBytes => Get(nameof(StoreBlobKeyDeriver_KeyIDKeyExactlyBytes));

    /// <summary>
    /// The content key is exactly {0} bytes.
    /// </summary>
    private static string ContentSealing_ContentKeyExactlyBytes => Get(nameof(ContentSealing_ContentKeyExactlyBytes));

    /// <summary>
    /// The content key is exactly {0} bytes.
    /// </summary>
    internal static string FormatContentSealing_ContentKeyExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ContentSealing_ContentKeyExactlyBytes, arg0);

    /// <summary>
    /// The sealed content key does not open with this repository's restore material.
    /// </summary>
    internal static string ContentSealing_DoesNotOpen => Get(nameof(ContentSealing_DoesNotOpen));

    /// <summary>
    /// An X25519 key is exactly {0} bytes.
    /// </summary>
    private static string ContentSealing_KeyExactlyBytes => Get(nameof(ContentSealing_KeyExactlyBytes));

    /// <summary>
    /// An X25519 key is exactly {0} bytes.
    /// </summary>
    internal static string FormatContentSealing_KeyExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ContentSealing_KeyExactlyBytes, arg0);

    /// <summary>
    /// The recipient public key is a low-order point — sealing to it would derive an attacker-known secret, so it is refused.
    /// </summary>
    internal static string ContentSealing_LowOrderRecipient => Get(nameof(ContentSealing_LowOrderRecipient));

    /// <summary>
    /// The sealed share offers a low-order point and is refused.
    /// </summary>
    internal static string ContentSealing_LowOrderShare => Get(nameof(ContentSealing_LowOrderShare));

    /// <summary>
    /// A sealed content key is exactly {0} bytes.
    /// </summary>
    private static string ContentSealing_SealedExactlyBytes => Get(nameof(ContentSealing_SealedExactlyBytes));

    /// <summary>
    /// A sealed content key is exactly {0} bytes.
    /// </summary>
    internal static string FormatContentSealing_SealedExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ContentSealing_SealedExactlyBytes, arg0);

    /// <summary>
    /// A serialised write credential is exactly {0} bytes with its magic intact.
    /// </summary>
    private static string RepositoryWriteCredential_SerialisedExactlyBytes => Get(nameof(RepositoryWriteCredential_SerialisedExactlyBytes));

    /// <summary>
    /// A serialised write credential is exactly {0} bytes with its magic intact.
    /// </summary>
    internal static string FormatRepositoryWriteCredential_SerialisedExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, RepositoryWriteCredential_SerialisedExactlyBytes, arg0);

    /// <summary>
    /// The derivation root is exactly {0} bytes.
    /// </summary>
    private static string WriteOnlyDerivation_RootExactlyBytes => Get(nameof(WriteOnlyDerivation_RootExactlyBytes));

    /// <summary>
    /// The derivation root is exactly {0} bytes.
    /// </summary>
    internal static string FormatWriteOnlyDerivation_RootExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, WriteOnlyDerivation_RootExactlyBytes, arg0);

    /// <summary>
    /// A write credential carrying a claim public key carries a reclaim public key too: the serialised shapes are nested, so a later member cannot be present while an earlier one is absent.
    /// </summary>
    internal static string RepositoryWriteCredential_ClaimNeedsReclaim => Get(nameof(RepositoryWriteCredential_ClaimNeedsReclaim));

    /// <summary>
    /// A reclaim key seed is exactly {0} bytes.
    /// </summary>
    private static string WriteOnlyDerivation_ReclaimSeedExactlyBytes => Get(nameof(WriteOnlyDerivation_ReclaimSeedExactlyBytes));

    /// <summary>
    /// A reclaim key seed is exactly {0} bytes.
    /// </summary>
    internal static string FormatWriteOnlyDerivation_ReclaimSeedExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, WriteOnlyDerivation_ReclaimSeedExactlyBytes, arg0);

    /// <summary>
    /// A reclaim sub-root is exactly {0} bytes.
    /// </summary>
    private static string ReclaimAuthority_RootExactlyBytes => Get(nameof(ReclaimAuthority_RootExactlyBytes));

    /// <summary>
    /// A reclaim sub-root is exactly {0} bytes.
    /// </summary>
    internal static string FormatReclaimAuthority_RootExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, ReclaimAuthority_RootExactlyBytes, arg0);
}
