// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Repository.Crypto.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Repository.Crypto.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Repository.Crypto.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// The blob salt is exactly {0} bytes.
    /// </summary>
    private static string BlobKeyDeriver_BlobSaltExactlyBytes => Get(nameof(BlobKeyDeriver_BlobSaltExactlyBytes));

    /// <summary>
    /// The blob salt is exactly {0} bytes.
    /// </summary>
    internal static string FormatBlobKeyDeriver_BlobSaltExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobKeyDeriver_BlobSaltExactlyBytes, arg0);

    /// <summary>
    /// The class key is exactly 32 bytes.
    /// </summary>
    internal static string BlobKeyDeriver_ClassKeyExactlyBytes => Get(nameof(BlobKeyDeriver_ClassKeyExactlyBytes));

    /// <summary>
    /// The destination is exactly {0} bytes.
    /// </summary>
    private static string BlobKeyDeriver_DestinationExactlyBytes => Get(nameof(BlobKeyDeriver_DestinationExactlyBytes));

    /// <summary>
    /// The destination is exactly {0} bytes.
    /// </summary>
    internal static string FormatBlobKeyDeriver_DestinationExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, BlobKeyDeriver_DestinationExactlyBytes, arg0);

    /// <summary>
    /// The content-ID key is exactly 32 bytes.
    /// </summary>
    internal static string HardlinkGrouper_ContentIDKeyExactlyBytes => Get(nameof(HardlinkGrouper_ContentIDKeyExactlyBytes));

    /// <summary>
    /// The KDF salt is exactly {0} bytes; got {1}.
    /// </summary>
    private static string KekDerivation_KDFSaltExactlyBytesGot => Get(nameof(KekDerivation_KDFSaltExactlyBytesGot));

    /// <summary>
    /// The KDF salt is exactly {0} bytes; got {1}.
    /// </summary>
    internal static string FormatKekDerivation_KDFSaltExactlyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, KekDerivation_KDFSaltExactlyBytesGot, arg0, arg1);

    /// <summary>
    /// The master key is exactly {0} bytes.
    /// </summary>
    private static string KeyHierarchy_MasterKeyExactlyBytes => Get(nameof(KeyHierarchy_MasterKeyExactlyBytes));

    /// <summary>
    /// The master key is exactly {0} bytes.
    /// </summary>
    internal static string FormatKeyHierarchy_MasterKeyExactlyBytes(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, KeyHierarchy_MasterKeyExactlyBytes, arg0);

    /// <summary>
    /// The device identifier is exactly 16 bytes.
    /// </summary>
    internal static string KeyedFileIdentity_DeviceIdentifierExactlyBytes => Get(nameof(KeyedFileIdentity_DeviceIdentifierExactlyBytes));

    /// <summary>
    /// An empty passphrase is refused at repository creation. The primitive accepts one, so refusing is the engine's job (specification 03 §2.1).
    /// </summary>
    internal static string Passphrase_EmptyPassphraseRefusedRepositoryCreation => Get(nameof(Passphrase_EmptyPassphraseRefusedRepositoryCreation));

    /// <summary>
    /// The key-ID key is exactly 32 bytes.
    /// </summary>
    internal static string StoreBlobKeyDeriver_KeyIDKeyExactlyBytes => Get(nameof(StoreBlobKeyDeriver_KeyIDKeyExactlyBytes));
}
