// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Repository.Segmentation.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Repository.Segmentation.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Repository.Segmentation.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// The buffer must hold the maximum segment size ({0} bytes); got {1}.
    /// </summary>
    private static string CdcSegmentReader_BufferMustHoldMaximumSegment => Get(nameof(CdcSegmentReader_BufferMustHoldMaximumSegment));

    /// <summary>
    /// The buffer must hold the maximum segment size ({0} bytes); got {1}.
    /// </summary>
    internal static string FormatCdcSegmentReader_BufferMustHoldMaximumSegment(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, CdcSegmentReader_BufferMustHoldMaximumSegment, arg0, arg1);

    /// <summary>
    /// The cdc parameters are unset; construct them via CdcParameters.Create (specification 09 §3.1).
    /// </summary>
    internal static string CdcSegmentReader_CdcParametersUnsetConstructThem => Get(nameof(CdcSegmentReader_CdcParametersUnsetConstructThem));

    /// <summary>
    /// The source stream must be readable.
    /// </summary>
    internal static string CdcSegmentReader_SourceStreamMustReadable => Get(nameof(CdcSegmentReader_SourceStreamMustReadable));

    /// <summary>
    /// The buffer must hold at least one segment ({0} bytes); got {1}.
    /// </summary>
    private static string FixedSegmentReader_BufferMustHoldLeastOne => Get(nameof(FixedSegmentReader_BufferMustHoldLeastOne));

    /// <summary>
    /// The buffer must hold at least one segment ({0} bytes); got {1}.
    /// </summary>
    internal static string FormatFixedSegmentReader_BufferMustHoldLeastOne(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, FixedSegmentReader_BufferMustHoldLeastOne, arg0, arg1);

    /// <summary>
    /// The segment size is unset; construct it via SegmentSize.Create (specification 09 §2.2).
    /// </summary>
    internal static string FixedSegmentReader_SegmentSizeUnsetConstructVia => Get(nameof(FixedSegmentReader_SegmentSizeUnsetConstructVia));
}
