// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Protocol.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Protocol.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Protocol.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// The peer offered a low-order X25519 point, which would fix the shared secret.
    /// </summary>
    internal static string PairingExchange_PeerOfferedLowOrderX => Get(nameof(PairingExchange_PeerOfferedLowOrderX));

    /// <summary>
    /// An ephemeral key is {0} bytes; got {1}.
    /// </summary>
    private static string PairingTranscript_EphemeralKeyBytesGot => Get(nameof(PairingTranscript_EphemeralKeyBytesGot));

    /// <summary>
    /// An ephemeral key is {0} bytes; got {1}.
    /// </summary>
    internal static string FormatPairingTranscript_EphemeralKeyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, PairingTranscript_EphemeralKeyBytesGot, arg0, arg1);

    /// <summary>
    /// A pairing nonce is {0} bytes; got {1}.
    /// </summary>
    private static string PairingTranscript_PairingNonceBytesGot => Get(nameof(PairingTranscript_PairingNonceBytesGot));

    /// <summary>
    /// A pairing nonce is {0} bytes; got {1}.
    /// </summary>
    internal static string FormatPairingTranscript_PairingNonceBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, PairingTranscript_PairingNonceBytesGot, arg0, arg1);

    /// <summary>
    /// An X25519 shared secret is {0} bytes; got {1}.
    /// </summary>
    private static string PairingTranscript_XSharedSecretBytesGot => Get(nameof(PairingTranscript_XSharedSecretBytesGot));

    /// <summary>
    /// An X25519 shared secret is {0} bytes; got {1}.
    /// </summary>
    internal static string FormatPairingTranscript_XSharedSecretBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, PairingTranscript_XSharedSecretBytesGot, arg0, arg1);

    /// <summary>
    /// This device already holds {0} peer grants, which is the limit.
    /// </summary>
    private static string PeerGrantStore_DeviceAlreadyHoldsPeerGrants => Get(nameof(PeerGrantStore_DeviceAlreadyHoldsPeerGrants));

    /// <summary>
    /// This device already holds {0} peer grants, which is the limit.
    /// </summary>
    internal static string FormatPeerGrantStore_DeviceAlreadyHoldsPeerGrants(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, PeerGrantStore_DeviceAlreadyHoldsPeerGrants, arg0);

    /// <summary>
    /// No grant exists for peer {0}.
    /// </summary>
    private static string PeerGrantStore_NoGrantExistsPeer => Get(nameof(PeerGrantStore_NoGrantExistsPeer));

    /// <summary>
    /// No grant exists for peer {0}.
    /// </summary>
    internal static string FormatPeerGrantStore_NoGrantExistsPeer(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, PeerGrantStore_NoGrantExistsPeer, arg0);

    /// <summary>
    /// The peer grants at '{0}' could not be read. Pairings are not rebuildable — restore the file or re-pair deliberately.
    /// </summary>
    private static string PeerGrantStore_PeerGrantsCouldNotRead => Get(nameof(PeerGrantStore_PeerGrantsCouldNotRead));

    /// <summary>
    /// The peer grants at '{0}' could not be read. Pairings are not rebuildable — restore the file or re-pair deliberately.
    /// </summary>
    internal static string FormatPeerGrantStore_PeerGrantsCouldNotRead(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, PeerGrantStore_PeerGrantsCouldNotRead, arg0);

    /// <summary>
    /// A peer identity is {0} bytes; got {1}.
    /// </summary>
    private static string PeerIdentity_PeerIdentityBytesGot => Get(nameof(PeerIdentity_PeerIdentityBytesGot));

    /// <summary>
    /// A peer identity is {0} bytes; got {1}.
    /// </summary>
    internal static string FormatPeerIdentity_PeerIdentityBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, PeerIdentity_PeerIdentityBytesGot, arg0, arg1);

    /// <summary>
    /// A peer private key is {0} bytes; got {1}.
    /// </summary>
    private static string PeerKeypair_PeerPrivateKeyBytesGot => Get(nameof(PeerKeypair_PeerPrivateKeyBytesGot));

    /// <summary>
    /// A peer private key is {0} bytes; got {1}.
    /// </summary>
    internal static string FormatPeerKeypair_PeerPrivateKeyBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, PeerKeypair_PeerPrivateKeyBytesGot, arg0, arg1);

    /// <summary>
    /// A binding nonce is {0} bytes; got {1}.
    /// </summary>
    private static string SessionBinding_BindingNonceBytesGot => Get(nameof(SessionBinding_BindingNonceBytesGot));

    /// <summary>
    /// A binding nonce is {0} bytes; got {1}.
    /// </summary>
    internal static string FormatSessionBinding_BindingNonceBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, SessionBinding_BindingNonceBytesGot, arg0, arg1);

    /// <summary>
    /// A channel binding is {0} bytes; got {1}.
    /// </summary>
    private static string SessionBinding_ChannelBindingBytesGot => Get(nameof(SessionBinding_ChannelBindingBytesGot));

    /// <summary>
    /// A channel binding is {0} bytes; got {1}.
    /// </summary>
    internal static string FormatSessionBinding_ChannelBindingBytesGot(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, SessionBinding_ChannelBindingBytesGot, arg0, arg1);
}
