// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Storage.S3.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Storage.S3.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Storage.S3.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// An S3-compatible store's credentials need both an access key id and the secret that signs for it.
    /// </summary>
    internal static string S3Credentials_Incomplete => Get(nameof(S3Credentials_Incomplete));

    /// <summary>
    /// The endpoint '{0}' is not a base URL: give a scheme, a host and, where it is not the scheme's own, a port — for example https://objects.example.net.
    /// </summary>
    private static string S3Location_EndpointNotABaseUrl => Get(nameof(S3Location_EndpointNotABaseUrl));

    /// <summary>
    /// The endpoint '{0}' is not a base URL: give a scheme, a host and, where it is not the scheme's own, a port — for example https://objects.example.net.
    /// </summary>
    internal static string FormatS3Location_EndpointNotABaseUrl(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, S3Location_EndpointNotABaseUrl, arg0);

    /// <summary>
    /// The endpoint '{0}' is not https. Only a store on this machine is spoken to in clear: anything further away is reached through whoever is in between.
    /// </summary>
    private static string S3Location_EndpointInClear => Get(nameof(S3Location_EndpointInClear));

    /// <summary>
    /// The endpoint '{0}' is not https. Only a store on this machine is spoken to in clear: anything further away is reached through whoever is in between.
    /// </summary>
    internal static string FormatS3Location_EndpointInClear(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, S3Location_EndpointInClear, arg0);

    /// <summary>
    /// '{0}' is not a bucket name: 3 to 63 lowercase letters, digits, dots and hyphens, starting and ending with a letter or a digit.
    /// </summary>
    private static string S3Location_BucketNameInvalid => Get(nameof(S3Location_BucketNameInvalid));

    /// <summary>
    /// '{0}' is not a bucket name: 3 to 63 lowercase letters, digits, dots and hyphens, starting and ending with a letter or a digit.
    /// </summary>
    internal static string FormatS3Location_BucketNameInvalid(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, S3Location_BucketNameInvalid, arg0);

    /// <summary>
    /// '{0}' is not a region: lowercase letters, digits and hyphens, such as us-east-1.
    /// </summary>
    private static string S3Location_RegionInvalid => Get(nameof(S3Location_RegionInvalid));

    /// <summary>
    /// '{0}' is not a region: lowercase letters, digits and hyphens, such as us-east-1.
    /// </summary>
    internal static string FormatS3Location_RegionInvalid(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, S3Location_RegionInvalid, arg0);

    /// <summary>
    /// '{0}' is not a prefix: folders of lowercase letters, digits, dots, underscores and hyphens, separated by '/', none starting with a dot.
    /// </summary>
    private static string S3Location_PrefixInvalid => Get(nameof(S3Location_PrefixInvalid));

    /// <summary>
    /// '{0}' is not a prefix: folders of lowercase letters, digits, dots, underscores and hyphens, separated by '/', none starting with a dot.
    /// </summary>
    internal static string FormatS3Location_PrefixInvalid(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, S3Location_PrefixInvalid, arg0);

    /// <summary>
    /// '{0}' is {1} bytes; one request to an S3-compatible store carries at most {2}.
    /// </summary>
    private static string S3ObjectStore_ObjectTooLarge => Get(nameof(S3ObjectStore_ObjectTooLarge));

    /// <summary>
    /// '{0}' is {1} bytes; one request to an S3-compatible store carries at most {2}.
    /// </summary>
    internal static string FormatS3ObjectStore_ObjectTooLarge(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, S3ObjectStore_ObjectTooLarge, arg0, arg1, arg2);

    /// <summary>
    /// The S3-compatible store answered a listing that cannot be read ({0}).
    /// </summary>
    private static string S3ObjectStore_ListingUnreadable => Get(nameof(S3ObjectStore_ListingUnreadable));

    /// <summary>
    /// The S3-compatible store answered a listing that cannot be read ({0}).
    /// </summary>
    internal static string FormatS3ObjectStore_ListingUnreadable(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, S3ObjectStore_ListingUnreadable, arg0);

    /// <summary>
    /// The S3-compatible store could not be reached for a {0} after {1} attempt(s): {2}
    /// </summary>
    private static string S3ObjectStore_Unreachable => Get(nameof(S3ObjectStore_Unreachable));

    /// <summary>
    /// The S3-compatible store could not be reached for a {0} after {1} attempt(s): {2}
    /// </summary>
    internal static string FormatS3ObjectStore_Unreachable(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, S3ObjectStore_Unreachable, arg0, arg1, arg2);

    /// <summary>
    /// The S3-compatible store refused a {0} of '{1}': {2} {3}. {4}
    /// </summary>
    private static string S3ObjectStore_Refused => Get(nameof(S3ObjectStore_Refused));

    /// <summary>
    /// The S3-compatible store refused a {0} of '{1}': {2} {3}. {4}
    /// </summary>
    internal static string FormatS3ObjectStore_Refused(object? arg0, object? arg1, object? arg2, object? arg3, object? arg4) =>
        string.Format(CultureInfo.CurrentCulture, S3ObjectStore_Refused, arg0, arg1, arg2, arg3, arg4);

    /// <summary>
    /// The S3-compatible store was too busy to serve a {0} of '{1}' on any attempt: {2} {3}. {4} The next pass asks again.
    /// </summary>
    private static string S3ObjectStore_Busy => Get(nameof(S3ObjectStore_Busy));

    /// <summary>
    /// The S3-compatible store was too busy to serve a {0} of '{1}' on any attempt: {2} {3}. {4} The next pass asks again.
    /// </summary>
    internal static string FormatS3ObjectStore_Busy(object? arg0, object? arg1, object? arg2, object? arg3, object? arg4) =>
        string.Format(CultureInfo.CurrentCulture, S3ObjectStore_Busy, arg0, arg1, arg2, arg3, arg4);

    /// <summary>
    /// The S3-compatible store has no room for '{1}': it answered a {0} with {2} {3}. {4} Once room is made there, the next pass goes on from where this one stopped.
    /// </summary>
    private static string S3ObjectStore_Full => Get(nameof(S3ObjectStore_Full));

    /// <summary>
    /// The S3-compatible store has no room for '{1}': it answered a {0} with {2} {3}. {4} Once room is made there, the next pass goes on from where this one stopped.
    /// </summary>
    internal static string FormatS3ObjectStore_Full(object? arg0, object? arg1, object? arg2, object? arg3, object? arg4) =>
        string.Format(CultureInfo.CurrentCulture, S3ObjectStore_Full, arg0, arg1, arg2, arg3, arg4);

    /// <summary>
    /// The S3-compatible store's quota would be crossed by '{1}': it answered a {0} with {2} {3}. {4} Raise the quota, or keep less at this destination.
    /// </summary>
    private static string S3ObjectStore_QuotaExceeded => Get(nameof(S3ObjectStore_QuotaExceeded));

    /// <summary>
    /// The S3-compatible store's quota would be crossed by '{1}': it answered a {0} with {2} {3}. {4} Raise the quota, or keep less at this destination.
    /// </summary>
    internal static string FormatS3ObjectStore_QuotaExceeded(object? arg0, object? arg1, object? arg2, object? arg3, object? arg4) =>
        string.Format(CultureInfo.CurrentCulture, S3ObjectStore_QuotaExceeded, arg0, arg1, arg2, arg3, arg4);

    /// <summary>
    /// The S3-compatible store's answer ended before the object it was sending did.
    /// </summary>
    internal static string S3ObjectStore_BodyEndedEarly => Get(nameof(S3ObjectStore_BodyEndedEarly));
}
