// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Storage.Local.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Storage.Local.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Storage.Local.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// Key '{0}' resolves outside the store root.
    /// </summary>
    private static string LocalFileSystemObjectStore_KeyResolvesOutsideStoreRoot => Get(nameof(LocalFileSystemObjectStore_KeyResolvesOutsideStoreRoot));

    /// <summary>
    /// Key '{0}' resolves outside the store root.
    /// </summary>
    internal static string FormatLocalFileSystemObjectStore_KeyResolvesOutsideStoreRoot(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, LocalFileSystemObjectStore_KeyResolvesOutsideStoreRoot, arg0);

    /// <summary>
    /// The object key is empty.
    /// </summary>
    internal static string LocalFileSystemObjectStore_ObjectKeyEmpty => Get(nameof(LocalFileSystemObjectStore_ObjectKeyEmpty));

    /// <summary>
    /// Refusing to traverse the symlinked directory '{0}' inside the store root.
    /// </summary>
    private static string LocalFileSystemObjectStore_RefusingTraverseSymlinkedDirectoryInside => Get(nameof(LocalFileSystemObjectStore_RefusingTraverseSymlinkedDirectoryInside));

    /// <summary>
    /// Refusing to traverse the symlinked directory '{0}' inside the store root.
    /// </summary>
    internal static string FormatLocalFileSystemObjectStore_RefusingTraverseSymlinkedDirectoryInside(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, LocalFileSystemObjectStore_RefusingTraverseSymlinkedDirectoryInside, arg0);
}
