// <auto-generated>
//     Generated by eng/generate-resources.py from Strings.resx.
//     Edit the resx, then re-run the generator; edits here are overwritten.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace FallbackPlan.Api.Resources;

/// <summary>
/// The translated messages for FallbackPlan.Api.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager Manager =
        new("FallbackPlan.Api.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The message for <paramref name="name"/> in the caller's UI culture.</summary>
    private static string Get(string name) =>
        Manager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    /// <summary>
    /// A {0}-byte frame exceeds the {1}-byte limit.
    /// </summary>
    private static string FrameCodec_ByteFrameExceedsByteLimit => Get(nameof(FrameCodec_ByteFrameExceedsByteLimit));

    /// <summary>
    /// A {0}-byte frame exceeds the {1}-byte limit.
    /// </summary>
    internal static string FormatFrameCodec_ByteFrameExceedsByteLimit(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, FrameCodec_ByteFrameExceedsByteLimit, arg0, arg1);

    /// <summary>
    /// A frame declared {0} bytes, which is outside 1..{1}.
    /// </summary>
    private static string FrameCodec_FrameDeclaredBytesWhichOutside => Get(nameof(FrameCodec_FrameDeclaredBytesWhichOutside));

    /// <summary>
    /// A frame declared {0} bytes, which is outside 1..{1}.
    /// </summary>
    internal static string FormatFrameCodec_FrameDeclaredBytesWhichOutside(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, FrameCodec_FrameDeclaredBytesWhichOutside, arg0, arg1);

    /// <summary>
    /// A frame decoded to nothing.
    /// </summary>
    internal static string FrameCodec_FrameDecodedNothing => Get(nameof(FrameCodec_FrameDecodedNothing));

    /// <summary>
    /// A frame ended before its declared length.
    /// </summary>
    internal static string FrameCodec_FrameEndedBeforeDeclaredLength => Get(nameof(FrameCodec_FrameEndedBeforeDeclaredLength));

    /// <summary>
    /// A frame was not valid JSON: {0}
    /// </summary>
    private static string FrameCodec_FrameNotValidJSON => Get(nameof(FrameCodec_FrameNotValidJSON));

    /// <summary>
    /// A frame was not valid JSON: {0}
    /// </summary>
    internal static string FormatFrameCodec_FrameNotValidJSON(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, FrameCodec_FrameNotValidJSON, arg0);

    /// <summary>
    /// The peer closed mid-frame.
    /// </summary>
    internal static string FrameCodec_PeerClosedMidFrame => Get(nameof(FrameCodec_PeerClosedMidFrame));

    /// <summary>
    /// The socket path '{0}' is {1} bytes, and the platform accepts at most {2}. Choose a shorter state directory — this limit is the operating system's, not this program's.
    /// </summary>
    private static string LocalEndpoint_SocketPathBytesPlatformAccepts => Get(nameof(LocalEndpoint_SocketPathBytesPlatformAccepts));

    /// <summary>
    /// The socket path '{0}' is {1} bytes, and the platform accepts at most {2}. Choose a shorter state directory — this limit is the operating system's, not this program's.
    /// </summary>
    internal static string FormatLocalEndpoint_SocketPathBytesPlatformAccepts(object? arg0, object? arg1, object? arg2) =>
        string.Format(CultureInfo.CurrentCulture, LocalEndpoint_SocketPathBytesPlatformAccepts, arg0, arg1, arg2);

    /// <summary>
    /// No service is listening on '{0}'.
    /// </summary>
    private static string LocalServiceClient_NoServiceListening => Get(nameof(LocalServiceClient_NoServiceListening));

    /// <summary>
    /// No service is listening on '{0}'.
    /// </summary>
    internal static string FormatLocalServiceClient_NoServiceListening(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, LocalServiceClient_NoServiceListening, arg0);

    /// <summary>
    /// The service answered request {0} while {1} was outstanding.
    /// </summary>
    private static string LocalServiceClient_ServiceAnsweredRequestWhileOutstanding => Get(nameof(LocalServiceClient_ServiceAnsweredRequestWhileOutstanding));

    /// <summary>
    /// The service answered request {0} while {1} was outstanding.
    /// </summary>
    internal static string FormatLocalServiceClient_ServiceAnsweredRequestWhileOutstanding(object? arg0, object? arg1) =>
        string.Format(CultureInfo.CurrentCulture, LocalServiceClient_ServiceAnsweredRequestWhileOutstanding, arg0, arg1);

    /// <summary>
    /// The service closed the connection without answering.
    /// </summary>
    internal static string LocalServiceClient_ServiceClosedConnectionWithoutAnswering => Get(nameof(LocalServiceClient_ServiceClosedConnectionWithoutAnswering));

    /// <summary>
    /// The service at '{0}' did not answer the contract handshake.
    /// </summary>
    private static string LocalServiceClient_ServiceDidNotAnswerContract => Get(nameof(LocalServiceClient_ServiceDidNotAnswerContract));

    /// <summary>
    /// The service at '{0}' did not answer the contract handshake.
    /// </summary>
    internal static string FormatLocalServiceClient_ServiceDidNotAnswerContract(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, LocalServiceClient_ServiceDidNotAnswerContract, arg0);

    /// <summary>
    /// The service reported contract version '{0}', which is not a version.
    /// </summary>
    private static string LocalServiceClient_ServiceReportedContractVersionWhich => Get(nameof(LocalServiceClient_ServiceReportedContractVersionWhich));

    /// <summary>
    /// The service reported contract version '{0}', which is not a version.
    /// </summary>
    internal static string FormatLocalServiceClient_ServiceReportedContractVersionWhich(object? arg0) =>
        string.Format(CultureInfo.CurrentCulture, LocalServiceClient_ServiceReportedContractVersionWhich, arg0);

    /// <summary>
    /// The service sent a frame that is not a response.
    /// </summary>
    internal static string LocalServiceClient_ServiceSentFrameNotResponse => Get(nameof(LocalServiceClient_ServiceSentFrameNotResponse));
}
